In [ ]:
# ============================================================
# Fresh runtime: Mount Google Drive and check project folder
# ============================================================

from google.colab import drive
drive.mount("/content/drive")

from pathlib import Path

PROJECT_ROOT = Path("/content/drive/MyDrive/UM_WQF7023/MRDRP-main")

print("PROJECT_ROOT exists:", PROJECT_ROOT.exists())
print("PROJECT_ROOT:", PROJECT_ROOT)

if PROJECT_ROOT.exists():
    print("\nItems directly under PROJECT_ROOT:")
    for p in sorted(PROJECT_ROOT.iterdir()):
        print("DIR " if p.is_dir() else "FILE", "-", p.name)
else:
    print("Project folder not found. Please check the Google Drive path.")

Mounted at /content/drive
PROJECT_ROOT exists: True
PROJECT_ROOT: /content/drive/MyDrive/UM_WQF7023/MRDRP-main

Items directly under PROJECT_ROOT:
FILE - LICENSE
FILE - MR-Icon.png
FILE - MRanalysis.py
FILE - MRanalysis_backup.py
FILE - MRdata.py
FILE - README.md
DIR  - __pycache__
FILE - analysis_set_record.csv
FILE - app.py
FILE - artesunate_file_screening_record.csv
DIR  - backend_work
DIR  - exposures
FILE - file_screening_record.csv
FILE - index.html
DIR  - outcome
DIR  - output_mr
DIR  - output_sig
FILE - pair_selection_record.csv
FILE - pair_selection_record.gsheet
DIR  - test

In [ ]:
# ============================================================
# Cell 1.1: Check Colab environment
# ============================================================

import os
import sys
import platform

print("Python version:", sys.version)
print("Platform:", platform.platform())
print("Current working directory:", os.getcwd())

Python version: 3.12.13 (main, Mar  4 2026, 09:23:07) [GCC 11.4.0]
Platform: Linux-6.6.122+-x86_64-with-glibc2.35
Current working directory: /content

In [ ]:
# ============================================================
# Cell 1.2: Update apt package list
# ============================================================

!apt-get update -qq

print("apt-get update finished.")

W: Skipping acquire of configured file 'main/source/Sources' as repository 'https://r2u.stat.illinois.edu/ubuntu jammy InRelease' does not seem to provide it (sources.list entry misspelt?)
apt-get update finished.

In [ ]:
# ============================================================
# Cell 1.3: Install R base environment
# ============================================================

!apt-get install -y -qq r-base r-base-dev

print("R base installation finished.")

R base installation finished.

In [ ]:
# ============================================================
# Cell 1.4: Install system libraries required by R packages
# ============================================================

!apt-get install -y -qq \
    libcurl4-openssl-dev \
    libssl-dev \
    libxml2-dev \
    libgit2-dev \
    git curl wget unzip

print("System library installation finished.")

System library installation finished.

In [ ]:
# ============================================================
# Cell 1.5: Install Python packages
# ============================================================

!pip install -q pandas numpy matplotlib seaborn rpy2 psutil

print("Python package installation finished.")

Python package installation finished.

In [ ]:
# ============================================================
# Cell 1.6: Check R installation
# ============================================================

!R --version

R version 4.6.0 (2026-04-24) -- "Because it was There"
Copyright (C) 2026 The R Foundation for Statistical Computing
Platform: x86_64-pc-linux-gnu

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under the terms of the
GNU General Public License versions 2 or 3.
For more information about these matters see
https://www.gnu.org/licenses/.

In [ ]:
# ============================================================
# Cell 1.7: Install basic R packages
# ============================================================

!R -q -e "options(repos = c(CRAN='https://cloud.r-project.org')); install.packages(c('remotes','ggplot2','data.table'))"

print("Basic R packages installation finished.")

> options(repos = c(CRAN='https://cloud.r-project.org')); install.packages(c('remotes','ggplot2','data.table'))
Installing packages into ‘/usr/local/lib/R/site-library’
(as ‘lib’ is unspecified)
trying URL 'https://cloud.r-project.org/src/contrib/remotes_2.5.0.tar.gz'
trying URL 'https://cloud.r-project.org/src/contrib/ggplot2_4.0.3.tar.gz'
trying URL 'https://cloud.r-project.org/src/contrib/data.table_1.18.4.tar.gz'
* installing *source* package ‘remotes’ ...
** this is package ‘remotes’ version ‘2.5.0’
** package ‘remotes’ successfully unpacked and MD5 sums checked
** using staged installation
** R
** inst
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
** building package indices
** installing vignettes
** testing if installed package can be loaded from temporary location
** testing if installed package can be loaded from final location
** testing if installed package keeps a record of temporary installation path
* DONE (remotes)
* installing *source* package ‘ggplot2’ ...
** this is package ‘ggplot2’ version ‘4.0.3’
** package ‘ggplot2’ successfully unpacked and MD5 sums checked
** using staged installation
** R
** data
*** moving datasets to lazyload DB
** inst
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
*** copying figures
** building package indices
** installing vignettes
** testing if installed package can be loaded from temporary location
** testing if installed package can be loaded from final location
** testing if installed package keeps a record of temporary installation path
* DONE (ggplot2)
* installing *source* package ‘data.table’ ...
** this is package ‘data.table’ version ‘1.18.4’
** package ‘data.table’ successfully unpacked and MD5 sums checked
** using staged installation
zlib 1.2.11 is available ok
* checking if R installation supports OpenMP without any extra hints... yes
** libs
using C compiler: ‘cc (Ubuntu 11.4.0-1ubuntu1~22.04.3) 11.4.0’
cc -I"/usr/share/R/include" -DNDEBUG      -fvisibility=hidden  -fopenmp  -fpic  -g -O2 -ffile-prefix-map=/build/r-base-gN72Ro/r-base-4.6.0=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2  -c assign.c -o assign.o
cc -I"/usr/share/R/include" -DNDEBUG      -fvisibility=hidden  -fopenmp  -fpic  -g -O2 -ffile-prefix-map=/build/r-base-gN72Ro/r-base-4.6.0=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2  -c between.c -o between.o
cc -I"/usr/share/R/include" -DNDEBUG      -fvisibility=hidden  -fopenmp  -fpic  -g -O2 -ffile-prefix-map=/build/r-base-gN72Ro/r-base-4.6.0=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2  -c bmerge.c -o bmerge.o
cc -I"/usr/share/R/include" -DNDEBUG      -fvisibility=hidden  -fopenmp  -fpic  -g -O2 -ffile-prefix-map=/build/r-base-gN72Ro/r-base-4.6.0=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2  -c chmatch.c -o chmatch.o
cc -I"/usr/share/R/include" -DNDEBUG      -fvisibility=hidden  -fopenmp  -fpic  -g -O2 -ffile-prefix-map=/build/r-base-gN72Ro/r-base-4.6.0=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2  -c cj.c -o cj.o
cc -I"/usr/share/R/include" -DNDEBUG      -fvisibility=hidden  -fopenmp  -fpic  -g -O2 -ffile-prefix-map=/build/r-base-gN72Ro/r-base-4.6.0=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2  -c coalesce.c -o coalesce.o
cc -I"/usr/share/R/include" -DNDEBUG      -fvisibility=hidden  -fopenmp  -fpic  -g -O2 -ffile-prefix-map=/build/r-base-gN72Ro/r-base-4.6.0=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2  -c dogroups.c -o dogroups.o
cc -I"/usr/share/R/include" -DNDEBUG      -fvisibility=hidden  -fopenmp  -fpic  -g -O2 -ffile-prefix-map=/build/r-base-gN72Ro/r-base-4.6.0=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2  -c fastmean.c -o fastmean.o
cc -I"/usr/share/R/include" -DNDEBUG      -fvisibility=hidden  -fopenmp  -fpic  -g -O2 -ffile-prefix-map=/build/r-base-gN72Ro/r-base-4.6.0=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2  -c fcast.c -o fcast.o
cc -I"/usr/share/R/include" -DNDEBUG      -fvisibility=hidden  -fopenmp  -fpic  -g -O2 -ffile-prefix-map=/build/r-base-gN72Ro/r-base-4.6.0=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2  -c fifelse.c -o fifelse.o
cc -I"/usr/share/R/include" -DNDEBUG      -fvisibility=hidden  -fopenmp  -fpic  -g -O2 -ffile-prefix-map=/build/r-base-gN72Ro/r-base-4.6.0=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2  -c fmelt.c -o fmelt.o
cc -I"/usr/share/R/include" -DNDEBUG      -fvisibility=hidden  -fopenmp  -fpic  -g -O2 -ffile-prefix-map=/build/r-base-gN72Ro/r-base-4.6.0=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2  -c forder.c -o forder.o
cc -I"/usr/share/R/include" -DNDEBUG      -fvisibility=hidden  -fopenmp  -fpic  -g -O2 -ffile-prefix-map=/build/r-base-gN72Ro/r-base-4.6.0=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2  -c frank.c -o frank.o
cc -I"/usr/share/R/include" -DNDEBUG      -fvisibility=hidden  -fopenmp  -fpic  -g -O2 -ffile-prefix-map=/build/r-base-gN72Ro/r-base-4.6.0=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2  -c fread.c -o fread.o
cc -I"/usr/share/R/include" -DNDEBUG      -fvisibility=hidden  -fopenmp  -fpic  -g -O2 -ffile-prefix-map=/build/r-base-gN72Ro/r-base-4.6.0=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2  -c freadR.c -o freadR.o
cc -I"/usr/share/R/include" -DNDEBUG      -fvisibility=hidden  -fopenmp  -fpic  -g -O2 -ffile-prefix-map=/build/r-base-gN72Ro/r-base-4.6.0=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2  -c froll.c -o froll.o
cc -I"/usr/share/R/include" -DNDEBUG      -fvisibility=hidden  -fopenmp  -fpic  -g -O2 -ffile-prefix-map=/build/r-base-gN72Ro/r-base-4.6.0=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2  -c frollR.c -o frollR.o
cc -I"/usr/share/R/include" -DNDEBUG      -fvisibility=hidden  -fopenmp  -fpic  -g -O2 -ffile-prefix-map=/build/r-base-gN72Ro/r-base-4.6.0=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2  -c frolladaptive.c -o frolladaptive.o
cc -I"/usr/share/R/include" -DNDEBUG      -fvisibility=hidden  -fopenmp  -fpic  -g -O2 -ffile-prefix-map=/build/r-base-gN72Ro/r-base-4.6.0=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2  -c frollapply.c -o frollapply.o
cc -I"/usr/share/R/include" -DNDEBUG      -fvisibility=hidden  -fopenmp  -fpic  -g -O2 -ffile-prefix-map=/build/r-base-gN72Ro/r-base-4.6.0=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2  -c fsort.c -o fsort.o
cc -I"/usr/share/R/include" -DNDEBUG      -fvisibility=hidden  -fopenmp  -fpic  -g -O2 -ffile-prefix-map=/build/r-base-gN72Ro/r-base-4.6.0=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2  -c fwrite.c -o fwrite.o
cc -I"/usr/share/R/include" -DNDEBUG      -fvisibility=hidden  -fopenmp  -fpic  -g -O2 -ffile-prefix-map=/build/r-base-gN72Ro/r-base-4.6.0=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2  -c fwriteR.c -o fwriteR.o
cc -I"/usr/share/R/include" -DNDEBUG      -fvisibility=hidden  -fopenmp  -fpic  -g -O2 -ffile-prefix-map=/build/r-base-gN72Ro/r-base-4.6.0=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2  -c gsumm.c -o gsumm.o
cc -I"/usr/share/R/include" -DNDEBUG      -fvisibility=hidden  -fopenmp  -fpic  -g -O2 -ffile-prefix-map=/build/r-base-gN72Ro/r-base-4.6.0=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2  -c hash.c -o hash.o
cc -I"/usr/share/R/include" -DNDEBUG      -fvisibility=hidden  -fopenmp  -fpic  -g -O2 -ffile-prefix-map=/build/r-base-gN72Ro/r-base-4.6.0=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2  -c idatetime.c -o idatetime.o
cc -I"/usr/share/R/include" -DNDEBUG      -fvisibility=hidden  -fopenmp  -fpic  -g -O2 -ffile-prefix-map=/build/r-base-gN72Ro/r-base-4.6.0=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2  -c ijoin.c -o ijoin.o
cc -I"/usr/share/R/include" -DNDEBUG      -fvisibility=hidden  -fopenmp  -fpic  -g -O2 -ffile-prefix-map=/build/r-base-gN72Ro/r-base-4.6.0=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2  -c init.c -o init.o
cc -I"/usr/share/R/include" -DNDEBUG      -fvisibility=hidden  -fopenmp  -fpic  -g -O2 -ffile-prefix-map=/build/r-base-gN72Ro/r-base-4.6.0=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2  -c inrange.c -o inrange.o
cc -I"/usr/share/R/include" -DNDEBUG      -fvisibility=hidden  -fopenmp  -fpic  -g -O2 -ffile-prefix-map=/build/r-base-gN72Ro/r-base-4.6.0=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2  -c mergelist.c -o mergelist.o
cc -I"/usr/share/R/include" -DNDEBUG      -fvisibility=hidden  -fopenmp  -fpic  -g -O2 -ffile-prefix-map=/build/r-base-gN72Ro/r-base-4.6.0=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2  -c nafill.c -o nafill.o
cc -I"/usr/share/R/include" -DNDEBUG      -fvisibility=hidden  -fopenmp  -fpic  -g -O2 -ffile-prefix-map=/build/r-base-gN72Ro/r-base-4.6.0=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2  -c negate.c -o negate.o
cc -I"/usr/share/R/include" -DNDEBUG      -fvisibility=hidden  -fopenmp  -fpic  -g -O2 -ffile-prefix-map=/build/r-base-gN72Ro/r-base-4.6.0=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2  -c nqrecreateindices.c -o nqrecreateindices.o
cc -I"/usr/share/R/include" -DNDEBUG      -fvisibility=hidden  -fopenmp  -fpic  -g -O2 -ffile-prefix-map=/build/r-base-gN72Ro/r-base-4.6.0=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2  -c openmp-utils.c -o openmp-utils.o
cc -I"/usr/share/R/include" -DNDEBUG      -fvisibility=hidden  -fopenmp  -fpic  -g -O2 -ffile-prefix-map=/build/r-base-gN72Ro/r-base-4.6.0=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2  -c programming.c -o programming.o
cc -I"/usr/share/R/include" -DNDEBUG      -fvisibility=hidden  -fopenmp  -fpic  -g -O2 -ffile-prefix-map=/build/r-base-gN72Ro/r-base-4.6.0=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2  -c quickselect.c -o quickselect.o
cc -I"/usr/share/R/include" -DNDEBUG      -fvisibility=hidden  -fopenmp  -fpic  -g -O2 -ffile-prefix-map=/build/r-base-gN72Ro/r-base-4.6.0=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2  -c rbindlist.c -o rbindlist.o
cc -I"/usr/share/R/include" -DNDEBUG      -fvisibility=hidden  -fopenmp  -fpic  -g -O2 -ffile-prefix-map=/build/r-base-gN72Ro/r-base-4.6.0=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2  -c reorder.c -o reorder.o
cc -I"/usr/share/R/include" -DNDEBUG      -fvisibility=hidden  -fopenmp  -fpic  -g -O2 -ffile-prefix-map=/build/r-base-gN72Ro/r-base-4.6.0=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2  -c shellsort.c -o shellsort.o
cc -I"/usr/share/R/include" -DNDEBUG      -fvisibility=hidden  -fopenmp  -fpic  -g -O2 -ffile-prefix-map=/build/r-base-gN72Ro/r-base-4.6.0=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2  -c shift.c -o shift.o
cc -I"/usr/share/R/include" -DNDEBUG      -fvisibility=hidden  -fopenmp  -fpic  -g -O2 -ffile-prefix-map=/build/r-base-gN72Ro/r-base-4.6.0=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2  -c snprintf.c -o snprintf.o
cc -I"/usr/share/R/include" -DNDEBUG      -fvisibility=hidden  -fopenmp  -fpic  -g -O2 -ffile-prefix-map=/build/r-base-gN72Ro/r-base-4.6.0=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2  -c subset.c -o subset.o
cc -I"/usr/share/R/include" -DNDEBUG      -fvisibility=hidden  -fopenmp  -fpic  -g -O2 -ffile-prefix-map=/build/r-base-gN72Ro/r-base-4.6.0=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2  -c transpose.c -o transpose.o
cc -I"/usr/share/R/include" -DNDEBUG      -fvisibility=hidden  -fopenmp  -fpic  -g -O2 -ffile-prefix-map=/build/r-base-gN72Ro/r-base-4.6.0=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2  -c types.c -o types.o
cc -I"/usr/share/R/include" -DNDEBUG      -fvisibility=hidden  -fopenmp  -fpic  -g -O2 -ffile-prefix-map=/build/r-base-gN72Ro/r-base-4.6.0=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2  -c uniqlist.c -o uniqlist.o
cc -I"/usr/share/R/include" -DNDEBUG      -fvisibility=hidden  -fopenmp  -fpic  -g -O2 -ffile-prefix-map=/build/r-base-gN72Ro/r-base-4.6.0=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2  -c utils.c -o utils.o
cc -I"/usr/share/R/include" -DNDEBUG      -fvisibility=hidden  -fopenmp  -fpic  -g -O2 -ffile-prefix-map=/build/r-base-gN72Ro/r-base-4.6.0=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2  -c vecseq.c -o vecseq.o
cc -I"/usr/share/R/include" -DNDEBUG      -fvisibility=hidden  -fopenmp  -fpic  -g -O2 -ffile-prefix-map=/build/r-base-gN72Ro/r-base-4.6.0=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2  -c wrappers.c -o wrappers.o
cc -shared -L/usr/lib/R/lib -Wl,-Bsymbolic-functions -flto=auto -ffat-lto-objects -flto=auto -Wl,-z,relro -o data.table.so assign.o between.o bmerge.o chmatch.o cj.o coalesce.o dogroups.o fastmean.o fcast.o fifelse.o fmelt.o forder.o frank.o fread.o freadR.o froll.o frollR.o frolladaptive.o frollapply.o fsort.o fwrite.o fwriteR.o gsumm.o hash.o idatetime.o ijoin.o init.o inrange.o mergelist.o nafill.o negate.o nqrecreateindices.o openmp-utils.o programming.o quickselect.o rbindlist.o reorder.o shellsort.o shift.o snprintf.o subset.o transpose.o types.o uniqlist.o utils.o vecseq.o wrappers.o -fvisibility=hidden -fopenmp -lz -L/usr/lib/R/lib -lR
PKG_CFLAGS = -fvisibility=hidden -fopenmp
PKG_LIBS = -fvisibility=hidden -fopenmp -lz
if [ "data.table.so" != "data_table.so" ]; then mv data.table.so data_table.so; fi
if [ "" != "Windows_NT" ] && [ `uname -s` = 'Darwin' ]; then install_name_tool -id data_table.so data_table.so; fi
installing to /usr/local/lib/R/site-library/00LOCK-data.table/00new/data.table/libs
** R
** inst
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
** building package indices
** installing vignettes
** testing if installed package can be loaded from temporary location
** checking absolute paths in shared objects and dynamic libraries
** testing if installed package can be loaded from final location
** testing if installed package keeps a record of temporary installation path
* DONE (data.table)

The downloaded source packages are in
	‘/tmp/RtmpmJZTcO/downloaded_packages’
>
Basic R packages installation finished.

In [ ]:
# ============================================================
# Cell 1.8: Install ieugwasr and genetics.binaRies
# ============================================================

!R -q -e "options(repos = c(MRCIEU='https://mrcieu.r-universe.dev', CRAN='https://cloud.r-project.org')); install.packages(c('ieugwasr','genetics.binaRies'))"

print("ieugwasr and genetics.binaRies installation finished.")

> options(repos = c(MRCIEU='https://mrcieu.r-universe.dev', CRAN='https://cloud.r-project.org')); install.packages(c('ieugwasr','genetics.binaRies'))
Installing packages into ‘/usr/local/lib/R/site-library’
(as ‘lib’ is unspecified)
trying URL 'https://mrcieu.r-universe.dev/src/contrib/sha256-52015a4f220a0a66b5bdb2b9e5082578e8c125cc6c5b0dfd829a64ebf8680f6f'
trying URL 'https://mrcieu.r-universe.dev/src/contrib/sha256-4b4d0c252f775f9c60e776a712ce53feb53eb2acf5c77dcabf13e5c0d1ec7e48'
* installing *source* package ‘ieugwasr’ ...
** this is package ‘ieugwasr’ version ‘1.1.0.9000’
** using staged installation
** R
** inst
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
** building package indices
** installing vignettes
** testing if installed package can be loaded from temporary location
** testing if installed package can be loaded from final location
** testing if installed package keeps a record of temporary installation path
* DONE (ieugwasr)
* installing *source* package ‘genetics.binaRies’ ...
** this is package ‘genetics.binaRies’ version ‘0.1.2’
** using staged installation
** R
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
** building package indices
** testing if installed package can be loaded from temporary location
** testing if installed package can be loaded from final location
** testing if installed package keeps a record of temporary installation path
* DONE (genetics.binaRies)

The downloaded source packages are in
	‘/tmp/RtmplHO9ov/downloaded_packages’
>
ieugwasr and genetics.binaRies installation finished.

In [ ]:
# ============================================================
# Cell 1.9.1: Smart install/check TwoSampleMR
# ============================================================

r_code = """
options(repos = c(MRCIEU='https://mrcieu.r-universe.dev', CRAN='https://cloud.r-project.org'))
options(Ncpus = 2)

if (!requireNamespace('TwoSampleMR', quietly = TRUE)) {
  cat('TwoSampleMR is not installed. Installing now...\\n')
  install.packages('TwoSampleMR', dependencies = TRUE)
} else {
  cat('TwoSampleMR is already installed. Skipping installation.\\n')
}

library(TwoSampleMR)
cat('TwoSampleMR loaded successfully.\\n')
cat('Version: ')
print(packageVersion('TwoSampleMR'))
"""

with open("/content/smart_install_twosamplemr.R", "w", encoding="utf-8") as f:
    f.write(r_code)

print("R script written to /content/smart_install_twosamplemr.R")

R script written to /content/smart_install_twosamplemr.R

In [ ]:
# ============================================================
# Cell 1.9.2: Run smart install/check TwoSampleMR
# ============================================================

%%capture twosamplemr_setup_log

!Rscript /content/smart_install_twosamplemr.R

In [ ]:
# ============================================================
# Cell 1.9.3: Show the last part of TwoSampleMR setup log
# ============================================================

log_text = str(twosamplemr_setup_log)

print(log_text[-4000:])

ation
** testing if installed package can be loaded from final location
** testing if installed package keeps a record of temporary installation path
* DONE (pbkrtest)
begin installing package ‘TwoSampleMR’
* installing *source* package ‘TwoSampleMR’ ...
** this is package ‘TwoSampleMR’ version ‘0.7.6’
** using staged installation
** R
** inst
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
** building package indices
** installing vignettes
** testing if installed package can be loaded from temporary location
** testing if installed package can be loaded from final location
** testing if installed package keeps a record of temporary installation path
* DONE (TwoSampleMR)
begin installing package ‘car’
* installing *source* package ‘car’ ...
** this is package ‘car’ version ‘3.1-5’
** package ‘car’ successfully unpacked and MD5 sums checked
** using staged installation
** R
** inst
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
** building package indices
** installing vignettes
** testing if installed package can be loaded from temporary location
** testing if installed package can be loaded from final location
** testing if installed package keeps a record of temporary installation path
* DONE (car)
* installing *source* package ‘meta’ ...
** this is package ‘meta’ version ‘8.5-0’
** package ‘meta’ successfully unpacked and MD5 sums checked
** using staged installation
** R
** data
** inst
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
** building package indices
** installing vignettes
** testing if installed package can be loaded from temporary location
** testing if installed package can be loaded from final location
** testing if installed package keeps a record of temporary installation path
* DONE (meta)
make: Target 'all' not remade because of errors.
* installing *source* package ‘gmp’ ...
** this is package ‘gmp’ version ‘0.7-5.1’
** package ‘gmp’ successfully unpacked and MD5 sums checked
** using staged installation
checking for gcc... cc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether cc accepts -g... yes
checking for cc option to accept ISO C89... none needed
checking how to run the C preprocessor... cc -E
checking whether we are using the GNU C++ compiler... yes
checking whether g++ -std=gnu++20 accepts -g... yes
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking gmp.h usability... no
checking gmp.h presence... no
checking for gmp.h... no
configure: error: Header file gmp.h not found; maybe use --with-gmp-include=INCLUDE_PATH
ERROR: configuration failed for package ‘gmp’
* removing ‘/usr/local/lib/R/site-library/gmp’

The downloaded source packages are in
	‘/tmp/RtmptVcndq/downloaded_packages’
Warning message:
In install.packages("TwoSampleMR", dependencies = TRUE) :
  installation of 4 packages failed:
  ‘gmp’, ‘arrangements’, ‘iterpc’, ‘MendelianRandomization’
TwoSampleMR version 0.7.6

  [>] New authentication requirements: https://mrcieu.github.io/ieugwasr/articles/guide.html#authentication.
  [>] Major upgrades to our servers completed to improve service and stability.
  [>] We need your help to shape our emerging roadmap!
      Please take 2 minutes to give us feedback -
      https://forms.office.com/e/eSr7EFAfCG
TwoSampleMR loaded successfully.
Version: [1] ‘0.7.6’

In [ ]:
# ============================================================
# Cell 1.9.4: Final verification for TwoSampleMR
# ============================================================

!R -q -e "library(TwoSampleMR); cat('TwoSampleMR loaded successfully.\n'); cat('Version: '); print(packageVersion('TwoSampleMR'))"

> library(TwoSampleMR); cat('TwoSampleMR loaded successfully.\n'); cat('Version: '); print(packageVersion('TwoSampleMR'))
TwoSampleMR version 0.7.6

  [>] New authentication requirements: https://mrcieu.github.io/ieugwasr/articles/guide.html#authentication.
  [>] Major upgrades to our servers completed to improve service and stability.
  [>] We need your help to shape our emerging roadmap!
      Please take 2 minutes to give us feedback -
      https://forms.office.com/e/eSr7EFAfCG
TwoSampleMR loaded successfully.
Version: [1] ‘0.7.6’
>

In [ ]:
# ============================================================
# Cell 1.10: Check required R packages
# ============================================================

!R -q -e "library(ggplot2); library(data.table); library(ieugwasr); library(genetics.binaRies); library(TwoSampleMR); cat('All required R packages loaded successfully.\n')"

> library(ggplot2); library(data.table); library(ieugwasr); library(genetics.binaRies); library(TwoSampleMR); cat('All required R packages loaded successfully.\n')

Attaching package: ‘data.table’

The following object is masked from ‘package:base’:

    %notin%

OpenGWAS updates:
  Date: 2024-05-17
  [>] OpenGWAS is growing!
  [>] Please take 2 minutes to give us feedback -
  [>] It will help directly shape our emerging roadmap
  [>] https://forms.office.com/e/eSr7EFAfCG
TwoSampleMR version 0.7.6

  [>] New authentication requirements: https://mrcieu.github.io/ieugwasr/articles/guide.html#authentication.
  [>] Major upgrades to our servers completed to improve service and stability.
  [>] We need your help to shape our emerging roadmap!
      Please take 2 minutes to give us feedback -
      https://forms.office.com/e/eSr7EFAfCG

Attaching package: ‘TwoSampleMR’

The following object is masked from ‘package:ieugwasr’:

    ld_matrix

All required R packages loaded successfully.
>

In [ ]:
# ============================================================
# Cell 1.11: Check rpy2 connection with R
# ============================================================

import rpy2.robjects as robjects
from rpy2.robjects.packages import importr

# Check whether Python can call R
r_version = robjects.r("R.version.string")[0]
print("R version from rpy2:")
print(r_version)

# Import required R packages through rpy2
TwoSampleMR = importr("TwoSampleMR")
ieugwasr = importr("ieugwasr")
ggplot2 = importr("ggplot2")
data_table = importr("data.table")

print("rpy2 can import TwoSampleMR, ieugwasr, ggplot2, and data.table successfully.")

R version from rpy2:
R version 4.6.0 (2026-04-24)
rpy2 can import TwoSampleMR, ieugwasr, ggplot2, and data.table successfully.

In [ ]:
# ============================================================
# Cell 2: Import basic libraries and confirm project path
# ============================================================

import os
import sys
import shutil
from pathlib import Path

PROJECT_ROOT = Path("/content/drive/MyDrive/UM_WQF7023/MRDRP-main")

print("PROJECT_ROOT exists:", PROJECT_ROOT.exists())
print("PROJECT_ROOT:", PROJECT_ROOT)

if PROJECT_ROOT.exists():
    print("\nItems directly under PROJECT_ROOT:")
    for p in sorted(PROJECT_ROOT.iterdir()):
        print("DIR " if p.is_dir() else "FILE", "-", p.name)
else:
    raise FileNotFoundError(
        "PROJECT_ROOT not found. Please mount Google Drive first and check the project path."
    )

PROJECT_ROOT exists: True
PROJECT_ROOT: /content/drive/MyDrive/UM_WQF7023/MRDRP-main

Items directly under PROJECT_ROOT:
FILE - LICENSE
FILE - MR-Icon.png
FILE - MRanalysis.py
FILE - MRanalysis_backup.py
FILE - MRdata.py
FILE - README.md
DIR  - __pycache__
FILE - analysis_set_record.csv
FILE - app.py
FILE - artesunate_file_screening_record.csv
DIR  - backend_work
DIR  - exposures
FILE - file_screening_record.csv
FILE - index.html
DIR  - outcome
DIR  - output_mr
DIR  - output_sig
FILE - pair_selection_record.csv
FILE - pair_selection_record.gsheet
DIR  - test

In [ ]:
# ============================================================
# Cell 3: Define project paths and target traits
# ============================================================

from pathlib import Path
import os

# Main project folder in Google Drive
PROJECT_ROOT = Path("/content/drive/MyDrive/UM_WQF7023/MRDRP-main")

# Input folders
EXPOSURE_ROOT = PROJECT_ROOT / "exposures"
OUTCOME_ROOT = PROJECT_ROOT / "outcome" / "endometrial_cancer"

# Backend working folders
BACKEND_ROOT = PROJECT_ROOT / "backend_work"
PREPARED_EXPOSURE_ROOT = BACKEND_ROOT / "prepared_exposures"
PREPARED_OUTCOME_ROOT = BACKEND_ROOT / "prepared_outcome"
SIG_VARIANT_ROOT = BACKEND_ROOT / "significant_variants"
MR_OUTPUT_ROOT = BACKEND_ROOT / "mr_outputs"

# Output folders for MR analysis
MR_RESULTS_DIR = MR_OUTPUT_ROOT / "results"
MR_DATA_DIR = MR_OUTPUT_ROOT / "harmonized_data"
PLEIOTROPY_DIR = MR_OUTPUT_ROOT / "pleiotropy"
HETEROGENEITY_DIR = MR_OUTPUT_ROOT / "heterogeneity"
SCATTER_PLOT_DIR = MR_OUTPUT_ROOT / "scatter_plots"
SINGLESNP_PLOT_DIR = MR_OUTPUT_ROOT / "singleSNP_plots"
SUMMARY_DIR = MR_OUTPUT_ROOT / "summary"

# Create folders
for folder in [
    EXPOSURE_ROOT,
    OUTCOME_ROOT,
    BACKEND_ROOT,
    PREPARED_EXPOSURE_ROOT,
    PREPARED_OUTCOME_ROOT,
    SIG_VARIANT_ROOT,
    MR_RESULTS_DIR,
    MR_DATA_DIR,
    PLEIOTROPY_DIR,
    HETEROGENEITY_DIR,
    SCATTER_PLOT_DIR,
    SINGLESNP_PLOT_DIR,
    SUMMARY_DIR,
]:
    folder.mkdir(parents=True, exist_ok=True)

# Current target exposures and outcome
TARGET_EXPOSURES = ["IGF1", "SHBG", "ADIPOQ", "GDF15"]
TARGET_OUTCOME = "endometrial_cancer"

print("Project root:", PROJECT_ROOT)
print("Exposure root:", EXPOSURE_ROOT)
print("Outcome root:", OUTCOME_ROOT)
print("Backend root:", BACKEND_ROOT)
print("Target exposures:", TARGET_EXPOSURES)
print("Target outcome:", TARGET_OUTCOME)

Project root: /content/drive/MyDrive/UM_WQF7023/MRDRP-main
Exposure root: /content/drive/MyDrive/UM_WQF7023/MRDRP-main/exposures
Outcome root: /content/drive/MyDrive/UM_WQF7023/MRDRP-main/outcome/endometrial_cancer
Backend root: /content/drive/MyDrive/UM_WQF7023/MRDRP-main/backend_work
Target exposures: ['IGF1', 'SHBG', 'ADIPOQ', 'GDF15']
Target outcome: endometrial_cancer

In [ ]:
# ============================================================
# Cell 4: List detected exposure and outcome files (CAN SKIP)
# ============================================================

SUPPORTED_EXTENSIONS = [".csv", ".csv.gz", ".tsv", ".tsv.gz", ".txt", ".txt.gz"]

def is_supported_gwas_file(path: Path) -> bool:
    name = path.name.lower()
    return any(name.endswith(ext) for ext in SUPPORTED_EXTENSIONS)

def list_trait_files(root: Path):
    files = []
    if not root.exists():
        return files
    for path in root.rglob("*"):
        if path.is_file() and is_supported_gwas_file(path):
            files.append(path)
    return sorted(files)

print("Detected exposure files:")
for trait in TARGET_EXPOSURES:
    trait_dir = EXPOSURE_ROOT / trait
    files = list_trait_files(trait_dir)
    print(f"\n[{trait}] {len(files)} file(s)")
    for f in files:
        print(" -", f)

print("\nDetected outcome files:")
outcome_files = list_trait_files(OUTCOME_ROOT)
print(f"[{TARGET_OUTCOME}] {len(outcome_files)} file(s)")
for f in outcome_files:
    print(" -", f)

Detected exposure files:

[IGF1] 14 file(s)
 - /content/drive/MyDrive/UM_WQF7023/MRDRP-main/exposures/IGF1/GCST90014008_buildGRCh38.tsv.gz
 - /content/drive/MyDrive/UM_WQF7023/MRDRP-main/exposures/IGF1/GCST90019511_buildGRCh37.tsv
 - /content/drive/MyDrive/UM_WQF7023/MRDRP-main/exposures/IGF1/GCST90025989_buildGRCh37.tsv
 - /content/drive/MyDrive/UM_WQF7023/MRDRP-main/exposures/IGF1/GCST90079032_buildGRCh38.tsv.gz
 - /content/drive/MyDrive/UM_WQF7023/MRDRP-main/exposures/IGF1/GCST90083018_buildGRCh38.tsv.gz
 - /content/drive/MyDrive/UM_WQF7023/MRDRP-main/exposures/IGF1/GCST90161219_buildGRCh37.tsv
 - /content/drive/MyDrive/UM_WQF7023/MRDRP-main/exposures/IGF1/GCST90297291.tsv.gz
 - /content/drive/MyDrive/UM_WQF7023/MRDRP-main/exposures/IGF1/GCST90297335.tsv.gz
 - /content/drive/MyDrive/UM_WQF7023/MRDRP-main/exposures/IGF1/GCST90297511.tsv.gz
 - /content/drive/MyDrive/UM_WQF7023/MRDRP-main/exposures/IGF1/GCST90310168.tsv.gz
 - /content/drive/MyDrive/UM_WQF7023/MRDRP-main/exposures/IGF1/GCST90319615.tsv.gz
 - /content/drive/MyDrive/UM_WQF7023/MRDRP-main/exposures/IGF1/GCST90319643.tsv.gz
 - /content/drive/MyDrive/UM_WQF7023/MRDRP-main/exposures/IGF1/GCST90335170.tsv.gz
 - /content/drive/MyDrive/UM_WQF7023/MRDRP-main/exposures/IGF1/GCST90335171.tsv.gz

[SHBG] 7 file(s)
 - /content/drive/MyDrive/UM_WQF7023/MRDRP-main/exposures/SHBG/GCST90012106_buildGRCh37.tsv.gz
 - /content/drive/MyDrive/UM_WQF7023/MRDRP-main/exposures/SHBG/GCST90012107_buildGRCh37.tsv.gz
 - /content/drive/MyDrive/UM_WQF7023/MRDRP-main/exposures/SHBG/GCST90012108_buildGRCh37.tsv.gz
 - /content/drive/MyDrive/UM_WQF7023/MRDRP-main/exposures/SHBG/GCST90019518_buildGRCh37.tsv
 - /content/drive/MyDrive/UM_WQF7023/MRDRP-main/exposures/SHBG/GCST90079040_buildGRCh38.tsv.gz
 - /content/drive/MyDrive/UM_WQF7023/MRDRP-main/exposures/SHBG/GCST90083026_buildGRCh38.tsv.gz
 - /content/drive/MyDrive/UM_WQF7023/MRDRP-main/exposures/SHBG/GCST90297308.tsv.gz

[ADIPOQ] 3 file(s)
 - /content/drive/MyDrive/UM_WQF7023/MRDRP-main/exposures/ADIPOQ/GCST90100621_buildGRCh37.tsv.gz
 - /content/drive/MyDrive/UM_WQF7023/MRDRP-main/exposures/ADIPOQ/GCST90161837_buildGRCh37.tsv.gz
 - /content/drive/MyDrive/UM_WQF7023/MRDRP-main/exposures/ADIPOQ/GCST90237429_buildGRCh38.tsv.gz

[GDF15] 2 file(s)
 - /content/drive/MyDrive/UM_WQF7023/MRDRP-main/exposures/GDF15/GCST90162057_buildGRCh37.tsv.gz
 - /content/drive/MyDrive/UM_WQF7023/MRDRP-main/exposures/GDF15/GCST90179306_buildGRCh38.tsv.gz

Detected outcome files:
[endometrial_cancer] 6 file(s)
 - /content/drive/MyDrive/UM_WQF7023/MRDRP-main/outcome/endometrial_cancer/GCST90077633_buildGRCh38.tsv.gz
 - /content/drive/MyDrive/UM_WQF7023/MRDRP-main/outcome/endometrial_cancer/GCST90079109_buildGRCh38.tsv.gz
 - /content/drive/MyDrive/UM_WQF7023/MRDRP-main/outcome/endometrial_cancer/GCST90079607_buildGRCh38.tsv.gz
 - /content/drive/MyDrive/UM_WQF7023/MRDRP-main/outcome/endometrial_cancer/GCST90081619_buildGRCh38.tsv.gz
 - /content/drive/MyDrive/UM_WQF7023/MRDRP-main/outcome/endometrial_cancer/GCST90083095_buildGRCh38.tsv.gz
 - /content/drive/MyDrive/UM_WQF7023/MRDRP-main/outcome/endometrial_cancer/GCST90083593_buildGRCh38.tsv.gz

In [ ]:
# ============================================================
# Cell 5: GWAS reader and automatic column detection
# ============================================================

import pandas as pd
import numpy as np
import gzip
import re
from pathlib import Path

def infer_separator(file_path: Path):
    name = file_path.name.lower()
    if name.endswith(".csv") or name.endswith(".csv.gz"):
        return ","
    return "\t"

def read_gwas_file(file_path: Path, nrows=None):
    sep = infer_separator(file_path)
    return pd.read_csv(
        file_path,
        sep=sep,
        compression="infer",
        nrows=nrows,
        low_memory=False
    )

COLUMN_CANDIDATES = {
    "SNP": [
        "SNP", "rsid", "rsID", "RSID", "variant_id", "variant", "MarkerName",
        "marker", "ID", "hm_rsid"
    ],
    "CHR": [
        "CHR", "CHROM", "chromosome", "chrom", "hm_chrom", "seqnames"
    ],
    "POS": [
        "POS", "BP", "base_pair_location", "position", "hm_pos", "pos",
        "variant_pos", "base_pair_position"
    ],
    "EA": [
        "EA", "effect_allele", "effectAllele", "A1", "ALT", "alt",
        "tested_allele", "hm_effect_allele"
    ],
    "OA": [
        "OA", "other_allele", "otherAllele", "A2", "REF", "ref",
        "non_effect_allele", "hm_other_allele"
    ],
    "BETA": [
        "BETA", "beta", "effect_size", "Effect", "effect", "estimate",
        "log_odds", "logOR"
    ],
    "OR": [
        "odds_ratio", "OR", "or", "oddsratio", "OddsRatio"
    ],
    "SE": [
        "SE", "se", "standard_error", "standard_error_beta",
        "stderr", "StdErr", "sebeta"
    ],
    "EAF": [
        "EAF", "eaf", "effect_allele_frequency", "A1FREQ",
        "AF", "af", "freq", "hm_effect_allele_frequency"
    ],
    "P": [
        "P", "p", "pval", "p_value", "p-value", "PVAL",
        "pvalue", "P_VALUE", "PVALUE"
    ],
    "N": [
        "N", "n", "samplesize", "sample_size", "n_samples",
        "N_total", "total_sample_size"
    ],
}

def find_column(columns, candidates):
    lower_map = {str(c).lower(): c for c in columns}
    for cand in candidates:
        if cand.lower() in lower_map:
            return lower_map[cand.lower()]
    return None

def detect_columns(df: pd.DataFrame):
    detected = {}
    for standard_name, candidates in COLUMN_CANDIDATES.items():
        detected[standard_name] = find_column(df.columns, candidates)
    return detected

def clean_chr_value(x):
    if pd.isna(x):
        return np.nan
    x = str(x).replace("chr", "").replace("CHR", "").strip()
    if x in ["X", "x"]:
        return 23
    if x in ["Y", "y"]:
        return 24
    try:
        return int(float(x))
    except:
        return np.nan

def infer_build_from_filename(file_path: Path):
    name = file_path.name.lower()
    if "grch38" in name or "hg38" in name or "build38" in name:
        return "GRCh38"
    if "grch37" in name or "hg19" in name or "build37" in name:
        return "GRCh37"
    return "Unknown"

print("GWAS helper functions are ready.")

GWAS helper functions are ready.

In [ ]:
# ============================================================
# Cell 6.0: Inspect exact columns of selected GWAS files (SKIP)
# ============================================================

def inspect_gwas_columns(file_path, nrows=5):
    file_path = Path(file_path)
    df_preview = read_gwas_file(file_path, nrows=nrows)

    print("=" * 100)
    print("File:", file_path)
    print("Shape preview:", df_preview.shape)
    print("\nColumns:")
    for i, col in enumerate(df_preview.columns):
        print(f"{i+1:03d}. {col}")

    print("\nPreview:")
    display(df_preview.head())

# Inspect IGF1 file that caused the error
inspect_gwas_columns("/content/drive/MyDrive/UM_WQF7023/MRDRP-main/exposures/IGF1/GCST90014008_buildGRCh38.tsv.gz")

FileNotFoundError: [Errno 2] No such file or directory: '/content/drive/MyDrive/UM_WQF7023/MRDRP-main/exposures/IGF1/GCST90014008_buildGRCh38.tsv.gz'

In [ ]:
# ============================================================
# Cell 6: Standardise GWAS files into MR-ready columns, v2
# Supports fallback pseudo SNP ID when rsID is missing
# ============================================================

ALLOW_PSEUDO_SNP_IF_RSID_MISSING = True

def standardise_gwas_file(
    input_path: Path,
    output_path: Path,
    trait: str,
    role: str,
    force_binary_outcome_or_to_beta: bool = False,
    allow_pseudo_snp: bool = ALLOW_PSEUDO_SNP_IF_RSID_MISSING
):
    """
    Standardise GWAS summary statistics into columns:
    SNP, CHR, POS, EA, OA, BETA, SE, EAF, P, N, trait, role, source_file, build.

    If rsID/SNP is missing but CHR/POS/EA/OA exist, this version can create a pseudo SNP ID:
    CHR:POS:EA:OA

    Important:
    - Real rsID is preferred for formal MR and remote LD clumping.
    - Pseudo SNP ID is mainly useful for backend testing or when outcome uses the same coordinate-based variant ID.
    """

    print(f"\nProcessing {role}: {trait}")
    print("Input:", input_path)

    df = read_gwas_file(input_path)
    detected = detect_columns(df)

    print("Detected columns:")
    for k, v in detected.items():
        print(f"  {k}: {v}")

    # BETA can be directly available, or derived from OR
    has_beta = detected.get("BETA") is not None
    has_or = detected.get("OR") is not None

    if not has_beta and not has_or:
        raise ValueError(
            f"No BETA or odds_ratio column found for {input_path.name}. "
            "MR requires an effect size."
        )

    # Required fields excluding SNP first.
    # SNP has fallback logic below.
    required_basic = ["EA", "OA", "SE", "P"]
    missing_basic = [k for k in required_basic if detected.get(k) is None]

    if missing_basic:
        raise ValueError(f"Missing required columns for {input_path.name}: {missing_basic}")

    out = pd.DataFrame()

    # CHR and POS
    if detected.get("CHR") is not None:
        out["CHR"] = df[detected["CHR"]].apply(clean_chr_value)
    else:
        out["CHR"] = np.nan

    if detected.get("POS") is not None:
        out["POS"] = pd.to_numeric(df[detected["POS"]], errors="coerce")
    else:
        out["POS"] = np.nan

    # Alleles
    out["EA"] = df[detected["EA"]].astype(str).str.upper().str.strip()
    out["OA"] = df[detected["OA"]].astype(str).str.upper().str.strip()

    # SNP / rsID handling
    if detected.get("SNP") is not None:
        out["SNP"] = df[detected["SNP"]].astype(str).str.strip()
        snp_source_type = "detected_snp_column"

    else:
        if allow_pseudo_snp and detected.get("CHR") is not None and detected.get("POS") is not None:
            print(
                "WARNING: No rsID/SNP column detected. "
                "Creating pseudo SNP ID using CHR:POS:EA:OA."
            )

            out["SNP"] = (
                out["CHR"].astype("Int64").astype(str)
                + ":"
                + out["POS"].astype("Int64").astype(str)
                + ":"
                + out["EA"].astype(str)
                + ":"
                + out["OA"].astype(str)
            )

            snp_source_type = "pseudo_chr_pos_allele_id"

        else:
            raise ValueError(
                f"Missing SNP/rsID column for {input_path.name}, and pseudo SNP fallback is not possible."
            )

    # Effect size handling
    if has_beta:
        out["BETA"] = pd.to_numeric(df[detected["BETA"]], errors="coerce")
        effect_size_type = "beta"
    else:
        out["BETA"] = np.log(pd.to_numeric(df[detected["OR"]], errors="coerce"))
        effect_size_type = "odds_ratio_converted_to_beta"

    # For binary outcome, force OR-to-beta if odds_ratio exists
    if force_binary_outcome_or_to_beta and has_or:
        out["BETA"] = np.log(pd.to_numeric(df[detected["OR"]], errors="coerce"))
        effect_size_type = "odds_ratio_converted_to_beta"

    out["SE"] = pd.to_numeric(df[detected["SE"]], errors="coerce")

    if detected.get("EAF") is not None:
        out["EAF"] = pd.to_numeric(df[detected["EAF"]], errors="coerce")
    else:
        out["EAF"] = np.nan

    out["P"] = pd.to_numeric(df[detected["P"]], errors="coerce")

    if detected.get("N") is not None:
        out["N"] = pd.to_numeric(df[detected["N"]], errors="coerce")
    else:
        out["N"] = np.nan

    out["trait"] = trait
    out["role"] = role
    out["source_file"] = str(input_path)
    out["build"] = infer_build_from_filename(input_path)
    out["effect_size_type"] = effect_size_type
    out["snp_source_type"] = snp_source_type

    # Basic cleaning
    out = out.replace([np.inf, -np.inf], np.nan)
    out = out.dropna(subset=["SNP", "EA", "OA", "BETA", "SE", "P"])

    # Remove invalid alleles
    valid_alleles = {"A", "C", "G", "T"}
    out = out[out["EA"].isin(valid_alleles) & out["OA"].isin(valid_alleles)]
    out = out[out["EA"] != out["OA"]]

    # Remove impossible p-values
    out = out[(out["P"] > 0) & (out["P"] <= 1)]

    # Remove rows with invalid pseudo CHR/POS if pseudo SNP is used
    if snp_source_type == "pseudo_chr_pos_allele_id":
        out = out.dropna(subset=["CHR", "POS"])

    output_path.parent.mkdir(parents=True, exist_ok=True)
    out.to_csv(output_path, index=False)

    print("Output:", output_path)
    print("Rows saved:", len(out))
    print("Effect size type:", effect_size_type)
    print("SNP source type:", snp_source_type)
    print("Build inferred:", infer_build_from_filename(input_path))

    if snp_source_type == "pseudo_chr_pos_allele_id":
        print(
            "NOTE: This file does not have real rsID. "
            "The pseudo SNP ID can help preprocessing continue, "
            "but formal LD clumping/MR may require rsID-based files."
        )

    return {
        "trait": trait,
        "role": role,
        "input_file": str(input_path),
        "output_file": str(output_path),
        "rows_saved": len(out),
        "effect_size_type": effect_size_type,
        "build": infer_build_from_filename(input_path),
        "snp_source_type": snp_source_type,
        "detected_columns": detected,
    }

print("Standardisation function v2 is ready.")

Standardisation function v2 is ready.

In [ ]:
# ============================================================
# Cell 6.5: Locate screening and analysis set records
# ============================================================

from pathlib import Path
import pandas as pd
import os

PROJECT_ROOT = Path("/content/drive/MyDrive/UM_WQF7023/MRDRP-main")

record_candidates = {
    "file_screening_record": PROJECT_ROOT / "artesunate_file_screening_record.csv",
    "analysis_set_record": PROJECT_ROOT / "analysis_set_record.csv",
}

for name, path in record_candidates.items():
    print("=" * 80)
    print(name)
    print("Path:", path)
    print("Exists:", path.exists())

    if path.exists():
        df = pd.read_csv(path)
        print("Shape:", df.shape)
        print("Columns:")
        print(list(df.columns))
        display(df.head())

================================================================================
file_screening_record
Path: /content/drive/MyDrive/UM_WQF7023/MRDRP-main/artesunate_file_screening_record.csv
Exists: True
Shape: (31, 22)
Columns:
['file_name', 'file_path', 'trait', 'study_accession', 'role', 'build', 'variant_identifier', 'chromosome', 'position', 'effect_allele', 'other_allele', 'beta', 'standard_error', 'effect_allele_frequency', 'p_value', 'sample_size', 'full_summary_stats_candidate', 'status', 'notes', 'odds_ratio', 'effect_size_column', 'effect_size_type']

,file_name,file_path,trait,study_accession,role,build,variant_identifier,chromosome,position,effect_allele,...,standard_error,effect_allele_frequency,p_value,sample_size,full_summary_stats_candidate,status,notes,odds_ratio,effect_size_column,effect_size_type
0,GCST90100621_buildGRCh37.tsv.gz,/content/drive/MyDrive/UM_WQF7023/MRDRP-main/e...,ADIPOQ,GCST90100621_buildGRCh37,exposure,GRCh37,NaN,chromosome,base_pair_location,effect_allele,...,NaN,effect_allele_frequency,p_value,NaN,No,Not suitable for current pipeline,Missing core fields: standard_error,NaN,beta,beta
1,GCST90161837_buildGRCh37.tsv.gz,/content/drive/MyDrive/UM_WQF7023/MRDRP-main/e...,ADIPOQ,GCST90161837_buildGRCh37,exposure,GRCh37,variant_id,chromosome,base_pair_location,effect_allele,...,standard_error,effect_allele_frequency,p_value,NaN,Yes,Suitable candidate,Core MR fields found; variant identifier present.,NaN,beta,beta
2,GCST90237429_buildGRCh38.tsv.gz,/content/drive/MyDrive/UM_WQF7023/MRDRP-main/e...,ADIPOQ,GCST90237429_buildGRCh38,exposure,GRCh38,variant_id,chromosome,base_pair_location,effect_allele,...,standard_error,effect_allele_frequency,p_value,NaN,Yes,Suitable candidate,Core MR fields found; variant identifier present.,NaN,beta,beta
3,GCST90162057_buildGRCh37.tsv.gz,/content/drive/MyDrive/UM_WQF7023/MRDRP-main/e...,GDF15,GCST90162057_buildGRCh37,exposure,GRCh37,variant_id,chromosome,base_pair_location,effect_allele,...,standard_error,effect_allele_frequency,p_value,NaN,Yes,Suitable candidate,Core MR fields found; variant identifier present.,NaN,beta,beta
4,GCST90179306_buildGRCh38.tsv.gz,/content/drive/MyDrive/UM_WQF7023/MRDRP-main/e...,GDF15,GCST90179306_buildGRCh38,exposure,GRCh38,NaN,chromosome,base_pair_location,effect_allele,...,standard_error,effect_allele_frequency,p_value,NaN,Yes,Needs adaptation,"Core MR fields found, but no obvious rsID/SNP-...",NaN,beta,beta

================================================================================
analysis_set_record
Path: /content/drive/MyDrive/UM_WQF7023/MRDRP-main/analysis_set_record.csv
Exists: True
Shape: (5, 11)
Columns:
['analysis_set_name', 'exposure_files', 'exposure_traits', 'outcome_file', 'outcome_trait', 'build_route', 'build_match', 'set_status', 'notes', 'required_exposures', 'missing_exposure_traits']

,analysis_set_name,exposure_files,exposure_traits,outcome_file,outcome_trait,build_route,build_match,set_status,notes,required_exposures,missing_exposure_traits
0,Artesunate_EndometrialCancer_GRCh38_Set01,GCST90237429_buildGRCh38.tsv.gz; GCST90179306_...,ADIPOQ; GDF15; IGF1; SHBG,GCST90077633_buildGRCh38.tsv.gz,endometrial_cancer,GRCh38,Yes,Ready after adaptation,All required exposure traits are selected and ...,IGF1; SHBG; ADIPOQ; GDF15,NaN
1,Artesunate_EndometrialCancer_GRCh38_Set02,GCST90237429_buildGRCh38.tsv.gz; GCST90179306_...,ADIPOQ; GDF15; IGF1; SHBG,GCST90079109_buildGRCh38.tsv.gz,endometrial_cancer,GRCh38,Yes,Ready after adaptation,All required exposure traits are selected and ...,IGF1; SHBG; ADIPOQ; GDF15,NaN
2,Artesunate_EndometrialCancer_GRCh38_Set03,GCST90237429_buildGRCh38.tsv.gz; GCST90179306_...,ADIPOQ; GDF15; IGF1; SHBG,GCST90079607_buildGRCh38.tsv.gz,endometrial_cancer,GRCh38,Yes,Ready after adaptation,All required exposure traits are selected and ...,IGF1; SHBG; ADIPOQ; GDF15,NaN
3,Artesunate_EndometrialCancer_GRCh38_Set04,GCST90237429_buildGRCh38.tsv.gz; GCST90179306_...,ADIPOQ; GDF15; IGF1; SHBG,GCST90083095_buildGRCh38.tsv.gz,endometrial_cancer,GRCh38,Yes,Ready after adaptation,All required exposure traits are selected and ...,IGF1; SHBG; ADIPOQ; GDF15,NaN
4,Artesunate_EndometrialCancer_GRCh38_Set05,GCST90237429_buildGRCh38.tsv.gz; GCST90179306_...,ADIPOQ; GDF15; IGF1; SHBG,GCST90083593_buildGRCh38.tsv.gz,endometrial_cancer,GRCh38,Yes,Ready after adaptation,All required exposure traits are selected and ...,IGF1; SHBG; ADIPOQ; GDF15,NaN

In [ ]:
# ============================================================
# Cell 6.6: Show candidate files from screening record
# ============================================================

screening_record_path = PROJECT_ROOT / "artesunate_file_screening_record.csv"

if not screening_record_path.exists():
    raise FileNotFoundError("artesunate_file_screening_record.csv not found.")

screening_df = pd.read_csv(screening_record_path)

print("Screening record columns:")
print(list(screening_df.columns))

# Try to identify useful columns automatically
possible_trait_cols = ["trait", "Trait", "confirmed_trait", "target_trait"]
possible_role_cols = ["role", "Role", "confirmed_role"]
possible_build_cols = ["build", "Build", "genome_build", "confirmed_build"]
possible_status_cols = ["status", "Status", "file_status", "suitability_status"]
possible_path_cols = ["path", "file_path", "File Path", "full_path", "absolute_path"]
possible_name_cols = ["file_name", "filename", "name", "File Name"]

def pick_col(df, candidates):
    for c in candidates:
        if c in df.columns:
            return c
    return None

trait_col = pick_col(screening_df, possible_trait_cols)
role_col = pick_col(screening_df, possible_role_cols)
build_col = pick_col(screening_df, possible_build_cols)
status_col = pick_col(screening_df, possible_status_cols)
path_col = pick_col(screening_df, possible_path_cols)
name_col = pick_col(screening_df, possible_name_cols)

print("\nDetected record columns:")
print("trait_col:", trait_col)
print("role_col:", role_col)
print("build_col:", build_col)
print("status_col:", status_col)
print("path_col:", path_col)
print("name_col:", name_col)

target_keywords = ["IGF", "SHBG", "ADIPO", "GDF", "endometrial", "cancer"]

candidate_df = screening_df.copy()

if trait_col is not None:
    mask = candidate_df[trait_col].astype(str).str.contains(
        "|".join(target_keywords),
        case=False,
        na=False
    )
    candidate_df = candidate_df[mask]

display_cols = [c for c in [trait_col, role_col, build_col, status_col, path_col, name_col] if c is not None]

print("\nCandidate records:")
display(candidate_df[display_cols].head(100))

Screening record columns:
['file_name', 'file_path', 'trait', 'study_accession', 'role', 'build', 'variant_identifier', 'chromosome', 'position', 'effect_allele', 'other_allele', 'beta', 'standard_error', 'effect_allele_frequency', 'p_value', 'sample_size', 'full_summary_stats_candidate', 'status', 'notes', 'odds_ratio', 'effect_size_column', 'effect_size_type']

Detected record columns:
trait_col: trait
role_col: role
build_col: build
status_col: status
path_col: file_path
name_col: file_name

Candidate records:

,trait,role,build,status,file_path,file_name
0,ADIPOQ,exposure,GRCh37,Not suitable for current pipeline,/content/drive/MyDrive/UM_WQF7023/MRDRP-main/e...,GCST90100621_buildGRCh37.tsv.gz
1,ADIPOQ,exposure,GRCh37,Suitable candidate,/content/drive/MyDrive/UM_WQF7023/MRDRP-main/e...,GCST90161837_buildGRCh37.tsv.gz
2,ADIPOQ,exposure,GRCh38,Suitable candidate,/content/drive/MyDrive/UM_WQF7023/MRDRP-main/e...,GCST90237429_buildGRCh38.tsv.gz
3,GDF15,exposure,GRCh37,Suitable candidate,/content/drive/MyDrive/UM_WQF7023/MRDRP-main/e...,GCST90162057_buildGRCh37.tsv.gz
4,GDF15,exposure,GRCh38,Needs adaptation,/content/drive/MyDrive/UM_WQF7023/MRDRP-main/e...,GCST90179306_buildGRCh38.tsv.gz
5,IGF1,exposure,GRCh38,Not suitable for current pipeline,/content/drive/MyDrive/UM_WQF7023/MRDRP-main/e...,GCST90014008_buildGRCh38.tsv.gz
6,IGF1,exposure,GRCh37,Not suitable for current pipeline,/content/drive/MyDrive/UM_WQF7023/MRDRP-main/e...,GCST90019511_buildGRCh37.tsv
7,IGF1,exposure,GRCh37,Not suitable for current pipeline,/content/drive/MyDrive/UM_WQF7023/MRDRP-main/e...,GCST90025989_buildGRCh37.tsv
8,IGF1,exposure,GRCh38,Needs adaptation,/content/drive/MyDrive/UM_WQF7023/MRDRP-main/e...,GCST90079032_buildGRCh38.tsv.gz
9,IGF1,exposure,GRCh38,Needs adaptation,/content/drive/MyDrive/UM_WQF7023/MRDRP-main/e...,GCST90083018_buildGRCh38.tsv.gz
10,IGF1,exposure,GRCh37,Not suitable for current pipeline,/content/drive/MyDrive/UM_WQF7023/MRDRP-main/e...,GCST90161219_buildGRCh37.tsv
11,IGF1,exposure,Unknown,Not suitable for current pipeline,/content/drive/MyDrive/UM_WQF7023/MRDRP-main/e...,GCST90297291.tsv.gz
12,IGF1,exposure,Unknown,Not suitable for current pipeline,/content/drive/MyDrive/UM_WQF7023/MRDRP-main/e...,GCST90297335.tsv.gz
13,IGF1,exposure,Unknown,Not suitable for current pipeline,/content/drive/MyDrive/UM_WQF7023/MRDRP-main/e...,GCST90297511.tsv.gz
14,IGF1,exposure,Unknown,Suitable candidate,/content/drive/MyDrive/UM_WQF7023/MRDRP-main/e...,GCST90310168.tsv.gz
15,IGF1,exposure,Unknown,Needs adaptation,/content/drive/MyDrive/UM_WQF7023/MRDRP-main/e...,GCST90319615.tsv.gz
16,IGF1,exposure,Unknown,Needs adaptation,/content/drive/MyDrive/UM_WQF7023/MRDRP-main/e...,GCST90319643.tsv.gz
17,IGF1,exposure,Unknown,Needs adaptation,/content/drive/MyDrive/UM_WQF7023/MRDRP-main/e...,GCST90335170.tsv.gz
18,IGF1,exposure,Unknown,Needs adaptation,/content/drive/MyDrive/UM_WQF7023/MRDRP-main/e...,GCST90335171.tsv.gz
19,SHBG,exposure,GRCh37,Suitable candidate,/content/drive/MyDrive/UM_WQF7023/MRDRP-main/e...,GCST90012106_buildGRCh37.tsv.gz
20,SHBG,exposure,GRCh37,Suitable candidate,/content/drive/MyDrive/UM_WQF7023/MRDRP-main/e...,GCST90012107_buildGRCh37.tsv.gz
21,SHBG,exposure,GRCh37,Suitable candidate,/content/drive/MyDrive/UM_WQF7023/MRDRP-main/e...,GCST90012108_buildGRCh37.tsv.gz
22,SHBG,exposure,GRCh37,Not suitable for current pipeline,/content/drive/MyDrive/UM_WQF7023/MRDRP-main/e...,GCST90019518_buildGRCh37.tsv
23,SHBG,exposure,GRCh38,Needs adaptation,/content/drive/MyDrive/UM_WQF7023/MRDRP-main/e...,GCST90079040_buildGRCh38.tsv.gz
24,SHBG,exposure,GRCh38,Needs adaptation,/content/drive/MyDrive/UM_WQF7023/MRDRP-main/e...,GCST90083026_buildGRCh38.tsv.gz
25,SHBG,exposure,Unknown,Not suitable for current pipeline,/content/drive/MyDrive/UM_WQF7023/MRDRP-main/e...,GCST90297308.tsv.gz
26,endometrial_cancer,outcome,GRCh38,Needs adaptation,/content/drive/MyDrive/UM_WQF7023/MRDRP-main/o...,GCST90077633_buildGRCh38.tsv.gz
27,endometrial_cancer,outcome,GRCh38,Needs adaptation,/content/drive/MyDrive/UM_WQF7023/MRDRP-main/o...,GCST90079109_buildGRCh38.tsv.gz
28,endometrial_cancer,outcome,GRCh38,Needs adaptation,/content/drive/MyDrive/UM_WQF7023/MRDRP-main/o...,GCST90079607_buildGRCh38.tsv.gz
29,endometrial_cancer,outcome,GRCh38,Needs adaptation,/content/drive/MyDrive/UM_WQF7023/MRDRP-main/o...,GCST90083095_buildGRCh38.tsv.gz
30,endometrial_cancer,outcome,GRCh38,Needs adaptation,/content/drive/MyDrive/UM_WQF7023/MRDRP-main/o...,GCST90083593_buildGRCh38.tsv.gz

In [ ]:
# ============================================================
# Cell 6.7: Standardise screening record columns
# ============================================================

import pandas as pd
import numpy as np
from pathlib import Path

screening_record_path = PROJECT_ROOT / "artesunate_file_screening_record.csv"

if not screening_record_path.exists():
    raise FileNotFoundError(f"Screening record not found: {screening_record_path}")

screening_df_raw = pd.read_csv(screening_record_path)

print("Raw screening record shape:", screening_df_raw.shape)
print("Raw columns:")
print(list(screening_df_raw.columns))


def pick_col(df, candidates):
    """
    Pick the first existing column from candidate names.
    """
    lower_map = {str(c).lower(): c for c in df.columns}
    for cand in candidates:
        if cand.lower() in lower_map:
            return lower_map[cand.lower()]
    return None


# Possible column names from different dashboard versions
trait_col = pick_col(screening_df_raw, [
    "trait", "Trait", "confirmed_trait", "target_trait", "detected_trait"
])

role_col = pick_col(screening_df_raw, [
    "role", "Role", "confirmed_role", "file_role"
])

build_col = pick_col(screening_df_raw, [
    "build", "Build", "genome_build", "confirmed_build", "detected_build"
])

status_col = pick_col(screening_df_raw, [
    "status", "Status", "file_status", "suitability_status", "screening_status"
])

path_col = pick_col(screening_df_raw, [
    "path", "file_path", "File Path", "full_path", "absolute_path", "selected_path"
])

name_col = pick_col(screening_df_raw, [
    "file_name", "filename", "name", "File Name"
])

effect_size_type_col = pick_col(screening_df_raw, [
    "effect_size_type", "Effect Size Type", "effect_type", "detected_effect_size_type"
])

notes_col = pick_col(screening_df_raw, [
    "notes", "Notes", "manual_notes", "comment", "remarks"
])

print("\nDetected important columns:")
print("trait_col:", trait_col)
print("role_col:", role_col)
print("build_col:", build_col)
print("status_col:", status_col)
print("path_col:", path_col)
print("name_col:", name_col)
print("effect_size_type_col:", effect_size_type_col)
print("notes_col:", notes_col)

required_record_cols = {
    "trait_col": trait_col,
    "role_col": role_col,
    "build_col": build_col,
    "status_col": status_col,
    "path_col": path_col,
}

missing_record_cols = [k for k, v in required_record_cols.items() if v is None]

if missing_record_cols:
    raise ValueError(
        "Some important columns could not be detected from the screening record: "
        + str(missing_record_cols)
        + "\nPlease check the actual column names printed above."
    )

# Create a clean internal version
screening_df = screening_df_raw.copy()

screening_df["_trait"] = screening_df[trait_col].astype(str).str.strip()
screening_df["_role"] = screening_df[role_col].astype(str).str.strip().str.lower()
screening_df["_build"] = screening_df[build_col].astype(str).str.strip()
screening_df["_status"] = screening_df[status_col].astype(str).str.strip()
screening_df["_path"] = screening_df[path_col].astype(str).str.strip()

if name_col is not None:
    screening_df["_file_name"] = screening_df[name_col].astype(str).str.strip()
else:
    screening_df["_file_name"] = screening_df["_path"].apply(lambda x: Path(x).name)

if effect_size_type_col is not None:
    screening_df["_effect_size_type"] = screening_df[effect_size_type_col].astype(str).str.strip()
else:
    screening_df["_effect_size_type"] = "Unknown"

if notes_col is not None:
    screening_df["_notes"] = screening_df[notes_col].astype(str).str.strip()
else:
    screening_df["_notes"] = ""

print("\nStandardised screening record preview:")
display(screening_df[["_trait", "_role", "_build", "_status", "_effect_size_type", "_file_name", "_path"]].head(20))

Raw screening record shape: (31, 22)
Raw columns:
['file_name', 'file_path', 'trait', 'study_accession', 'role', 'build', 'variant_identifier', 'chromosome', 'position', 'effect_allele', 'other_allele', 'beta', 'standard_error', 'effect_allele_frequency', 'p_value', 'sample_size', 'full_summary_stats_candidate', 'status', 'notes', 'odds_ratio', 'effect_size_column', 'effect_size_type']

Detected important columns:
trait_col: trait
role_col: role
build_col: build
status_col: status
path_col: file_path
name_col: file_name
effect_size_type_col: effect_size_type
notes_col: notes

Standardised screening record preview:

,_trait,_role,_build,_status,_effect_size_type,_file_name,_path
0,ADIPOQ,exposure,GRCh37,Not suitable for current pipeline,beta,GCST90100621_buildGRCh37.tsv.gz,/content/drive/MyDrive/UM_WQF7023/MRDRP-main/e...
1,ADIPOQ,exposure,GRCh37,Suitable candidate,beta,GCST90161837_buildGRCh37.tsv.gz,/content/drive/MyDrive/UM_WQF7023/MRDRP-main/e...
2,ADIPOQ,exposure,GRCh38,Suitable candidate,beta,GCST90237429_buildGRCh38.tsv.gz,/content/drive/MyDrive/UM_WQF7023/MRDRP-main/e...
3,GDF15,exposure,GRCh37,Suitable candidate,beta,GCST90162057_buildGRCh37.tsv.gz,/content/drive/MyDrive/UM_WQF7023/MRDRP-main/e...
4,GDF15,exposure,GRCh38,Needs adaptation,beta,GCST90179306_buildGRCh38.tsv.gz,/content/drive/MyDrive/UM_WQF7023/MRDRP-main/e...
5,IGF1,exposure,GRCh38,Not suitable for current pipeline,beta,GCST90014008_buildGRCh38.tsv.gz,/content/drive/MyDrive/UM_WQF7023/MRDRP-main/e...
6,IGF1,exposure,GRCh37,Not suitable for current pipeline,beta,GCST90019511_buildGRCh37.tsv,/content/drive/MyDrive/UM_WQF7023/MRDRP-main/e...
7,IGF1,exposure,GRCh37,Not suitable for current pipeline,beta,GCST90025989_buildGRCh37.tsv,/content/drive/MyDrive/UM_WQF7023/MRDRP-main/e...
8,IGF1,exposure,GRCh38,Needs adaptation,beta,GCST90079032_buildGRCh38.tsv.gz,/content/drive/MyDrive/UM_WQF7023/MRDRP-main/e...
9,IGF1,exposure,GRCh38,Needs adaptation,beta,GCST90083018_buildGRCh38.tsv.gz,/content/drive/MyDrive/UM_WQF7023/MRDRP-main/e...
10,IGF1,exposure,GRCh37,Not suitable for current pipeline,unknown,GCST90161219_buildGRCh37.tsv,/content/drive/MyDrive/UM_WQF7023/MRDRP-main/e...
11,IGF1,exposure,Unknown,Not suitable for current pipeline,beta,GCST90297291.tsv.gz,/content/drive/MyDrive/UM_WQF7023/MRDRP-main/e...
12,IGF1,exposure,Unknown,Not suitable for current pipeline,beta,GCST90297335.tsv.gz,/content/drive/MyDrive/UM_WQF7023/MRDRP-main/e...
13,IGF1,exposure,Unknown,Not suitable for current pipeline,beta,GCST90297511.tsv.gz,/content/drive/MyDrive/UM_WQF7023/MRDRP-main/e...
14,IGF1,exposure,Unknown,Suitable candidate,beta,GCST90310168.tsv.gz,/content/drive/MyDrive/UM_WQF7023/MRDRP-main/e...
15,IGF1,exposure,Unknown,Needs adaptation,beta,GCST90319615.tsv.gz,/content/drive/MyDrive/UM_WQF7023/MRDRP-main/e...
16,IGF1,exposure,Unknown,Needs adaptation,beta,GCST90319643.tsv.gz,/content/drive/MyDrive/UM_WQF7023/MRDRP-main/e...
17,IGF1,exposure,Unknown,Needs adaptation,beta,GCST90335170.tsv.gz,/content/drive/MyDrive/UM_WQF7023/MRDRP-main/e...
18,IGF1,exposure,Unknown,Needs adaptation,beta,GCST90335171.tsv.gz,/content/drive/MyDrive/UM_WQF7023/MRDRP-main/e...
19,SHBG,exposure,GRCh37,Suitable candidate,beta,GCST90012106_buildGRCh37.tsv.gz,/content/drive/MyDrive/UM_WQF7023/MRDRP-main/e...

In [ ]:
# ============================================================
# Cell 6.8: Filter usable candidate files from screening record
# ============================================================

TARGET_EXPOSURES = ["IGF1", "SHBG", "ADIPOQ", "GDF15"]
TARGET_OUTCOME = "endometrial_cancer"

PREFERRED_BUILD = "GRCh38"

# Status keywords that are considered usable
# You can adjust these based on your dashboard labels.
USABLE_STATUS_KEYWORDS = [
    "ready",
    "suitable",
    "usable",
    "pass",
    "adaptation",
    "needs adaptation",
    "ready after adaptation"
]

BAD_STATUS_KEYWORDS = [
    "not suitable",
    "unsuitable",
    "missing",
    "fail",
    "failed",
    "not ready",
    "needs review",
    "needs build harmonisation"
]


def normalise_trait_name(x):
    """
    Normalise trait labels so that slight variations can be matched.
    """
    x = str(x).lower().replace("-", "").replace("_", "").replace(" ", "")

    if "igf" in x:
        return "IGF1"
    if "shbg" in x:
        return "SHBG"
    if "adipo" in x or "adiponectin" in x:
        return "ADIPOQ"
    if "gdf15" in x or "gdf" in x:
        return "GDF15"
    if "endometrial" in x or "uterine" in x:
        return "endometrial_cancer"

    return str(x)


def is_exposure_role(x):
    x = str(x).lower()
    return "exposure" in x


def is_outcome_role(x):
    x = str(x).lower()
    return "outcome" in x


def status_score(status):
    """
    Higher score means more usable.
    """
    s = str(status).lower()

    # Bad labels first
    for bad in BAD_STATUS_KEYWORDS:
        if bad in s:
            return -100

    # Strong usable labels
    if "ready after adaptation" in s:
        return 80
    if "ready" in s:
        return 100
    if "suitable" in s:
        return 90
    if "adaptation" in s:
        return 70
    if "usable" in s:
        return 70
    if "pass" in s:
        return 60

    # Unknown but not explicitly bad
    return 0


def build_score(build):
    b = str(build).lower()
    if "grch38" in b or "hg38" in b or "build38" in b:
        return 100
    if "grch37" in b or "hg19" in b or "build37" in b:
        return 50
    return 0


def effect_size_score(effect_size_type, role):
    e = str(effect_size_type).lower()
    r = str(role).lower()

    if "beta" in e:
        return 100

    # Outcome can use odds_ratio if later converted to beta
    if "odds" in e or e == "or":
        if "outcome" in r:
            return 80
        return 30

    return 0


def path_exists_score(path):
    return 100 if Path(str(path)).exists() else -100


candidate_df = screening_df.copy()
candidate_df["_normalised_trait"] = candidate_df["_trait"].apply(normalise_trait_name)
candidate_df["_status_score"] = candidate_df["_status"].apply(status_score)
candidate_df["_build_score"] = candidate_df["_build"].apply(build_score)
candidate_df["_effect_size_score"] = candidate_df.apply(
    lambda row: effect_size_score(row["_effect_size_type"], row["_role"]),
    axis=1
)
candidate_df["_path_exists_score"] = candidate_df["_path"].apply(path_exists_score)

# Keep only target traits
target_all_traits = TARGET_EXPOSURES + [TARGET_OUTCOME]
candidate_df = candidate_df[candidate_df["_normalised_trait"].isin(target_all_traits)].copy()

# Keep role-consistent rows
candidate_df = candidate_df[
    (
        candidate_df["_normalised_trait"].isin(TARGET_EXPOSURES)
        & candidate_df["_role"].apply(is_exposure_role)
    )
    |
    (
        candidate_df["_normalised_trait"].eq(TARGET_OUTCOME)
        & candidate_df["_role"].apply(is_outcome_role)
    )
].copy()

# Overall file score
candidate_df["_overall_score"] = (
    candidate_df["_status_score"]
    + candidate_df["_build_score"]
    + candidate_df["_effect_size_score"]
    + candidate_df["_path_exists_score"]
)

# Sort by trait and score
candidate_df = candidate_df.sort_values(
    by=["_normalised_trait", "_overall_score"],
    ascending=[True, False]
)

print("Candidate files after filtering:")
display(candidate_df[[
    "_normalised_trait",
    "_role",
    "_build",
    "_status",
    "_effect_size_type",
    "_overall_score",
    "_file_name",
    "_path"
]].head(100))

Candidate files after filtering:

,_normalised_trait,_role,_build,_status,_effect_size_type,_overall_score,_file_name,_path
2,ADIPOQ,exposure,GRCh38,Suitable candidate,beta,390,GCST90237429_buildGRCh38.tsv.gz,/content/drive/MyDrive/UM_WQF7023/MRDRP-main/e...
1,ADIPOQ,exposure,GRCh37,Suitable candidate,beta,340,GCST90161837_buildGRCh37.tsv.gz,/content/drive/MyDrive/UM_WQF7023/MRDRP-main/e...
0,ADIPOQ,exposure,GRCh37,Not suitable for current pipeline,beta,150,GCST90100621_buildGRCh37.tsv.gz,/content/drive/MyDrive/UM_WQF7023/MRDRP-main/e...
4,GDF15,exposure,GRCh38,Needs adaptation,beta,370,GCST90179306_buildGRCh38.tsv.gz,/content/drive/MyDrive/UM_WQF7023/MRDRP-main/e...
3,GDF15,exposure,GRCh37,Suitable candidate,beta,340,GCST90162057_buildGRCh37.tsv.gz,/content/drive/MyDrive/UM_WQF7023/MRDRP-main/e...
8,IGF1,exposure,GRCh38,Needs adaptation,beta,370,GCST90079032_buildGRCh38.tsv.gz,/content/drive/MyDrive/UM_WQF7023/MRDRP-main/e...
9,IGF1,exposure,GRCh38,Needs adaptation,beta,370,GCST90083018_buildGRCh38.tsv.gz,/content/drive/MyDrive/UM_WQF7023/MRDRP-main/e...
14,IGF1,exposure,Unknown,Suitable candidate,beta,290,GCST90310168.tsv.gz,/content/drive/MyDrive/UM_WQF7023/MRDRP-main/e...
15,IGF1,exposure,Unknown,Needs adaptation,beta,270,GCST90319615.tsv.gz,/content/drive/MyDrive/UM_WQF7023/MRDRP-main/e...
16,IGF1,exposure,Unknown,Needs adaptation,beta,270,GCST90319643.tsv.gz,/content/drive/MyDrive/UM_WQF7023/MRDRP-main/e...
17,IGF1,exposure,Unknown,Needs adaptation,beta,270,GCST90335170.tsv.gz,/content/drive/MyDrive/UM_WQF7023/MRDRP-main/e...
18,IGF1,exposure,Unknown,Needs adaptation,beta,270,GCST90335171.tsv.gz,/content/drive/MyDrive/UM_WQF7023/MRDRP-main/e...
5,IGF1,exposure,GRCh38,Not suitable for current pipeline,beta,200,GCST90014008_buildGRCh38.tsv.gz,/content/drive/MyDrive/UM_WQF7023/MRDRP-main/e...
6,IGF1,exposure,GRCh37,Not suitable for current pipeline,beta,150,GCST90019511_buildGRCh37.tsv,/content/drive/MyDrive/UM_WQF7023/MRDRP-main/e...
7,IGF1,exposure,GRCh37,Not suitable for current pipeline,beta,150,GCST90025989_buildGRCh37.tsv,/content/drive/MyDrive/UM_WQF7023/MRDRP-main/e...
11,IGF1,exposure,Unknown,Not suitable for current pipeline,beta,100,GCST90297291.tsv.gz,/content/drive/MyDrive/UM_WQF7023/MRDRP-main/e...
12,IGF1,exposure,Unknown,Not suitable for current pipeline,beta,100,GCST90297335.tsv.gz,/content/drive/MyDrive/UM_WQF7023/MRDRP-main/e...
13,IGF1,exposure,Unknown,Not suitable for current pipeline,beta,100,GCST90297511.tsv.gz,/content/drive/MyDrive/UM_WQF7023/MRDRP-main/e...
10,IGF1,exposure,GRCh37,Not suitable for current pipeline,unknown,50,GCST90161219_buildGRCh37.tsv,/content/drive/MyDrive/UM_WQF7023/MRDRP-main/e...
23,SHBG,exposure,GRCh38,Needs adaptation,beta,370,GCST90079040_buildGRCh38.tsv.gz,/content/drive/MyDrive/UM_WQF7023/MRDRP-main/e...
24,SHBG,exposure,GRCh38,Needs adaptation,beta,370,GCST90083026_buildGRCh38.tsv.gz,/content/drive/MyDrive/UM_WQF7023/MRDRP-main/e...
19,SHBG,exposure,GRCh37,Suitable candidate,beta,340,GCST90012106_buildGRCh37.tsv.gz,/content/drive/MyDrive/UM_WQF7023/MRDRP-main/e...
20,SHBG,exposure,GRCh37,Suitable candidate,beta,340,GCST90012107_buildGRCh37.tsv.gz,/content/drive/MyDrive/UM_WQF7023/MRDRP-main/e...
21,SHBG,exposure,GRCh37,Suitable candidate,beta,340,GCST90012108_buildGRCh37.tsv.gz,/content/drive/MyDrive/UM_WQF7023/MRDRP-main/e...
22,SHBG,exposure,GRCh37,Not suitable for current pipeline,beta,150,GCST90019518_buildGRCh37.tsv,/content/drive/MyDrive/UM_WQF7023/MRDRP-main/e...
25,SHBG,exposure,Unknown,Not suitable for current pipeline,beta,100,GCST90297308.tsv.gz,/content/drive/MyDrive/UM_WQF7023/MRDRP-main/e...
26,endometrial_cancer,outcome,GRCh38,Needs adaptation,odds_ratio,350,GCST90077633_buildGRCh38.tsv.gz,/content/drive/MyDrive/UM_WQF7023/MRDRP-main/o...
27,endometrial_cancer,outcome,GRCh38,Needs adaptation,odds_ratio,350,GCST90079109_buildGRCh38.tsv.gz,/content/drive/MyDrive/UM_WQF7023/MRDRP-main/o...
28,endometrial_cancer,outcome,GRCh38,Needs adaptation,odds_ratio,350,GCST90079607_buildGRCh38.tsv.gz,/content/drive/MyDrive/UM_WQF7023/MRDRP-main/o...
29,endometrial_cancer,outcome,GRCh38,Needs adaptation,odds_ratio,350,GCST90083095_buildGRCh38.tsv.gz,/content/drive/MyDrive/UM_WQF7023/MRDRP-main/o...
30,endometrial_cancer,outcome,GRCh38,Needs adaptation,odds_ratio,350,GCST90083593_buildGRCh38.tsv.gz,/content/drive/MyDrive/UM_WQF7023/MRDRP-main/o...

In [ ]:
# ============================================================
# Cell 6.9: Automatically select best 4-exposure + 1-outcome analysis set
# ============================================================

def select_best_file_for_trait(candidate_df, trait, role):
    """
    Select the highest-scoring file for one trait and role.
    """
    sub = candidate_df[candidate_df["_normalised_trait"].eq(trait)].copy()

    if role == "exposure":
        sub = sub[sub["_role"].apply(is_exposure_role)]
    elif role == "outcome":
        sub = sub[sub["_role"].apply(is_outcome_role)]

    if len(sub) == 0:
        return None

    # Prefer the preferred build explicitly if available
    preferred = sub[sub["_build"].astype(str).str.contains(PREFERRED_BUILD, case=False, na=False)].copy()

    if len(preferred) > 0:
        preferred = preferred.sort_values("_overall_score", ascending=False)
        return preferred.iloc[0]

    # Otherwise use highest score
    sub = sub.sort_values("_overall_score", ascending=False)
    return sub.iloc[0]


selected_rows = []

for trait in TARGET_EXPOSURES:
    row = select_best_file_for_trait(candidate_df, trait, role="exposure")
    if row is None:
        print(f"WARNING: No usable exposure candidate found for {trait}")
    else:
        selected_rows.append(row)

outcome_row = select_best_file_for_trait(candidate_df, TARGET_OUTCOME, role="outcome")
if outcome_row is None:
    print(f"WARNING: No usable outcome candidate found for {TARGET_OUTCOME}")
else:
    selected_rows.append(outcome_row)

selected_analysis_df = pd.DataFrame(selected_rows)

print("Automatically selected analysis set:")
display(selected_analysis_df[[
    "_normalised_trait",
    "_role",
    "_build",
    "_status",
    "_effect_size_type",
    "_overall_score",
    "_file_name",
    "_path"
]])

# Build route check
selected_builds = selected_analysis_df["_build"].astype(str).unique().tolist()

if len(selected_analysis_df) < 5:
    set_status = "Needs review: missing required exposure or outcome"
elif len(set([b.lower() for b in selected_builds])) == 1:
    if any(selected_analysis_df["_status"].astype(str).str.lower().str.contains("adaptation", na=False)):
        set_status = "Ready after adaptation"
    else:
        set_status = "Ready"
else:
    set_status = "Needs build harmonisation"

print("\nSelected builds:", selected_builds)
print("Analysis set status:", set_status)

# Create SELECTED_ANALYSIS_FILES dictionary for Cell 7
SELECTED_ANALYSIS_FILES = {}

for _, row in selected_analysis_df.iterrows():
    trait = row["_normalised_trait"]
    SELECTED_ANALYSIS_FILES[trait] = row["_path"]

print("\nSELECTED_ANALYSIS_FILES:")
for trait, path in SELECTED_ANALYSIS_FILES.items():
    print(f"{trait}: {path}")

# Save selected analysis set record
auto_selected_set_path = SUMMARY_DIR / "auto_selected_analysis_set.csv"
selected_analysis_df.to_csv(auto_selected_set_path, index=False)

print("\nAuto-selected analysis set saved to:", auto_selected_set_path)

Automatically selected analysis set:

,_normalised_trait,_role,_build,_status,_effect_size_type,_overall_score,_file_name,_path
8,IGF1,exposure,GRCh38,Needs adaptation,beta,370,GCST90079032_buildGRCh38.tsv.gz,/content/drive/MyDrive/UM_WQF7023/MRDRP-main/e...
23,SHBG,exposure,GRCh38,Needs adaptation,beta,370,GCST90079040_buildGRCh38.tsv.gz,/content/drive/MyDrive/UM_WQF7023/MRDRP-main/e...
2,ADIPOQ,exposure,GRCh38,Suitable candidate,beta,390,GCST90237429_buildGRCh38.tsv.gz,/content/drive/MyDrive/UM_WQF7023/MRDRP-main/e...
4,GDF15,exposure,GRCh38,Needs adaptation,beta,370,GCST90179306_buildGRCh38.tsv.gz,/content/drive/MyDrive/UM_WQF7023/MRDRP-main/e...
26,endometrial_cancer,outcome,GRCh38,Needs adaptation,odds_ratio,350,GCST90077633_buildGRCh38.tsv.gz,/content/drive/MyDrive/UM_WQF7023/MRDRP-main/o...

Selected builds: ['GRCh38']
Analysis set status: Ready after adaptation

SELECTED_ANALYSIS_FILES:
IGF1: /content/drive/MyDrive/UM_WQF7023/MRDRP-main/exposures/IGF1/GCST90079032_buildGRCh38.tsv.gz
SHBG: /content/drive/MyDrive/UM_WQF7023/MRDRP-main/exposures/SHBG/GCST90079040_buildGRCh38.tsv.gz
ADIPOQ: /content/drive/MyDrive/UM_WQF7023/MRDRP-main/exposures/ADIPOQ/GCST90237429_buildGRCh38.tsv.gz
GDF15: /content/drive/MyDrive/UM_WQF7023/MRDRP-main/exposures/GDF15/GCST90179306_buildGRCh38.tsv.gz
endometrial_cancer: /content/drive/MyDrive/UM_WQF7023/MRDRP-main/outcome/endometrial_cancer/GCST90077633_buildGRCh38.tsv.gz

Auto-selected analysis set saved to: /content/drive/MyDrive/UM_WQF7023/MRDRP-main/backend_work/mr_outputs/summary/auto_selected_analysis_set.csv

In [ ]:
# ============================================================
# Cell 6.9B: Select multiple outcome candidates for comparison
# ============================================================

TOP_N_OUTCOMES = 5

# Exposure files still use the best selected exposure candidates from Cell 6.9
selected_exposure_files = {
    trait: SELECTED_ANALYSIS_FILES[trait]
    for trait in TARGET_EXPOSURES
    if trait in SELECTED_ANALYSIS_FILES
}

# Get all outcome candidates for endometrial cancer
outcome_candidates = candidate_df[
    candidate_df["_normalised_trait"].eq(TARGET_OUTCOME)
    & candidate_df["_role"].apply(is_outcome_role)
].copy()

# Prefer GRCh38
outcome_candidates["_preferred_build"] = outcome_candidates["_build"].astype(str).str.contains(
    "GRCh38", case=False, na=False
)

outcome_candidates = outcome_candidates.sort_values(
    by=["_preferred_build", "_overall_score", "_file_name"],
    ascending=[False, False, True]
)

top_outcome_candidates = outcome_candidates.head(TOP_N_OUTCOMES).copy()

print("Top outcome candidates:")
display(top_outcome_candidates[[
    "_normalised_trait",
    "_role",
    "_build",
    "_status",
    "_effect_size_type",
    "_overall_score",
    "_file_name",
    "_path"
]])

top_outcome_candidates_path = SUMMARY_DIR / "top_outcome_candidates_for_comparison.csv"
top_outcome_candidates.to_csv(top_outcome_candidates_path, index=False)

print("Saved to:", top_outcome_candidates_path)

Top outcome candidates:

,_normalised_trait,_role,_build,_status,_effect_size_type,_overall_score,_file_name,_path
26,endometrial_cancer,outcome,GRCh38,Needs adaptation,odds_ratio,350,GCST90077633_buildGRCh38.tsv.gz,/content/drive/MyDrive/UM_WQF7023/MRDRP-main/o...
27,endometrial_cancer,outcome,GRCh38,Needs adaptation,odds_ratio,350,GCST90079109_buildGRCh38.tsv.gz,/content/drive/MyDrive/UM_WQF7023/MRDRP-main/o...
28,endometrial_cancer,outcome,GRCh38,Needs adaptation,odds_ratio,350,GCST90079607_buildGRCh38.tsv.gz,/content/drive/MyDrive/UM_WQF7023/MRDRP-main/o...
29,endometrial_cancer,outcome,GRCh38,Needs adaptation,odds_ratio,350,GCST90083095_buildGRCh38.tsv.gz,/content/drive/MyDrive/UM_WQF7023/MRDRP-main/o...
30,endometrial_cancer,outcome,GRCh38,Needs adaptation,odds_ratio,350,GCST90083593_buildGRCh38.tsv.gz,/content/drive/MyDrive/UM_WQF7023/MRDRP-main/o...

Saved to: /content/drive/MyDrive/UM_WQF7023/MRDRP-main/backend_work/mr_outputs/summary/top_outcome_candidates_for_comparison.csv

In [ ]:
# ============================================================
# Cell 6.9C: Create multiple analysis sets with different outcome files
# ============================================================

MULTI_OUTCOME_ANALYSIS_SETS = []

for idx, (_, outcome_row) in enumerate(top_outcome_candidates.iterrows(), start=1):
    set_name = f"Artesunate_EndometrialCancer_GRCh38_OutcomeCompare_{idx:02d}"

    selected_files = selected_exposure_files.copy()
    selected_files[TARGET_OUTCOME] = outcome_row["_path"]

    MULTI_OUTCOME_ANALYSIS_SETS.append({
        "set_name": set_name,
        "outcome_file": outcome_row["_path"],
        "outcome_file_name": outcome_row["_file_name"],
        "outcome_build": outcome_row["_build"],
        "outcome_status": outcome_row["_status"],
        "outcome_effect_size_type": outcome_row["_effect_size_type"],
        "selected_files": selected_files,
    })

multi_outcome_sets_df = pd.DataFrame([
    {
        "set_name": s["set_name"],
        "outcome_file_name": s["outcome_file_name"],
        "outcome_build": s["outcome_build"],
        "outcome_status": s["outcome_status"],
        "outcome_effect_size_type": s["outcome_effect_size_type"],
        "outcome_file": s["outcome_file"],
    }
    for s in MULTI_OUTCOME_ANALYSIS_SETS
])

display(multi_outcome_sets_df)

multi_outcome_sets_path = SUMMARY_DIR / "multi_outcome_analysis_sets.csv"
multi_outcome_sets_df.to_csv(multi_outcome_sets_path, index=False)

print("Saved to:", multi_outcome_sets_path)

,set_name,outcome_file_name,outcome_build,outcome_status,outcome_effect_size_type,outcome_file
0,Artesunate_EndometrialCancer_GRCh38_OutcomeCom...,GCST90077633_buildGRCh38.tsv.gz,GRCh38,Needs adaptation,odds_ratio,/content/drive/MyDrive/UM_WQF7023/MRDRP-main/o...
1,Artesunate_EndometrialCancer_GRCh38_OutcomeCom...,GCST90079109_buildGRCh38.tsv.gz,GRCh38,Needs adaptation,odds_ratio,/content/drive/MyDrive/UM_WQF7023/MRDRP-main/o...
2,Artesunate_EndometrialCancer_GRCh38_OutcomeCom...,GCST90079607_buildGRCh38.tsv.gz,GRCh38,Needs adaptation,odds_ratio,/content/drive/MyDrive/UM_WQF7023/MRDRP-main/o...
3,Artesunate_EndometrialCancer_GRCh38_OutcomeCom...,GCST90083095_buildGRCh38.tsv.gz,GRCh38,Needs adaptation,odds_ratio,/content/drive/MyDrive/UM_WQF7023/MRDRP-main/o...
4,Artesunate_EndometrialCancer_GRCh38_OutcomeCom...,GCST90083593_buildGRCh38.tsv.gz,GRCh38,Needs adaptation,odds_ratio,/content/drive/MyDrive/UM_WQF7023/MRDRP-main/o...

Saved to: /content/drive/MyDrive/UM_WQF7023/MRDRP-main/backend_work/mr_outputs/summary/multi_outcome_analysis_sets.csv

In [ ]:
# ============================================================
# Cell 6.10: Fast preview check for automatically selected files
# ============================================================

selected_check_records = []

for trait, file_path in SELECTED_ANALYSIS_FILES.items():
    path = Path(file_path)

    if not path.exists():
        selected_check_records.append({
            "trait": trait,
            "file_path": str(path),
            "exists": False,
            "build": None,
            "detected_SNP": None,
            "detected_CHR": None,
            "detected_POS": None,
            "detected_BETA": None,
            "detected_OR": None,
            "detected_SE": None,
            "detected_EAF": None,
            "detected_P": None,
            "status": "file_not_found"
        })
        continue

    preview = read_gwas_file(path, nrows=5)
    detected = detect_columns(preview)

    selected_check_records.append({
        "trait": trait,
        "file_path": str(path),
        "exists": True,
        "build": infer_build_from_filename(path),
        "detected_SNP": detected.get("SNP"),
        "detected_CHR": detected.get("CHR"),
        "detected_POS": detected.get("POS"),
        "detected_BETA": detected.get("BETA"),
        "detected_OR": detected.get("OR"),
        "detected_SE": detected.get("SE"),
        "detected_EAF": detected.get("EAF"),
        "detected_P": detected.get("P"),
        "status": "preview_checked"
    })

selected_check_df = pd.DataFrame(selected_check_records)

print("Fast preview check for selected analysis set:")
display(selected_check_df)

selected_check_path = SUMMARY_DIR / "auto_selected_analysis_set_fast_check.csv"
selected_check_df.to_csv(selected_check_path, index=False)

print("Fast check saved to:", selected_check_path)

Fast preview check for selected analysis set:

,trait,file_path,exists,build,detected_SNP,detected_CHR,detected_POS,detected_BETA,detected_OR,detected_SE,detected_EAF,detected_P,status
0,IGF1,/content/drive/MyDrive/UM_WQF7023/MRDRP-main/e...,True,GRCh38,None,chromosome,base_pair_location,beta,None,standard_error,effect_allele_frequency,p_value,preview_checked
1,SHBG,/content/drive/MyDrive/UM_WQF7023/MRDRP-main/e...,True,GRCh38,None,chromosome,base_pair_location,beta,None,standard_error,effect_allele_frequency,p_value,preview_checked
2,ADIPOQ,/content/drive/MyDrive/UM_WQF7023/MRDRP-main/e...,True,GRCh38,variant_id,chromosome,base_pair_location,beta,None,standard_error,effect_allele_frequency,p_value,preview_checked
3,GDF15,/content/drive/MyDrive/UM_WQF7023/MRDRP-main/e...,True,GRCh38,None,chromosome,base_pair_location,beta,None,standard_error,effect_allele_frequency,p_value,preview_checked
4,endometrial_cancer,/content/drive/MyDrive/UM_WQF7023/MRDRP-main/o...,True,GRCh38,None,chromosome,base_pair_location,None,odds_ratio,standard_error,effect_allele_frequency,p_value,preview_checked

Fast check saved to: /content/drive/MyDrive/UM_WQF7023/MRDRP-main/backend_work/mr_outputs/summary/auto_selected_analysis_set_fast_check.csv

In [ ]:
# ============================================================
# Cell 7.0: Check current preprocessing status before rerunning Cell 7
# ============================================================

from pathlib import Path
import pandas as pd
import os
from datetime import datetime

print("Checking current backend preprocessing files...\n")

# 1. Check fast check file from Cell 6.10
fast_check_path = SUMMARY_DIR / "auto_selected_analysis_set_fast_check.csv"
print("=" * 80)
print("Fast check file:")
print("Path:", fast_check_path)
print("Exists:", fast_check_path.exists())

if fast_check_path.exists():
    print("Last modified:", datetime.fromtimestamp(fast_check_path.stat().st_mtime))
    fast_check_df = pd.read_csv(fast_check_path)
    display(fast_check_df)
else:
    print("WARNING: auto_selected_analysis_set_fast_check.csv does not exist. Please rerun Cell 6.10.")

# 2. Check selected analysis files dictionary
print("\n" + "=" * 80)
print("SELECTED_ANALYSIS_FILES in memory:")

if "SELECTED_ANALYSIS_FILES" not in globals():
    print("WARNING: SELECTED_ANALYSIS_FILES is not found in memory. Please rerun Cell 6.9.")
else:
    for trait, path in SELECTED_ANALYSIS_FILES.items():
        print(f"{trait}: {path}")

# 3. Check prepared output files
print("\n" + "=" * 80)
print("Prepared standardised files:")

prepared_check_records = []

if "SELECTED_ANALYSIS_FILES" in globals():
    for trait in TARGET_EXPOSURES:
        output_file = PREPARED_EXPOSURE_ROOT / trait / f"{trait}_standardised.csv"
        prepared_check_records.append({
            "trait": trait,
            "role": "exposure",
            "output_file": str(output_file),
            "exists": output_file.exists(),
            "size_MB": round(output_file.stat().st_size / 1024 / 1024, 2) if output_file.exists() else 0,
            "last_modified": datetime.fromtimestamp(output_file.stat().st_mtime).strftime("%Y-%m-%d %H:%M:%S") if output_file.exists() else None,
        })

    outcome_output_file = PREPARED_OUTCOME_ROOT / "endometrial_cancer_standardised.csv"
    prepared_check_records.append({
        "trait": TARGET_OUTCOME,
        "role": "outcome",
        "output_file": str(outcome_output_file),
        "exists": outcome_output_file.exists(),
        "size_MB": round(outcome_output_file.stat().st_size / 1024 / 1024, 2) if outcome_output_file.exists() else 0,
        "last_modified": datetime.fromtimestamp(outcome_output_file.stat().st_mtime).strftime("%Y-%m-%d %H:%M:%S") if outcome_output_file.exists() else None,
    })

prepared_check_df = pd.DataFrame(prepared_check_records)
display(prepared_check_df)

# 4. Check preprocessing summary
print("\n" + "=" * 80)
print("Preprocessing summary:")

preprocess_summary_path = SUMMARY_DIR / "backend_preprocessing_summary.csv"
print("Path:", preprocess_summary_path)
print("Exists:", preprocess_summary_path.exists())

if preprocess_summary_path.exists():
    print("Last modified:", datetime.fromtimestamp(preprocess_summary_path.stat().st_mtime))
    current_preprocess_summary = pd.read_csv(preprocess_summary_path)
    display(current_preprocess_summary)
else:
    print("WARNING: backend_preprocessing_summary.csv does not exist.")

Checking current backend preprocessing files...

================================================================================
Fast check file:
Path: /content/drive/MyDrive/UM_WQF7023/MRDRP-main/backend_work/mr_outputs/summary/auto_selected_analysis_set_fast_check.csv
Exists: True
Last modified: 2026-05-13 12:45:40

,trait,file_path,exists,build,detected_SNP,detected_CHR,detected_POS,detected_BETA,detected_OR,detected_SE,detected_EAF,detected_P,status
0,IGF1,/content/drive/MyDrive/UM_WQF7023/MRDRP-main/e...,True,GRCh38,NaN,chromosome,base_pair_location,beta,NaN,standard_error,effect_allele_frequency,p_value,preview_checked
1,SHBG,/content/drive/MyDrive/UM_WQF7023/MRDRP-main/e...,True,GRCh38,NaN,chromosome,base_pair_location,beta,NaN,standard_error,effect_allele_frequency,p_value,preview_checked
2,ADIPOQ,/content/drive/MyDrive/UM_WQF7023/MRDRP-main/e...,True,GRCh38,variant_id,chromosome,base_pair_location,beta,NaN,standard_error,effect_allele_frequency,p_value,preview_checked
3,GDF15,/content/drive/MyDrive/UM_WQF7023/MRDRP-main/e...,True,GRCh38,NaN,chromosome,base_pair_location,beta,NaN,standard_error,effect_allele_frequency,p_value,preview_checked
4,endometrial_cancer,/content/drive/MyDrive/UM_WQF7023/MRDRP-main/o...,True,GRCh38,NaN,chromosome,base_pair_location,NaN,odds_ratio,standard_error,effect_allele_frequency,p_value,preview_checked

================================================================================
SELECTED_ANALYSIS_FILES in memory:
IGF1: /content/drive/MyDrive/UM_WQF7023/MRDRP-main/exposures/IGF1/GCST90079032_buildGRCh38.tsv.gz
SHBG: /content/drive/MyDrive/UM_WQF7023/MRDRP-main/exposures/SHBG/GCST90079040_buildGRCh38.tsv.gz
ADIPOQ: /content/drive/MyDrive/UM_WQF7023/MRDRP-main/exposures/ADIPOQ/GCST90237429_buildGRCh38.tsv.gz
GDF15: /content/drive/MyDrive/UM_WQF7023/MRDRP-main/exposures/GDF15/GCST90179306_buildGRCh38.tsv.gz
endometrial_cancer: /content/drive/MyDrive/UM_WQF7023/MRDRP-main/outcome/endometrial_cancer/GCST90077633_buildGRCh38.tsv.gz

================================================================================
Prepared standardised files:

,trait,role,output_file,exists,size_MB,last_modified
0,IGF1,exposure,/content/drive/MyDrive/UM_WQF7023/MRDRP-main/b...,True,95.25,2026-05-13 07:29:20
1,SHBG,exposure,/content/drive/MyDrive/UM_WQF7023/MRDRP-main/b...,True,89.74,2026-05-13 07:29:34
2,ADIPOQ,exposure,/content/drive/MyDrive/UM_WQF7023/MRDRP-main/b...,True,205.42,2026-05-13 07:50:45
3,GDF15,exposure,/content/drive/MyDrive/UM_WQF7023/MRDRP-main/b...,True,5139.79,2026-05-13 07:38:09
4,endometrial_cancer,outcome,/content/drive/MyDrive/UM_WQF7023/MRDRP-main/b...,True,18.39,2026-05-13 13:05:06

================================================================================
Preprocessing summary:
Path: /content/drive/MyDrive/UM_WQF7023/MRDRP-main/backend_work/mr_outputs/summary/backend_preprocessing_summary.csv
Exists: True
Last modified: 2026-05-13 13:05:04

,trait,role,input_file,output_file,rows_saved,effect_size_type,build,snp_source_type,detected_columns
0,IGF1,exposure,/content/drive/MyDrive/UM_WQF7023/MRDRP-main/e...,/content/drive/MyDrive/UM_WQF7023/MRDRP-main/b...,464432,beta,GRCh38,pseudo_chr_pos_allele_id,"{'SNP': None, 'CHR': 'chromosome', 'POS': 'bas..."
1,SHBG,exposure,/content/drive/MyDrive/UM_WQF7023/MRDRP-main/e...,/content/drive/MyDrive/UM_WQF7023/MRDRP-main/b...,437423,beta,GRCh38,pseudo_chr_pos_allele_id,"{'SNP': None, 'CHR': 'chromosome', 'POS': 'bas..."
2,ADIPOQ,exposure,/content/drive/MyDrive/UM_WQF7023/MRDRP-main/e...,/content/drive/MyDrive/UM_WQF7023/MRDRP-main/b...,13976587,beta,GRCh38,detected_snp_column,"{'SNP': 'variant_id', 'CHR': 'chromosome', 'PO..."
3,GDF15,exposure,/content/drive/MyDrive/UM_WQF7023/MRDRP-main/e...,/content/drive/MyDrive/UM_WQF7023/MRDRP-main/b...,26372674,beta,GRCh38,pseudo_chr_pos_allele_id,"{'SNP': None, 'CHR': 'chromosome', 'POS': 'bas..."
4,endometrial_cancer,outcome,/content/drive/MyDrive/UM_WQF7023/MRDRP-main/o...,/content/drive/MyDrive/UM_WQF7023/MRDRP-main/b...,70746,odds_ratio_converted_to_beta,GRCh38,pseudo_chr_pos_allele_id,"{'SNP': None, 'CHR': 'chromosome', 'POS': 'bas..."

In [ ]:
# ============================================================
# Cell 7: Preprocess automatically selected 4 exposures + 1 outcome only
# ============================================================

# Check required traits before preprocessing
required_keys = TARGET_EXPOSURES + [TARGET_OUTCOME]
missing_keys = [k for k in required_keys if k not in SELECTED_ANALYSIS_FILES]

if missing_keys:
    raise ValueError(f"Missing selected files for: {missing_keys}")

preprocess_records = []

# Process selected exposures only
for trait in TARGET_EXPOSURES:
    input_file = Path(SELECTED_ANALYSIS_FILES[trait])

    if not input_file.exists():
        print(f"WARNING: Selected file not found for exposure {trait}: {input_file}")
        continue

    output_file = PREPARED_EXPOSURE_ROOT / trait / f"{trait}_standardised.csv"

    try:
        record = standardise_gwas_file(
            input_path=input_file,
            output_path=output_file,
            trait=trait,
            role="exposure",
            force_binary_outcome_or_to_beta=False
        )
        preprocess_records.append(record)

    except Exception as e:
        print(f"ERROR while processing exposure {trait}: {e}")
        preprocess_records.append({
            "trait": trait,
            "role": "exposure",
            "input_file": str(input_file),
            "output_file": str(output_file),
            "rows_saved": 0,
            "effect_size_type": None,
            "build": infer_build_from_filename(input_file),
            "snp_source_type": None,
            "se_source_type": None,
            "error": str(e),
        })

# Process selected outcome only
outcome_input_file = Path(SELECTED_ANALYSIS_FILES[TARGET_OUTCOME])

if not outcome_input_file.exists():
    raise FileNotFoundError(f"Selected outcome file not found: {outcome_input_file}")

outcome_output_file = PREPARED_OUTCOME_ROOT / "endometrial_cancer_standardised.csv"

try:
    outcome_record = standardise_gwas_file(
        input_path=outcome_input_file,
        output_path=outcome_output_file,
        trait=TARGET_OUTCOME,
        role="outcome",
        force_binary_outcome_or_to_beta=True
    )
    preprocess_records.append(outcome_record)

except Exception as e:
    print(f"ERROR while processing outcome {TARGET_OUTCOME}: {e}")
    preprocess_records.append({
        "trait": TARGET_OUTCOME,
        "role": "outcome",
        "input_file": str(outcome_input_file),
        "output_file": str(outcome_output_file),
        "rows_saved": 0,
        "effect_size_type": None,
        "build": infer_build_from_filename(outcome_input_file),
        "snp_source_type": None,
        "se_source_type": None,
        "error": str(e),
    })

# Save preprocessing summary
preprocess_summary = pd.DataFrame(preprocess_records)

preprocess_summary_path = SUMMARY_DIR / "backend_preprocessing_summary.csv"
preprocess_summary.to_csv(preprocess_summary_path, index=False)

print("\nPreprocessing summary:")
display(preprocess_summary)
print("Saved to:", preprocess_summary_path)

Processing exposure: IGF1
Input: /content/drive/MyDrive/UM_WQF7023/MRDRP-main/exposures/IGF1/GCST90079032_buildGRCh38.tsv.gz
Detected columns:
  SNP: None
  CHR: chromosome
  POS: base_pair_location
  EA: effect_allele
  OA: other_allele
  BETA: beta
  OR: None
  SE: standard_error
  EAF: effect_allele_frequency
  P: p_value
  N: None
WARNING: No rsID/SNP column detected. Creating pseudo SNP ID using CHR:POS:EA:OA.
Output: /content/drive/MyDrive/UM_WQF7023/MRDRP-main/backend_work/prepared_exposures/IGF1/IGF1_standardised.csv
Rows saved: 464432
Effect size type: beta
SNP source type: pseudo_chr_pos_allele_id
Build inferred: GRCh38
NOTE: This file does not have real rsID. The pseudo SNP ID can help preprocessing continue, but formal LD clumping/MR may require rsID-based files.

Processing exposure: SHBG
Input: /content/drive/MyDrive/UM_WQF7023/MRDRP-main/exposures/SHBG/GCST90079040_buildGRCh38.tsv.gz
Detected columns:
  SNP: None
  CHR: chromosome
  POS: base_pair_location
  EA: effect_allele
  OA: other_allele
  BETA: beta
  OR: None
  SE: standard_error
  EAF: effect_allele_frequency
  P: p_value
  N: None
WARNING: No rsID/SNP column detected. Creating pseudo SNP ID using CHR:POS:EA:OA.
Output: /content/drive/MyDrive/UM_WQF7023/MRDRP-main/backend_work/prepared_exposures/SHBG/SHBG_standardised.csv
Rows saved: 437423
Effect size type: beta
SNP source type: pseudo_chr_pos_allele_id
Build inferred: GRCh38
NOTE: This file does not have real rsID. The pseudo SNP ID can help preprocessing continue, but formal LD clumping/MR may require rsID-based files.

Processing exposure: ADIPOQ
Input: /content/drive/MyDrive/UM_WQF7023/MRDRP-main/exposures/ADIPOQ/GCST90237429_buildGRCh38.tsv.gz
Detected columns:
  SNP: variant_id
  CHR: chromosome
  POS: base_pair_location
  EA: effect_allele
  OA: other_allele
  BETA: beta
  OR: None
  SE: standard_error
  EAF: effect_allele_frequency
  P: p_value
  N: None
Output: /content/drive/MyDrive/UM_WQF7023/MRDRP-main/backend_work/prepared_exposures/ADIPOQ/ADIPOQ_standardised.csv
Rows saved: 13976587
Effect size type: beta
SNP source type: detected_snp_column
Build inferred: GRCh38

Processing exposure: GDF15
Input: /content/drive/MyDrive/UM_WQF7023/MRDRP-main/exposures/GDF15/GCST90179306_buildGRCh38.tsv.gz
Detected columns:
  SNP: None
  CHR: chromosome
  POS: base_pair_location
  EA: effect_allele
  OA: other_allele
  BETA: beta
  OR: None
  SE: standard_error
  EAF: effect_allele_frequency
  P: p_value
  N: None
WARNING: No rsID/SNP column detected. Creating pseudo SNP ID using CHR:POS:EA:OA.
Output: /content/drive/MyDrive/UM_WQF7023/MRDRP-main/backend_work/prepared_exposures/GDF15/GDF15_standardised.csv
Rows saved: 26372674
Effect size type: beta
SNP source type: pseudo_chr_pos_allele_id
Build inferred: GRCh38
NOTE: This file does not have real rsID. The pseudo SNP ID can help preprocessing continue, but formal LD clumping/MR may require rsID-based files.

Processing outcome: endometrial_cancer
Input: /content/drive/MyDrive/UM_WQF7023/MRDRP-main/outcome/endometrial_cancer/GCST90077633_buildGRCh38.tsv.gz
Detected columns:
  SNP: None
  CHR: chromosome
  POS: base_pair_location
  EA: effect_allele
  OA: other_allele
  BETA: None
  OR: odds_ratio
  SE: standard_error
  EAF: effect_allele_frequency
  P: p_value
  N: None
WARNING: No rsID/SNP column detected. Creating pseudo SNP ID using CHR:POS:EA:OA.

/usr/local/lib/python3.12/dist-packages/pandas/core/arraylike.py:399: RuntimeWarning: divide by zero encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)
/usr/local/lib/python3.12/dist-packages/pandas/core/arraylike.py:399: RuntimeWarning: divide by zero encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)

Output: /content/drive/MyDrive/UM_WQF7023/MRDRP-main/backend_work/prepared_outcome/endometrial_cancer_standardised.csv
Rows saved: 70746
Effect size type: odds_ratio_converted_to_beta
SNP source type: pseudo_chr_pos_allele_id
Build inferred: GRCh38
NOTE: This file does not have real rsID. The pseudo SNP ID can help preprocessing continue, but formal LD clumping/MR may require rsID-based files.

Preprocessing summary:

,trait,role,input_file,output_file,rows_saved,effect_size_type,build,snp_source_type,detected_columns
0,IGF1,exposure,/content/drive/MyDrive/UM_WQF7023/MRDRP-main/e...,/content/drive/MyDrive/UM_WQF7023/MRDRP-main/b...,464432,beta,GRCh38,pseudo_chr_pos_allele_id,"{'SNP': None, 'CHR': 'chromosome', 'POS': 'bas..."
1,SHBG,exposure,/content/drive/MyDrive/UM_WQF7023/MRDRP-main/e...,/content/drive/MyDrive/UM_WQF7023/MRDRP-main/b...,437423,beta,GRCh38,pseudo_chr_pos_allele_id,"{'SNP': None, 'CHR': 'chromosome', 'POS': 'bas..."
2,ADIPOQ,exposure,/content/drive/MyDrive/UM_WQF7023/MRDRP-main/e...,/content/drive/MyDrive/UM_WQF7023/MRDRP-main/b...,13976587,beta,GRCh38,detected_snp_column,"{'SNP': 'variant_id', 'CHR': 'chromosome', 'PO..."
3,GDF15,exposure,/content/drive/MyDrive/UM_WQF7023/MRDRP-main/e...,/content/drive/MyDrive/UM_WQF7023/MRDRP-main/b...,26372674,beta,GRCh38,pseudo_chr_pos_allele_id,"{'SNP': None, 'CHR': 'chromosome', 'POS': 'bas..."
4,endometrial_cancer,outcome,/content/drive/MyDrive/UM_WQF7023/MRDRP-main/o...,/content/drive/MyDrive/UM_WQF7023/MRDRP-main/b...,70746,odds_ratio_converted_to_beta,GRCh38,pseudo_chr_pos_allele_id,"{'SNP': None, 'CHR': 'chromosome', 'POS': 'bas..."

Saved to: /content/drive/MyDrive/UM_WQF7023/MRDRP-main/backend_work/mr_outputs/summary/backend_preprocessing_summary.csv

In [ ]:
# ============================================================
# Cell 7.1: Validate preprocessing result
# ============================================================

preprocess_summary_path = SUMMARY_DIR / "backend_preprocessing_summary.csv"

if not preprocess_summary_path.exists():
    raise FileNotFoundError("backend_preprocessing_summary.csv was not generated. Please rerun Cell 7.")

preprocess_summary = pd.read_csv(preprocess_summary_path)

print("Preprocessing summary:")
display(preprocess_summary)

# Basic validation
required_traits = TARGET_EXPOSURES + [TARGET_OUTCOME]

summary_traits = preprocess_summary["trait"].astype(str).tolist()
missing_traits = [t for t in required_traits if t not in summary_traits]

if missing_traits:
    print("WARNING: Missing traits in preprocessing summary:", missing_traits)
else:
    print("All required traits are present in preprocessing summary.")

# Check row count
if "rows_saved" in preprocess_summary.columns:
    zero_rows = preprocess_summary[preprocess_summary["rows_saved"].fillna(0) <= 0]
    if len(zero_rows) > 0:
        print("\nWARNING: Some files saved zero rows:")
        display(zero_rows)
    else:
        print("All preprocessed files have rows_saved > 0.")

# Check errors
if "error" in preprocess_summary.columns:
    error_rows = preprocess_summary[preprocess_summary["error"].notna()]
    if len(error_rows) > 0:
        print("\nWARNING: Some preprocessing errors were recorded:")
        display(error_rows)
    else:
        print("No preprocessing errors recorded.")

# Check build consistency
if "build" in preprocess_summary.columns:
    print("\nBuild counts:")
    display(preprocess_summary["build"].value_counts().reset_index().rename(
        columns={"index": "build", "build": "count"}
    ))

# Check SNP source and SE source
for col in ["snp_source_type", "se_source_type", "effect_size_type"]:
    if col in preprocess_summary.columns:
        print(f"\n{col} counts:")
        display(preprocess_summary[col].value_counts(dropna=False).reset_index().rename(
            columns={"index": col, col: "count"}
        ))

Preprocessing summary:

,trait,role,input_file,output_file,rows_saved,effect_size_type,build,snp_source_type,detected_columns
0,IGF1,exposure,/content/drive/MyDrive/UM_WQF7023/MRDRP-main/e...,/content/drive/MyDrive/UM_WQF7023/MRDRP-main/b...,464432,beta,GRCh38,pseudo_chr_pos_allele_id,"{'SNP': None, 'CHR': 'chromosome', 'POS': 'bas..."
1,SHBG,exposure,/content/drive/MyDrive/UM_WQF7023/MRDRP-main/e...,/content/drive/MyDrive/UM_WQF7023/MRDRP-main/b...,437423,beta,GRCh38,pseudo_chr_pos_allele_id,"{'SNP': None, 'CHR': 'chromosome', 'POS': 'bas..."
2,ADIPOQ,exposure,/content/drive/MyDrive/UM_WQF7023/MRDRP-main/e...,/content/drive/MyDrive/UM_WQF7023/MRDRP-main/b...,13976587,beta,GRCh38,detected_snp_column,"{'SNP': 'variant_id', 'CHR': 'chromosome', 'PO..."
3,GDF15,exposure,/content/drive/MyDrive/UM_WQF7023/MRDRP-main/e...,/content/drive/MyDrive/UM_WQF7023/MRDRP-main/b...,26372674,beta,GRCh38,pseudo_chr_pos_allele_id,"{'SNP': None, 'CHR': 'chromosome', 'POS': 'bas..."
4,endometrial_cancer,outcome,/content/drive/MyDrive/UM_WQF7023/MRDRP-main/o...,/content/drive/MyDrive/UM_WQF7023/MRDRP-main/b...,70746,odds_ratio_converted_to_beta,GRCh38,pseudo_chr_pos_allele_id,"{'SNP': None, 'CHR': 'chromosome', 'POS': 'bas..."

All required traits are present in preprocessing summary.
All preprocessed files have rows_saved > 0.

Build counts:

    count  count
0  GRCh38      5

snp_source_type counts:

                      count  count
0  pseudo_chr_pos_allele_id      4
1       detected_snp_column      1

effect_size_type counts:

                          count  count
0                          beta      4
1  odds_ratio_converted_to_beta      1

In [ ]:
# ============================================================
# Cell 7.2: Create slim standardised files for backend MR
# ============================================================

import pandas as pd
import shutil
from pathlib import Path

SLIM_EXPOSURE_ROOT = BACKEND_ROOT / "slim_prepared_exposures"
SLIM_OUTCOME_ROOT = BACKEND_ROOT / "slim_prepared_outcome"

if SLIM_EXPOSURE_ROOT.exists():
    shutil.rmtree(SLIM_EXPOSURE_ROOT)
if SLIM_OUTCOME_ROOT.exists():
    shutil.rmtree(SLIM_OUTCOME_ROOT)

SLIM_EXPOSURE_ROOT.mkdir(parents=True, exist_ok=True)
SLIM_OUTCOME_ROOT.mkdir(parents=True, exist_ok=True)

MR_REQUIRED_COLUMNS = ["SNP", "CHR", "POS", "EA", "OA", "BETA", "SE", "EAF", "P", "N"]

def create_slim_csv(input_file: Path, output_file: Path, chunksize=500000):
    output_file.parent.mkdir(parents=True, exist_ok=True)

    first_chunk = True
    total_rows = 0

    for chunk in pd.read_csv(input_file, chunksize=chunksize, low_memory=False):
        available_cols = [c for c in MR_REQUIRED_COLUMNS if c in chunk.columns]
        slim = chunk[available_cols].copy()

        # Ensure all required columns exist
        for col in MR_REQUIRED_COLUMNS:
            if col not in slim.columns:
                slim[col] = pd.NA

        slim = slim[MR_REQUIRED_COLUMNS]

        slim.to_csv(
            output_file,
            index=False,
            mode="w" if first_chunk else "a",
            header=first_chunk
        )

        total_rows += len(slim)
        first_chunk = False

    return total_rows

slim_records = []

# Exposures
for trait in TARGET_EXPOSURES:
    input_file = PREPARED_EXPOSURE_ROOT / trait / f"{trait}_standardised.csv"
    output_file = SLIM_EXPOSURE_ROOT / trait / f"{trait}_standardised_slim.csv"

    if input_file.exists():
        print(f"Creating slim file for {trait}...")
        rows = create_slim_csv(input_file, output_file)

        slim_records.append({
            "trait": trait,
            "role": "exposure",
            "input_file": str(input_file),
            "output_file": str(output_file),
            "rows": rows,
            "size_MB": round(output_file.stat().st_size / 1024 / 1024, 2)
        })

        print(f"Saved: {output_file}")
        print(f"Rows: {rows}, Size MB: {round(output_file.stat().st_size / 1024 / 1024, 2)}")
    else:
        print(f"WARNING: Missing prepared exposure file for {trait}: {input_file}")

# Outcome
input_file = PREPARED_OUTCOME_ROOT / "endometrial_cancer_standardised.csv"
output_file = SLIM_OUTCOME_ROOT / "endometrial_cancer_standardised_slim.csv"

if input_file.exists():
    print("Creating slim file for endometrial_cancer...")
    rows = create_slim_csv(input_file, output_file)

    slim_records.append({
        "trait": TARGET_OUTCOME,
        "role": "outcome",
        "input_file": str(input_file),
        "output_file": str(output_file),
        "rows": rows,
        "size_MB": round(output_file.stat().st_size / 1024 / 1024, 2)
    })

    print(f"Saved: {output_file}")
    print(f"Rows: {rows}, Size MB: {round(output_file.stat().st_size / 1024 / 1024, 2)}")
else:
    print("WARNING: Missing prepared outcome file.")

slim_summary = pd.DataFrame(slim_records)
slim_summary_path = SUMMARY_DIR / "slim_prepared_file_summary.csv"
slim_summary.to_csv(slim_summary_path, index=False)

print("\nSlim file summary:")
display(slim_summary)
print("Saved to:", slim_summary_path)

Creating slim file for IGF1...
Saved: /content/drive/MyDrive/UM_WQF7023/MRDRP-main/backend_work/slim_prepared_exposures/IGF1/IGF1_standardised_slim.csv
Rows: 464432, Size MB: 31.92
Creating slim file for SHBG...
Saved: /content/drive/MyDrive/UM_WQF7023/MRDRP-main/backend_work/slim_prepared_exposures/SHBG/SHBG_standardised_slim.csv
Rows: 437423, Size MB: 30.09
Creating slim file for ADIPOQ...
Saved: /content/drive/MyDrive/UM_WQF7023/MRDRP-main/backend_work/slim_prepared_exposures/ADIPOQ/ADIPOQ_standardised_slim.csv
Rows: 1062500, Size MB: 61.53
Creating slim file for GDF15...
Saved: /content/drive/MyDrive/UM_WQF7023/MRDRP-main/backend_work/slim_prepared_exposures/GDF15/GDF15_standardised_slim.csv
Rows: 26372674, Size MB: 1492.9
Creating slim file for endometrial_cancer...
Saved: /content/drive/MyDrive/UM_WQF7023/MRDRP-main/backend_work/slim_prepared_outcome/endometrial_cancer_standardised_slim.csv
Rows: 70746, Size MB: 5.43

Slim file summary:

,trait,role,input_file,output_file,rows,size_MB
0,IGF1,exposure,/content/drive/MyDrive/UM_WQF7023/MRDRP-main/b...,/content/drive/MyDrive/UM_WQF7023/MRDRP-main/b...,464432,31.92
1,SHBG,exposure,/content/drive/MyDrive/UM_WQF7023/MRDRP-main/b...,/content/drive/MyDrive/UM_WQF7023/MRDRP-main/b...,437423,30.09
2,ADIPOQ,exposure,/content/drive/MyDrive/UM_WQF7023/MRDRP-main/b...,/content/drive/MyDrive/UM_WQF7023/MRDRP-main/b...,1062500,61.53
3,GDF15,exposure,/content/drive/MyDrive/UM_WQF7023/MRDRP-main/b...,/content/drive/MyDrive/UM_WQF7023/MRDRP-main/b...,26372674,1492.90
4,endometrial_cancer,outcome,/content/drive/MyDrive/UM_WQF7023/MRDRP-main/b...,/content/drive/MyDrive/UM_WQF7023/MRDRP-main/b...,70746,5.43

Saved to: /content/drive/MyDrive/UM_WQF7023/MRDRP-main/backend_work/mr_outputs/summary/slim_prepared_file_summary.csv

In [ ]:
# ============================================================
# Cell 8: Lightweight QC for slim prepared files
# ============================================================

import pandas as pd
import numpy as np
from pathlib import Path

def chunk_qc_csv(path: Path, chunksize=500000):
    if not path.exists():
        return {
            "file": str(path),
            "exists": False,
            "rows": 0,
            "unique_snps_estimated": np.nan,
            "min_p": np.nan,
            "num_p5e8": 0,
            "num_p1e5": 0,
            "size_MB": 0,
        }

    total_rows = 0
    min_p = np.inf
    num_p5e8 = 0
    num_p1e5 = 0

    # Exact unique SNP can be memory-heavy, so only estimate if file is small.
    unique_snps = set()
    collect_unique = path.stat().st_size < 500 * 1024 * 1024

    for chunk in pd.read_csv(path, chunksize=chunksize, low_memory=False):
        total_rows += len(chunk)

        if "P" in chunk.columns:
            p = pd.to_numeric(chunk["P"], errors="coerce")
            min_p = min(min_p, p.min(skipna=True))
            num_p5e8 += int((p < 5e-8).sum())
            num_p1e5 += int((p < 1e-5).sum())

        if collect_unique and "SNP" in chunk.columns:
            unique_snps.update(chunk["SNP"].dropna().astype(str).tolist())

    return {
        "file": str(path),
        "exists": True,
        "rows": total_rows,
        "unique_snps_estimated": len(unique_snps) if collect_unique else "Skipped_large_file",
        "min_p": min_p if min_p != np.inf else np.nan,
        "num_p5e8": num_p5e8,
        "num_p1e5": num_p1e5,
        "size_MB": round(path.stat().st_size / 1024 / 1024, 2),
    }

slim_files = []

for trait in TARGET_EXPOSURES:
    slim_files.append(SLIM_EXPOSURE_ROOT / trait / f"{trait}_standardised_slim.csv")

slim_files.append(SLIM_OUTCOME_ROOT / "endometrial_cancer_standardised_slim.csv")

slim_qc_records = []

for path in slim_files:
    print("QC:", path)
    slim_qc_records.append(chunk_qc_csv(path))

slim_qc_df = pd.DataFrame(slim_qc_records)
slim_qc_path = SUMMARY_DIR / "slim_prepared_file_qc.csv"
slim_qc_df.to_csv(slim_qc_path, index=False)

display(slim_qc_df)
print("Saved to:", slim_qc_path)

QC: /content/drive/MyDrive/UM_WQF7023/MRDRP-main/backend_work/slim_prepared_exposures/IGF1/IGF1_standardised_slim.csv
QC: /content/drive/MyDrive/UM_WQF7023/MRDRP-main/backend_work/slim_prepared_exposures/SHBG/SHBG_standardised_slim.csv
QC: /content/drive/MyDrive/UM_WQF7023/MRDRP-main/backend_work/slim_prepared_exposures/ADIPOQ/ADIPOQ_standardised_slim.csv
QC: /content/drive/MyDrive/UM_WQF7023/MRDRP-main/backend_work/slim_prepared_exposures/GDF15/GDF15_standardised_slim.csv
QC: /content/drive/MyDrive/UM_WQF7023/MRDRP-main/backend_work/slim_prepared_outcome/endometrial_cancer_standardised_slim.csv

,file,exists,rows,unique_snps_estimated,min_p,num_p5e8,num_p1e5,size_MB
0,/content/drive/MyDrive/UM_WQF7023/MRDRP-main/b...,True,464432,464432,1.387340e-43,47,98,31.92
1,/content/drive/MyDrive/UM_WQF7023/MRDRP-main/b...,True,437423,437423,2.225070e-307,37,75,30.09
2,/content/drive/MyDrive/UM_WQF7023/MRDRP-main/b...,True,1062500,1062204,7.251550e-07,0,8,61.53
3,/content/drive/MyDrive/UM_WQF7023/MRDRP-main/b...,True,26372674,Skipped_large_file,1.670000e-105,9105,20320,1492.90
4,/content/drive/MyDrive/UM_WQF7023/MRDRP-main/b...,True,70746,70746,1.169450e-05,0,0,5.43

Saved to: /content/drive/MyDrive/UM_WQF7023/MRDRP-main/backend_work/mr_outputs/summary/slim_prepared_file_qc.csv

In [ ]:
# ============================================================
# Cell 8.1: Review slim file QC before significant variant selection
# ============================================================

display(slim_qc_df)

print("Key checks:")

# Missing files
missing_files = slim_qc_df[slim_qc_df["exists"] == False]
if len(missing_files) > 0:
    print("WARNING: Some slim files are missing:")
    display(missing_files)
else:
    print("- All slim files exist.")

# Empty files
empty_files = slim_qc_df[slim_qc_df["rows"] <= 0]
if len(empty_files) > 0:
    print("WARNING: Some slim files are empty:")
    display(empty_files)
else:
    print("- All slim files have rows.")

# Significant variants check for exposures only
exposure_qc = slim_qc_df.iloc[:len(TARGET_EXPOSURES)].copy()

no_p5e8 = exposure_qc[exposure_qc["num_p5e8"] == 0]
if len(no_p5e8) > 0:
    print("- Some exposures have zero variants at p < 5e-8:")
    display(no_p5e8[["file", "num_p5e8", "num_p1e5", "min_p"]])
    print("  This does not stop backend testing, but strict MR may not run for those exposures.")
else:
    print("- All exposures have at least one p < 5e-8 variant.")

,file,exists,rows,unique_snps_estimated,min_p,num_p5e8,num_p1e5,size_MB
0,/content/drive/MyDrive/UM_WQF7023/MRDRP-main/b...,True,464432,464432,1.387340e-43,47,98,31.92
1,/content/drive/MyDrive/UM_WQF7023/MRDRP-main/b...,True,437423,437423,2.225070e-307,37,75,30.09
2,/content/drive/MyDrive/UM_WQF7023/MRDRP-main/b...,True,1062500,1062204,7.251550e-07,0,8,61.53
3,/content/drive/MyDrive/UM_WQF7023/MRDRP-main/b...,True,26372674,Skipped_large_file,1.670000e-105,9105,20320,1492.90
4,/content/drive/MyDrive/UM_WQF7023/MRDRP-main/b...,True,70746,70746,1.169450e-05,0,0,5.43

Key checks:
- All slim files exist.
- All slim files have rows.
- Some exposures have zero variants at p < 5e-8:

,file,num_p5e8,num_p1e5,min_p
2,/content/drive/MyDrive/UM_WQF7023/MRDRP-main/b...,0,8,7.251550e-07

  This does not stop backend testing, but strict MR may not run for those exposures.

In [ ]:
# ============================================================
# Cell 9: Chunk-based cis significant variant selection
# ============================================================

import pandas as pd
import numpy as np
import shutil
from pathlib import Path

SIG_THRESHOLD = 5e-8
CIS_WINDOW = 300000

GENE_COORDINATES_GRCH38 = {
    "IGF1":  (12, 102395874, 102481839),
    "SHBG":  (17, 7618495, 7632902),
    "ADIPOQ": (3, 186842033, 186858463),
    "GDF15": (19, 18374742, 18389181),
}

if SIG_VARIANT_ROOT.exists():
    shutil.rmtree(SIG_VARIANT_ROOT)
SIG_VARIANT_ROOT.mkdir(parents=True, exist_ok=True)

def select_cis_significant_variants_chunked(
    trait,
    input_file: Path,
    output_dir: Path,
    gene_coordinates,
    window=300000,
    p_threshold=5e-8,
    chunksize=500000
):
    chrom, start, end = gene_coordinates
    lower = start - window
    upper = end + window

    selected_chunks = []
    total_rows = 0
    cis_rows = 0
    sig_rows = 0

    print(f"\nSelecting cis significant variants for {trait}")
    print("Input:", input_file)
    print("CHR:", chrom, "Region:", lower, "-", upper)
    print("P threshold:", p_threshold)

    for chunk in pd.read_csv(input_file, chunksize=chunksize, low_memory=False):
        total_rows += len(chunk)

        chunk["CHR"] = pd.to_numeric(chunk["CHR"], errors="coerce")
        chunk["POS"] = pd.to_numeric(chunk["POS"], errors="coerce")
        chunk["P"] = pd.to_numeric(chunk["P"], errors="coerce")

        cis = chunk[
            (chunk["CHR"] == chrom)
            & (chunk["POS"] >= lower)
            & (chunk["POS"] <= upper)
        ].copy()

        cis_rows += len(cis)

        sig = cis[cis["P"] < p_threshold].copy()
        sig_rows += len(sig)

        if len(sig) > 0:
            selected_chunks.append(sig)

    if len(selected_chunks) > 0:
        out_df = pd.concat(selected_chunks, ignore_index=True)
        out_df = out_df.sort_values("P")

        output_file = output_dir / f"{trait}_full_sig_variants.csv"
        out_df.to_csv(output_file, index=False)

        print("Saved:", output_file)
        print("Total rows:", total_rows)
        print("Cis rows:", cis_rows)
        print("Significant rows:", len(out_df))

        return {
            "trait": trait,
            "input_file": str(input_file),
            "output_file": str(output_file),
            "total_rows": total_rows,
            "cis_rows": cis_rows,
            "sig_rows": len(out_df),
            "min_p": out_df["P"].min()
        }
    else:
        print("No significant cis variants found.")
        print("Total rows:", total_rows)
        print("Cis rows:", cis_rows)
        print("Significant rows:", sig_rows)

        return {
            "trait": trait,
            "input_file": str(input_file),
            "output_file": None,
            "total_rows": total_rows,
            "cis_rows": cis_rows,
            "sig_rows": 0,
            "min_p": np.nan
        }

sig_selection_records = []

for trait in TARGET_EXPOSURES:
    input_file = SLIM_EXPOSURE_ROOT / trait / f"{trait}_standardised_slim.csv"

    if not input_file.exists():
        print(f"WARNING: Missing slim file for {trait}")
        continue

    record = select_cis_significant_variants_chunked(
        trait=trait,
        input_file=input_file,
        output_dir=SIG_VARIANT_ROOT,
        gene_coordinates=GENE_COORDINATES_GRCH38[trait],
        window=CIS_WINDOW,
        p_threshold=SIG_THRESHOLD,
        chunksize=500000
    )

    sig_selection_records.append(record)

sig_selection_df = pd.DataFrame(sig_selection_records)
sig_selection_path = SUMMARY_DIR / "chunked_cis_significant_variant_selection.csv"
sig_selection_df.to_csv(sig_selection_path, index=False)

print("\nSignificant variant selection summary:")
display(sig_selection_df)
print("Saved to:", sig_selection_path)

Selecting cis significant variants for IGF1
Input: /content/drive/MyDrive/UM_WQF7023/MRDRP-main/backend_work/slim_prepared_exposures/IGF1/IGF1_standardised_slim.csv
CHR: 12 Region: 102095874 - 102781839
P threshold: 5e-08
No significant cis variants found.
Total rows: 464432
Cis rows: 52
Significant rows: 0

Selecting cis significant variants for SHBG
Input: /content/drive/MyDrive/UM_WQF7023/MRDRP-main/backend_work/slim_prepared_exposures/SHBG/SHBG_standardised_slim.csv
CHR: 17 Region: 7318495 - 7932902
P threshold: 5e-08
Saved: /content/drive/MyDrive/UM_WQF7023/MRDRP-main/backend_work/significant_variants/SHBG_full_sig_variants.csv
Total rows: 437423
Cis rows: 860
Significant rows: 8

Selecting cis significant variants for ADIPOQ
Input: /content/drive/MyDrive/UM_WQF7023/MRDRP-main/backend_work/slim_prepared_exposures/ADIPOQ/ADIPOQ_standardised_slim.csv
CHR: 3 Region: 186542033 - 187158463
P threshold: 5e-08
No significant cis variants found.
Total rows: 1062500
Cis rows: 0
Significant rows: 0

Selecting cis significant variants for GDF15
Input: /content/drive/MyDrive/UM_WQF7023/MRDRP-main/backend_work/slim_prepared_exposures/GDF15/GDF15_standardised_slim.csv
CHR: 19 Region: 18074742 - 18689181
P threshold: 5e-08
Saved: /content/drive/MyDrive/UM_WQF7023/MRDRP-main/backend_work/significant_variants/GDF15_full_sig_variants.csv
Total rows: 26372674
Cis rows: 6242
Significant rows: 81

Significant variant selection summary:

,trait,input_file,output_file,total_rows,cis_rows,sig_rows,min_p
0,IGF1,/content/drive/MyDrive/UM_WQF7023/MRDRP-main/b...,None,464432,52,0,NaN
1,SHBG,/content/drive/MyDrive/UM_WQF7023/MRDRP-main/b...,/content/drive/MyDrive/UM_WQF7023/MRDRP-main/b...,437423,860,8,2.225070e-307
2,ADIPOQ,/content/drive/MyDrive/UM_WQF7023/MRDRP-main/b...,None,1062500,0,0,NaN
3,GDF15,/content/drive/MyDrive/UM_WQF7023/MRDRP-main/b...,/content/drive/MyDrive/UM_WQF7023/MRDRP-main/b...,26372674,6242,81,1.670000e-105

Saved to: /content/drive/MyDrive/UM_WQF7023/MRDRP-main/backend_work/mr_outputs/summary/chunked_cis_significant_variant_selection.csv

In [ ]:
# ============================================================
# Cell 10: Check significant variant outputs
# ============================================================

sig_files = sorted(SIG_VARIANT_ROOT.glob("*.csv"))

sig_qc = []

for f in sig_files:
    df = pd.read_csv(f)
    sig_qc.append({
        "file": f.name,
        "rows": len(df),
        "unique_snps": df["SNP"].nunique() if "SNP" in df.columns else np.nan,
        "min_p": df["P"].min() if "P" in df.columns else np.nan,
        "max_p": df["P"].max() if "P" in df.columns else np.nan,
        "example_snp": df["SNP"].iloc[0] if len(df) > 0 else None,
    })

sig_qc_df = pd.DataFrame(sig_qc)
sig_qc_path = SUMMARY_DIR / "significant_variant_qc.csv"
sig_qc_df.to_csv(sig_qc_path, index=False)

print("Significant variant files:")
display(sig_qc_df)

if len(sig_files) == 0:
    print("WARNING: No significant variant files were generated at p < 5e-8.")
    print("For backend connectivity testing, you may try p < 1e-5 later.")
else:
    print("Significant variant QC saved to:", sig_qc_path)

Significant variant files:

,file,rows,unique_snps,min_p,max_p,example_snp
0,GDF15_full_sig_variants.csv,81,81,1.670000e-105,3.207000e-08,19:18388639:T:G
1,SHBG_full_sig_variants.csv,8,8,2.225070e-307,4.438210e-09,17:7631360:T:C

Significant variant QC saved to: /content/drive/MyDrive/UM_WQF7023/MRDRP-main/backend_work/mr_outputs/summary/significant_variant_qc.csv

In [ ]:
# ============================================================
# Cell 11: Prepare coordinate-based MR input
# ============================================================

import pandas as pd
import numpy as np
import shutil
from pathlib import Path

MR_READY_SIG_ROOT = BACKEND_ROOT / "mr_ready_significant_variants"
MR_READY_OUTCOME_ROOT = BACKEND_ROOT / "mr_ready_outcome"

if MR_READY_SIG_ROOT.exists():
    shutil.rmtree(MR_READY_SIG_ROOT)
if MR_READY_OUTCOME_ROOT.exists():
    shutil.rmtree(MR_READY_OUTCOME_ROOT)

MR_READY_SIG_ROOT.mkdir(parents=True, exist_ok=True)
MR_READY_OUTCOME_ROOT.mkdir(parents=True, exist_ok=True)

def make_coord_snp_id(df):
    """
    Use CHR:POS as the variant matching key.
    This is safer than CHR:POS:EA:OA when exposure/outcome alleles may be reversed.
    """
    chr_clean = pd.to_numeric(df["CHR"], errors="coerce").astype("Int64").astype(str)
    pos_clean = pd.to_numeric(df["POS"], errors="coerce").astype("Int64").astype(str)
    return chr_clean + ":" + pos_clean

def prepare_mr_ready_exposure_file(input_file: Path, output_file: Path):
    df = pd.read_csv(input_file)

    df["original_SNP"] = df["SNP"].astype(str)
    df["SNP"] = make_coord_snp_id(df)

    # Keep MR-required columns
    keep_cols = ["SNP", "CHR", "POS", "EA", "OA", "BETA", "SE", "EAF", "P", "N", "original_SNP"]
    available_cols = [c for c in keep_cols if c in df.columns]
    df = df[available_cols].copy()

    # Basic cleaning
    df = df.replace([np.inf, -np.inf], np.nan)
    df = df.dropna(subset=["SNP", "EA", "OA", "BETA", "SE", "P"])
    df = df.drop_duplicates(subset=["SNP"], keep="first")

    output_file.parent.mkdir(parents=True, exist_ok=True)
    df.to_csv(output_file, index=False)

    return {
        "input_file": str(input_file),
        "output_file": str(output_file),
        "rows": len(df),
        "min_p": df["P"].min() if len(df) > 0 else np.nan,
        "example_snp": df["SNP"].iloc[0] if len(df) > 0 else None,
    }

mr_ready_exposure_records = []

sig_files = sorted(SIG_VARIANT_ROOT.glob("*.csv"))

for sig_file in sig_files:
    trait = sig_file.name.replace("_full_sig_variants.csv", "")
    output_file = MR_READY_SIG_ROOT / f"{trait}_mr_ready_sig_variants.csv"

    record = prepare_mr_ready_exposure_file(sig_file, output_file)
    record["trait"] = trait
    mr_ready_exposure_records.append(record)

mr_ready_exposure_df = pd.DataFrame(mr_ready_exposure_records)

print("MR-ready exposure significant variant files:")
display(mr_ready_exposure_df)

mr_ready_exposure_summary_path = SUMMARY_DIR / "mr_ready_exposure_sig_variant_summary.csv"
mr_ready_exposure_df.to_csv(mr_ready_exposure_summary_path, index=False)

print("Saved to:", mr_ready_exposure_summary_path)

MR-ready exposure significant variant files:

,input_file,output_file,rows,min_p,example_snp,trait
0,/content/drive/MyDrive/UM_WQF7023/MRDRP-main/b...,/content/drive/MyDrive/UM_WQF7023/MRDRP-main/b...,81,1.670000e-105,19:18388639,GDF15
1,/content/drive/MyDrive/UM_WQF7023/MRDRP-main/b...,/content/drive/MyDrive/UM_WQF7023/MRDRP-main/b...,8,2.225070e-307,17:7631360,SHBG

Saved to: /content/drive/MyDrive/UM_WQF7023/MRDRP-main/backend_work/mr_outputs/summary/mr_ready_exposure_sig_variant_summary.csv

In [ ]:
# ============================================================
# Cell 12.0
# Recovery cell: Define slim and MR-ready folders
# Run this before Cell 12
# ============================================================

from pathlib import Path

PROJECT_ROOT = Path("/content/drive/MyDrive/UM_WQF7023/MRDRP-main")
BACKEND_ROOT = PROJECT_ROOT / "backend_work"

MR_OUTPUT_ROOT = BACKEND_ROOT / "mr_outputs"
SUMMARY_DIR = MR_OUTPUT_ROOT / "summary"

PREPARED_EXPOSURE_ROOT = BACKEND_ROOT / "prepared_exposures"
PREPARED_OUTCOME_ROOT = BACKEND_ROOT / "prepared_outcome"

SLIM_EXPOSURE_ROOT = BACKEND_ROOT / "slim_prepared_exposures"
SLIM_OUTCOME_ROOT = BACKEND_ROOT / "slim_prepared_outcome"

SIG_VARIANT_ROOT = BACKEND_ROOT / "significant_variants"
MR_READY_SIG_ROOT = BACKEND_ROOT / "mr_ready_significant_variants"
MR_READY_OUTCOME_ROOT = BACKEND_ROOT / "mr_ready_outcome"

for folder in [
    MR_OUTPUT_ROOT,
    SUMMARY_DIR,
    PREPARED_EXPOSURE_ROOT,
    PREPARED_OUTCOME_ROOT,
    SLIM_EXPOSURE_ROOT,
    SLIM_OUTCOME_ROOT,
    SIG_VARIANT_ROOT,
    MR_READY_SIG_ROOT,
    MR_READY_OUTCOME_ROOT,
]:
    folder.mkdir(parents=True, exist_ok=True)

print("Recovered backend folder variables.")
print("SLIM_OUTCOME_ROOT:", SLIM_OUTCOME_ROOT)
print("MR_READY_OUTCOME_ROOT:", MR_READY_OUTCOME_ROOT)

# Check whether expected files exist
expected_files = [
    SLIM_OUTCOME_ROOT / "endometrial_cancer_standardised_slim.csv",
    MR_READY_SIG_ROOT / "GDF15_mr_ready_sig_variants.csv",
    MR_READY_SIG_ROOT / "SHBG_mr_ready_sig_variants.csv",
    SIG_VARIANT_ROOT / "GDF15_full_sig_variants.csv",
    SIG_VARIANT_ROOT / "SHBG_full_sig_variants.csv",
]

print("\nExpected file check:")
for f in expected_files:
    print(f.exists(), f)

Recovered backend folder variables.
SLIM_OUTCOME_ROOT: /content/drive/MyDrive/UM_WQF7023/MRDRP-main/backend_work/slim_prepared_outcome
MR_READY_OUTCOME_ROOT: /content/drive/MyDrive/UM_WQF7023/MRDRP-main/backend_work/mr_ready_outcome

Expected file check:
True /content/drive/MyDrive/UM_WQF7023/MRDRP-main/backend_work/slim_prepared_outcome/endometrial_cancer_standardised_slim.csv
True /content/drive/MyDrive/UM_WQF7023/MRDRP-main/backend_work/mr_ready_significant_variants/GDF15_mr_ready_sig_variants.csv
True /content/drive/MyDrive/UM_WQF7023/MRDRP-main/backend_work/mr_ready_significant_variants/SHBG_mr_ready_sig_variants.csv
True /content/drive/MyDrive/UM_WQF7023/MRDRP-main/backend_work/significant_variants/GDF15_full_sig_variants.csv
True /content/drive/MyDrive/UM_WQF7023/MRDRP-main/backend_work/significant_variants/SHBG_full_sig_variants.csv

In [ ]:
# ============================================================
# Cell 12: Prepare coordinate-based outcome file
# ============================================================

def prepare_mr_ready_outcome_file(input_file: Path, output_file: Path, chunksize=500000):
    output_file.parent.mkdir(parents=True, exist_ok=True)

    first_chunk = True
    total_rows = 0

    for chunk in pd.read_csv(input_file, chunksize=chunksize, low_memory=False):
        chunk["original_SNP"] = chunk["SNP"].astype(str)
        chunk["SNP"] = make_coord_snp_id(chunk)

        keep_cols = ["SNP", "CHR", "POS", "EA", "OA", "BETA", "SE", "EAF", "P", "N", "original_SNP"]
        available_cols = [c for c in keep_cols if c in chunk.columns]
        out = chunk[available_cols].copy()

        out = out.replace([np.inf, -np.inf], np.nan)
        out = out.dropna(subset=["SNP", "EA", "OA", "BETA", "SE", "P"])

        out.to_csv(
            output_file,
            index=False,
            mode="w" if first_chunk else "a",
            header=first_chunk
        )

        total_rows += len(out)
        first_chunk = False

    return total_rows

outcome_slim_file = SLIM_OUTCOME_ROOT / "endometrial_cancer_standardised_slim.csv"
mr_ready_outcome_file = MR_READY_OUTCOME_ROOT / "endometrial_cancer_mr_ready.csv"

rows = prepare_mr_ready_outcome_file(
    input_file=outcome_slim_file,
    output_file=mr_ready_outcome_file,
    chunksize=500000
)

print("MR-ready outcome file created:")
print("Path:", mr_ready_outcome_file)
print("Rows:", rows)
print("Size MB:", round(mr_ready_outcome_file.stat().st_size / 1024 / 1024, 2))

MR-ready outcome file created:
Path: /content/drive/MyDrive/UM_WQF7023/MRDRP-main/backend_work/mr_ready_outcome/endometrial_cancer_mr_ready.csv
Rows: 70746
Size MB: 6.21

In [ ]:
# ============================================================
# Cell 13: Check exposure-outcome SNP overlap
# ============================================================

def load_snp_set_from_csv(path: Path, snp_col="SNP", chunksize=500000):
    snps = set()

    for chunk in pd.read_csv(path, usecols=[snp_col], chunksize=chunksize):
        snps.update(chunk[snp_col].dropna().astype(str).tolist())

    return snps

outcome_snps = load_snp_set_from_csv(mr_ready_outcome_file)

overlap_records = []

for _, row in mr_ready_exposure_df.iterrows():
    trait = row["trait"]
    exp_file = Path(row["output_file"])

    exp_df = pd.read_csv(exp_file)
    exp_snps = set(exp_df["SNP"].dropna().astype(str).tolist())

    overlap = sorted(list(exp_snps.intersection(outcome_snps)))

    overlap_records.append({
        "trait": trait,
        "exposure_snps": len(exp_snps),
        "outcome_snps": len(outcome_snps),
        "overlap_snps": len(overlap),
        "example_overlap": overlap[0] if len(overlap) > 0 else None,
    })

overlap_df = pd.DataFrame(overlap_records)

overlap_path = SUMMARY_DIR / "exposure_outcome_snp_overlap.csv"
overlap_df.to_csv(overlap_path, index=False)

print("Exposure-outcome SNP overlap:")
display(overlap_df)
print("Saved to:", overlap_path)

Exposure-outcome SNP overlap:

   trait  exposure_snps  outcome_snps  overlap_snps example_overlap
0  GDF15             81         70453             2     19:18264536
1   SHBG              8         70453             5      17:7387376

Saved to: /content/drive/MyDrive/UM_WQF7023/MRDRP-main/backend_work/mr_outputs/summary/exposure_outcome_snp_overlap.csv

In [ ]:
# ============================================================
# Cell 14: Import R packages for MR analysis
# ============================================================

import rpy2.robjects as robjects
from rpy2.robjects.packages import importr
from rpy2.robjects import pandas2ri
from rpy2.rinterface_lib.embedded import RRuntimeError

pandas2ri.activate()

TwoSampleMR = importr("TwoSampleMR")
grdevices = importr("grDevices")

rprint = robjects.r("function(x, ...) print(x)")

def r_to_pandas(r_obj):
    with (robjects.default_converter + pandas2ri.converter).context():
        return robjects.conversion.get_conversion().rpy2py(r_obj)

print("TwoSampleMR imported successfully through rpy2.")

TwoSampleMR imported successfully through rpy2.

In [ ]:
# ============================================================
# Cell 15: Run coordinate-based MR without LD clumping
# ============================================================

MR_COORD_OUTPUT_ROOT = MR_OUTPUT_ROOT / "coordinate_based_no_ld_clump"

COORD_RESULTS_DIR = MR_COORD_OUTPUT_ROOT / "results"
COORD_HARMONISED_DIR = MR_COORD_OUTPUT_ROOT / "harmonised_data"
COORD_PLEIOTROPY_DIR = MR_COORD_OUTPUT_ROOT / "pleiotropy"
COORD_HETEROGENEITY_DIR = MR_COORD_OUTPUT_ROOT / "heterogeneity"
COORD_SCATTER_DIR = MR_COORD_OUTPUT_ROOT / "scatter_plots"
COORD_SINGLE_SNP_DIR = MR_COORD_OUTPUT_ROOT / "singleSNP_plots"

for folder in [
    COORD_RESULTS_DIR,
    COORD_HARMONISED_DIR,
    COORD_PLEIOTROPY_DIR,
    COORD_HETEROGENEITY_DIR,
    COORD_SCATTER_DIR,
    COORD_SINGLE_SNP_DIR,
]:
    folder.mkdir(parents=True, exist_ok=True)

mr_run_records = []
mr_result_tables = []

for _, row in mr_ready_exposure_df.iterrows():
    trait = row["trait"]
    exp_file = Path(row["output_file"])

    print("\n" + "=" * 100)
    print("Running MR for:", trait)
    print("Exposure file:", exp_file)
    print("Outcome file:", mr_ready_outcome_file)

    try:
        # Read exposure significant variants
        exp_dat = TwoSampleMR.read_exposure_data(
            filename=str(exp_file),
            sep=",",
            snp_col="SNP",
            beta_col="BETA",
            se_col="SE",
            effect_allele_col="EA",
            other_allele_col="OA",
            eaf_col="EAF",
            pval_col="P",
            samplesize_col="N",
            chr_col="CHR",
            pos_col="POS",
            clump=False
        )

        exp_df = pd.read_csv(exp_file)
        snp_list = robjects.StrVector(exp_df["SNP"].dropna().astype(str).tolist())

        # Read matching outcome rows
        outcome_dat = TwoSampleMR.read_outcome_data(
            snps=snp_list,
            filename=str(mr_ready_outcome_file),
            sep=",",
            snp_col="SNP",
            beta_col="BETA",
            se_col="SE",
            effect_allele_col="EA",
            other_allele_col="OA",
            eaf_col="EAF",
            pval_col="P"
        )

        # Harmonise
        harmonised = TwoSampleMR.harmonise_data(exp_dat, outcome_dat)
        harmonised_py = r_to_pandas(harmonised)

        print("Harmonised SNP count:", len(harmonised_py))

        if len(harmonised_py) == 0:
            raise ValueError("No SNPs retained after harmonisation.")

        # Run MR
        res = TwoSampleMR.mr(harmonised)
        res_py = r_to_pandas(res)

        # Sensitivity tests
        try:
            pleiotropy = TwoSampleMR.mr_pleiotropy_test(harmonised)
            pleiotropy_py = r_to_pandas(pleiotropy)
        except Exception as e:
            pleiotropy_py = pd.DataFrame({"warning": [str(e)]})

        try:
            heterogeneity = TwoSampleMR.mr_heterogeneity(harmonised)
            heterogeneity_py = r_to_pandas(heterogeneity)
        except Exception as e:
            heterogeneity_py = pd.DataFrame({"warning": [str(e)]})

        # Single SNP
        try:
            single_snp = TwoSampleMR.mr_singlesnp(harmonised)
        except Exception as e:
            single_snp = None
            print("Single-SNP warning:", e)

        # Save tables
        res_py.to_csv(COORD_RESULTS_DIR / f"{trait}.csv", index=False)
        harmonised_py.to_csv(COORD_HARMONISED_DIR / f"{trait}.csv", index=False)
        pleiotropy_py.to_csv(COORD_PLEIOTROPY_DIR / f"{trait}.csv", index=False)
        heterogeneity_py.to_csv(COORD_HETEROGENEITY_DIR / f"{trait}.csv", index=False)

        # Save scatter plot
        try:
            scatter_plot = TwoSampleMR.mr_scatter_plot(res, harmonised)
            grdevices.png(
                file=str(COORD_SCATTER_DIR / f"{trait}_scatter.png"),
                width=1000,
                height=850
            )
            rprint(scatter_plot)
            grdevices.dev_off()
        except Exception as e:
            print("Scatter plot warning:", e)

        # Save single SNP plot
        if single_snp is not None:
            try:
                forest_plot = TwoSampleMR.mr_forest_plot(single_snp)
                grdevices.png(
                    file=str(COORD_SINGLE_SNP_DIR / f"{trait}_singleSNP.png"),
                    width=1000,
                    height=850
                )
                rprint(forest_plot)
                grdevices.dev_off()
            except Exception as e:
                print("Single-SNP plot warning:", e)

        res_py["trait"] = trait
        mr_result_tables.append(res_py)

        mr_run_records.append({
            "trait": trait,
            "status": "success",
            "harmonised_snps": len(harmonised_py),
            "result_rows": len(res_py),
            "error": None
        })

        print("MR result:")
        display(res_py)

    except Exception as e:
        print("ERROR:", e)

        mr_run_records.append({
            "trait": trait,
            "status": "failed",
            "harmonised_snps": 0,
            "result_rows": 0,
            "error": str(e)
        })

mr_run_summary = pd.DataFrame(mr_run_records)
mr_run_summary_path = SUMMARY_DIR / "coordinate_based_mr_run_summary.csv"
mr_run_summary.to_csv(mr_run_summary_path, index=False)

print("\nMR run summary:")
display(mr_run_summary)
print("Saved to:", mr_run_summary_path)

WARNING:rpy2.rinterface_lib.callbacks:R[write to console]: No phenotype name specified, defaulting to 'exposure'.

WARNING:rpy2.rinterface_lib.callbacks:R[write to console]: No phenotype name specified, defaulting to 'outcome'.

====================================================================================================
Running MR for: GDF15
Exposure file: /content/drive/MyDrive/UM_WQF7023/MRDRP-main/backend_work/mr_ready_significant_variants/GDF15_mr_ready_sig_variants.csv
Outcome file: /content/drive/MyDrive/UM_WQF7023/MRDRP-main/backend_work/mr_ready_outcome/endometrial_cancer_mr_ready.csv

WARNING:rpy2.rinterface_lib.callbacks:R[write to console]: Harmonising exposure (sFtvLK) and outcome (OMEknY)

WARNING:rpy2.rinterface_lib.callbacks:R[write to console]: Analysing 'sFtvLK' on 'OMEknY'

Harmonised SNP count: 2
$sFtvLK.OMEknY

[[1]]

MR result:

,id.exposure,id.outcome,outcome,exposure,method,nsnp,b,se,pval,trait
1,sFtvLK,OMEknY,outcome,exposure,Inverse variance weighted,2.0,-0.704855,0.40822,0.084229,GDF15

WARNING:rpy2.rinterface_lib.callbacks:R[write to console]: No phenotype name specified, defaulting to 'exposure'.

====================================================================================================
Running MR for: SHBG
Exposure file: /content/drive/MyDrive/UM_WQF7023/MRDRP-main/backend_work/mr_ready_significant_variants/SHBG_mr_ready_sig_variants.csv
Outcome file: /content/drive/MyDrive/UM_WQF7023/MRDRP-main/backend_work/mr_ready_outcome/endometrial_cancer_mr_ready.csv

WARNING:rpy2.rinterface_lib.callbacks:R[write to console]: No phenotype name specified, defaulting to 'outcome'.

WARNING:rpy2.rinterface_lib.callbacks:R[write to console]: Harmonising exposure (D0KulX) and outcome (hEfA5r)

Harmonised SNP count: 5

WARNING:rpy2.rinterface_lib.callbacks:R[write to console]: Analysing 'D0KulX' on 'hEfA5r'

$D0KulX.hEfA5r

[[1]]

MR result:

,id.exposure,id.outcome,outcome,exposure,method,nsnp,b,se,pval,trait
1,D0KulX,hEfA5r,outcome,exposure,MR Egger,5.0,0.149544,0.220549,0.546353,SHBG
2,D0KulX,hEfA5r,outcome,exposure,Weighted median,5.0,0.198280,0.202096,0.326535,SHBG
3,D0KulX,hEfA5r,outcome,exposure,Inverse variance weighted,5.0,0.216414,0.203990,0.288733,SHBG
4,D0KulX,hEfA5r,outcome,exposure,Simple mode,5.0,0.926519,1.748123,0.624162,SHBG
5,D0KulX,hEfA5r,outcome,exposure,Weighted mode,5.0,0.199689,2.185189,0.931582,SHBG

MR run summary:

   trait   status  harmonised_snps  result_rows error
0  GDF15  success                2            1  None
1   SHBG  success                5            5  None

Saved to: /content/drive/MyDrive/UM_WQF7023/MRDRP-main/backend_work/mr_outputs/summary/coordinate_based_mr_run_summary.csv

In [ ]:
# ============================================================
# Cell 16: Combine coordinate-based MR results
# ============================================================

if len(mr_result_tables) > 0:
    combined_coord_mr_results = pd.concat(mr_result_tables, ignore_index=True)

    # Add OR interpretation
    if "b" in combined_coord_mr_results.columns:
        combined_coord_mr_results["MR_OR"] = np.exp(combined_coord_mr_results["b"])

    if "b" in combined_coord_mr_results.columns and "se" in combined_coord_mr_results.columns:
        combined_coord_mr_results["MR_OR_lower_95CI"] = np.exp(
            combined_coord_mr_results["b"] - 1.96 * combined_coord_mr_results["se"]
        )
        combined_coord_mr_results["MR_OR_upper_95CI"] = np.exp(
            combined_coord_mr_results["b"] + 1.96 * combined_coord_mr_results["se"]
        )

    if "pval" in combined_coord_mr_results.columns:
        combined_coord_mr_results["nominal_significant"] = combined_coord_mr_results["pval"] < 0.05

    combined_coord_results_path = SUMMARY_DIR / "coordinate_based_combined_mr_results.csv"
    combined_coord_mr_results.to_csv(combined_coord_results_path, index=False)

    print("Combined coordinate-based MR results:")
    display(combined_coord_mr_results)
    print("Saved to:", combined_coord_results_path)

else:
    print("No MR result tables were generated.")

Combined coordinate-based MR results:

,id.exposure,id.outcome,outcome,exposure,method,nsnp,b,se,pval,trait,MR_OR,MR_OR_lower_95CI,MR_OR_upper_95CI,nominal_significant
0,sFtvLK,OMEknY,outcome,exposure,Inverse variance weighted,2.0,-0.704855,0.408220,0.084229,GDF15,0.494180,0.222025,1.099940,False
1,D0KulX,hEfA5r,outcome,exposure,MR Egger,5.0,0.149544,0.220549,0.546353,SHBG,1.161305,0.753721,1.789293,False
2,D0KulX,hEfA5r,outcome,exposure,Weighted median,5.0,0.198280,0.202096,0.326535,SHBG,1.219304,0.820510,1.811924,False
3,D0KulX,hEfA5r,outcome,exposure,Inverse variance weighted,5.0,0.216414,0.203990,0.288733,SHBG,1.241617,0.832430,1.851942,False
4,D0KulX,hEfA5r,outcome,exposure,Simple mode,5.0,0.926519,1.748123,0.624162,SHBG,2.525703,0.082101,77.698828,False
5,D0KulX,hEfA5r,outcome,exposure,Weighted mode,5.0,0.199689,2.185189,0.931582,SHBG,1.221023,0.016852,88.469651,False

Saved to: /content/drive/MyDrive/UM_WQF7023/MRDRP-main/backend_work/mr_outputs/summary/coordinate_based_combined_mr_results.csv

In [ ]:
# ============================================================
# Cell 17: Generate backend MR status report
# ============================================================

from datetime import datetime

report_lines = []

report_lines.append("# Backend MR Status Report")
report_lines.append("")
report_lines.append(f"Run time: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
report_lines.append("")

report_lines.append("## Target analysis setting")
report_lines.append("")
report_lines.append("Exposures:")
for trait in TARGET_EXPOSURES:
    report_lines.append(f"- {trait}")
report_lines.append("")
report_lines.append(f"Outcome: {TARGET_OUTCOME}")
report_lines.append("")

report_lines.append("## Significant variant selection")
report_lines.append("")
if "sig_qc_df" in globals() and len(sig_qc_df) > 0:
    report_lines.append(sig_qc_df.to_markdown(index=False))
else:
    report_lines.append("No significant variants were generated at the selected threshold.")
report_lines.append("")

report_lines.append("## Important backend note")
report_lines.append("")
report_lines.append(
    "At p < 5e-8, cis significant variants were detected for GDF15 and SHBG only. "
    "IGF1 and ADIPOQ did not generate significant variant files under the strict threshold. "
    "The current available variants use coordinate-based identifiers rather than standard rsID for some files. "
    "Therefore, the current MR run uses coordinate-based SNP matching and skips formal LD clumping. "
    "This is suitable for backend connectivity testing and prototype result generation, but formal MR should later use rsID-based files or rsID mapping for proper LD clumping."
)
report_lines.append("")

report_lines.append("## SNP overlap")
report_lines.append("")
if "overlap_df" in globals():
    report_lines.append(overlap_df.to_markdown(index=False))
else:
    report_lines.append("SNP overlap table not available.")
report_lines.append("")

report_lines.append("## MR run summary")
report_lines.append("")
if "mr_run_summary" in globals():
    report_lines.append(mr_run_summary.to_markdown(index=False))
else:
    report_lines.append("MR run summary not available.")
report_lines.append("")

report_lines.append("## Combined MR results")
report_lines.append("")
if "combined_coord_mr_results" in globals() and len(combined_coord_mr_results) > 0:
    report_lines.append(combined_coord_mr_results.to_markdown(index=False))
else:
    report_lines.append("No combined MR results available.")
report_lines.append("")

backend_report_text = "\n".join(report_lines)

backend_report_path = SUMMARY_DIR / "backend_mr_status_report.md"

with open(backend_report_path, "w", encoding="utf-8") as f:
    f.write(backend_report_text)

print("Backend MR status report saved to:", backend_report_path)
print("\nPreview:")
print(backend_report_text[:3000])

Backend MR status report saved to: /content/drive/MyDrive/UM_WQF7023/MRDRP-main/backend_work/mr_outputs/summary/backend_mr_status_report.md

Preview:
# Backend MR Status Report

Run time: 2026-05-13 08:18:08

## Target analysis setting

Exposures:
- IGF1
- SHBG
- ADIPOQ
- GDF15

Outcome: endometrial_cancer

## Significant variant selection

| file                        |   rows |   unique_snps |        min_p |       max_p | example_snp     |
|:----------------------------|-------:|--------------:|-------------:|------------:|:----------------|
| GDF15_full_sig_variants.csv |     81 |            81 | 1.67e-105    | 3.207e-08   | 19:18388639:T:G |
| SHBG_full_sig_variants.csv  |      8 |             8 | 2.22507e-307 | 4.43821e-09 | 17:7631360:T:C  |

## Important backend note

At p < 5e-8, cis significant variants were detected for GDF15 and SHBG only. IGF1 and ADIPOQ did not generate significant variant files under the strict threshold. The current available variants use coordinate-based identifiers rather than standard rsID for some files. Therefore, the current MR run uses coordinate-based SNP matching and skips formal LD clumping. This is suitable for backend connectivity testing and prototype result generation, but formal MR should later use rsID-based files or rsID mapping for proper LD clumping.

## SNP overlap

| trait   |   exposure_snps |   outcome_snps |   overlap_snps | example_overlap   |
|:--------|----------------:|---------------:|---------------:|:------------------|
| GDF15   |              81 |          70453 |              2 | 19:18264536       |
| SHBG    |               8 |          70453 |              5 | 17:7387376        |

## MR run summary

| trait   | status   |   harmonised_snps |   result_rows | error   |
|:--------|:---------|------------------:|--------------:|:--------|
| GDF15   | success  |                 2 |             1 |         |
| SHBG    | success  |                 5 |             5 |         |

## Combined MR results

| id.exposure   | id.outcome   | outcome   | exposure   | method                    |   nsnp |         b |       se |      pval | trait   |   MR_OR |   MR_OR_lower_95CI |   MR_OR_upper_95CI | nominal_significant   |
|:--------------|:-------------|:----------|:-----------|:--------------------------|-------:|----------:|---------:|----------:|:--------|--------:|-------------------:|-------------------:|:----------------------|
| sFtvLK        | OMEknY       | outcome   | exposure   | Inverse variance weighted |      2 | -0.704855 | 0.40822  | 0.0842295 | GDF15   | 0.49418 |          0.222025  |            1.09994 | False                 |
| D0KulX        | hEfA5r       | outcome   | exposure   | MR Egger                  |      5 |  0.149544 | 0.220549 | 0.546353  | SHBG    | 1.1613  |          0.753721  |            1.78929 | False                 |
| D0KulX        | hEfA5r       | outcome   | exposure   | Weighted median           |      5 |  0.19828  | 0.202096 | 0.326535  | SHBG    | 1.2193  |          0.82051   |            1.81192 | False                 |
| D0KulX        | hEfA5r       | outcome   | exposure   | Inverse varianc

In [ ]:
# ============================================================
# Cell 18: Prepare multiple outcome files for comparison
# ============================================================

import pandas as pd
import numpy as np
import shutil
from pathlib import Path

OUTCOME_COMPARE_ROOT = MR_OUTPUT_ROOT / "outcome_comparison"
OUTCOME_COMPARE_PREPARED_ROOT = OUTCOME_COMPARE_ROOT / "prepared_outcomes"
OUTCOME_COMPARE_MR_READY_ROOT = OUTCOME_COMPARE_ROOT / "mr_ready_outcomes"

for folder in [
    OUTCOME_COMPARE_ROOT,
    OUTCOME_COMPARE_PREPARED_ROOT,
    OUTCOME_COMPARE_MR_READY_ROOT,
]:
    folder.mkdir(parents=True, exist_ok=True)

def prepare_single_outcome_for_comparison(set_info):
    set_name = set_info["set_name"]
    outcome_input_file = Path(set_info["outcome_file"])

    print("\n" + "=" * 100)
    print("Preparing outcome set:", set_name)
    print("Outcome file:", outcome_input_file)

    prepared_output_file = OUTCOME_COMPARE_PREPARED_ROOT / set_name / "endometrial_cancer_standardised.csv"
    mr_ready_output_file = OUTCOME_COMPARE_MR_READY_ROOT / set_name / "endometrial_cancer_mr_ready.csv"

    # Standardise outcome file.
    # This uses your existing standardise_gwas_file function.
    record = standardise_gwas_file(
        input_path=outcome_input_file,
        output_path=prepared_output_file,
        trait=TARGET_OUTCOME,
        role="outcome",
        force_binary_outcome_or_to_beta=True
    )

    # Convert to coordinate-based MR-ready outcome file.
    rows = prepare_mr_ready_outcome_file(
        input_file=prepared_output_file,
        output_file=mr_ready_output_file,
        chunksize=500000
    )

    return {
        "set_name": set_name,
        "outcome_file": str(outcome_input_file),
        "prepared_outcome_file": str(prepared_output_file),
        "mr_ready_outcome_file": str(mr_ready_output_file),
        "rows_saved": record.get("rows_saved", None),
        "effect_size_type": record.get("effect_size_type", None),
        "snp_source_type": record.get("snp_source_type", None),
        "build": record.get("build", None),
        "mr_ready_rows": rows,
        "status": "prepared",
        "error": None,
    }

multi_outcome_prepare_records = []

for set_info in MULTI_OUTCOME_ANALYSIS_SETS:
    try:
        record = prepare_single_outcome_for_comparison(set_info)
        multi_outcome_prepare_records.append(record)
    except Exception as e:
        print("ERROR:", e)
        multi_outcome_prepare_records.append({
            "set_name": set_info["set_name"],
            "outcome_file": set_info["outcome_file"],
            "prepared_outcome_file": None,
            "mr_ready_outcome_file": None,
            "rows_saved": 0,
            "effect_size_type": None,
            "snp_source_type": None,
            "build": set_info.get("outcome_build", None),
            "mr_ready_rows": 0,
            "status": "failed",
            "error": str(e),
        })

multi_outcome_prepare_df = pd.DataFrame(multi_outcome_prepare_records)

multi_outcome_prepare_path = SUMMARY_DIR / "multi_outcome_prepare_summary.csv"
multi_outcome_prepare_df.to_csv(multi_outcome_prepare_path, index=False)

print("\nMulti-outcome preparation summary:")
display(multi_outcome_prepare_df)
print("Saved to:", multi_outcome_prepare_path)

====================================================================================================
Preparing outcome set: Artesunate_EndometrialCancer_GRCh38_OutcomeCompare_01
Outcome file: /content/drive/MyDrive/UM_WQF7023/MRDRP-main/outcome/endometrial_cancer/GCST90077633_buildGRCh38.tsv.gz

Processing outcome: endometrial_cancer
Input: /content/drive/MyDrive/UM_WQF7023/MRDRP-main/outcome/endometrial_cancer/GCST90077633_buildGRCh38.tsv.gz
Detected columns:
  SNP: None
  CHR: chromosome
  POS: base_pair_location
  EA: effect_allele
  OA: other_allele
  BETA: None
  OR: odds_ratio
  SE: standard_error
  EAF: effect_allele_frequency
  P: p_value
  N: None
WARNING: No rsID/SNP column detected. Creating pseudo SNP ID using CHR:POS:EA:OA.

/usr/local/lib/python3.12/dist-packages/pandas/core/arraylike.py:399: RuntimeWarning: divide by zero encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)
/usr/local/lib/python3.12/dist-packages/pandas/core/arraylike.py:399: RuntimeWarning: divide by zero encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)

Output: /content/drive/MyDrive/UM_WQF7023/MRDRP-main/backend_work/mr_outputs/outcome_comparison/prepared_outcomes/Artesunate_EndometrialCancer_GRCh38_OutcomeCompare_01/endometrial_cancer_standardised.csv
Rows saved: 70746
Effect size type: odds_ratio_converted_to_beta
SNP source type: pseudo_chr_pos_allele_id
Build inferred: GRCh38
NOTE: This file does not have real rsID. The pseudo SNP ID can help preprocessing continue, but formal LD clumping/MR may require rsID-based files.

====================================================================================================
Preparing outcome set: Artesunate_EndometrialCancer_GRCh38_OutcomeCompare_02
Outcome file: /content/drive/MyDrive/UM_WQF7023/MRDRP-main/outcome/endometrial_cancer/GCST90079109_buildGRCh38.tsv.gz

Processing outcome: endometrial_cancer
Input: /content/drive/MyDrive/UM_WQF7023/MRDRP-main/outcome/endometrial_cancer/GCST90079109_buildGRCh38.tsv.gz
Detected columns:
  SNP: None
  CHR: chromosome
  POS: base_pair_location
  EA: effect_allele
  OA: other_allele
  BETA: None
  OR: odds_ratio
  SE: standard_error
  EAF: effect_allele_frequency
  P: p_value
  N: None
WARNING: No rsID/SNP column detected. Creating pseudo SNP ID using CHR:POS:EA:OA.
Output: /content/drive/MyDrive/UM_WQF7023/MRDRP-main/backend_work/mr_outputs/outcome_comparison/prepared_outcomes/Artesunate_EndometrialCancer_GRCh38_OutcomeCompare_02/endometrial_cancer_standardised.csv
Rows saved: 73088
Effect size type: odds_ratio_converted_to_beta
SNP source type: pseudo_chr_pos_allele_id
Build inferred: GRCh38
NOTE: This file does not have real rsID. The pseudo SNP ID can help preprocessing continue, but formal LD clumping/MR may require rsID-based files.

====================================================================================================
Preparing outcome set: Artesunate_EndometrialCancer_GRCh38_OutcomeCompare_03
Outcome file: /content/drive/MyDrive/UM_WQF7023/MRDRP-main/outcome/endometrial_cancer/GCST90079607_buildGRCh38.tsv.gz

Processing outcome: endometrial_cancer
Input: /content/drive/MyDrive/UM_WQF7023/MRDRP-main/outcome/endometrial_cancer/GCST90079607_buildGRCh38.tsv.gz
Detected columns:
  SNP: None
  CHR: chromosome
  POS: base_pair_location
  EA: effect_allele
  OA: other_allele
  BETA: None
  OR: odds_ratio
  SE: standard_error
  EAF: effect_allele_frequency
  P: p_value
  N: None
WARNING: No rsID/SNP column detected. Creating pseudo SNP ID using CHR:POS:EA:OA.
Output: /content/drive/MyDrive/UM_WQF7023/MRDRP-main/backend_work/mr_outputs/outcome_comparison/prepared_outcomes/Artesunate_EndometrialCancer_GRCh38_OutcomeCompare_03/endometrial_cancer_standardised.csv
Rows saved: 308476
Effect size type: odds_ratio_converted_to_beta
SNP source type: pseudo_chr_pos_allele_id
Build inferred: GRCh38
NOTE: This file does not have real rsID. The pseudo SNP ID can help preprocessing continue, but formal LD clumping/MR may require rsID-based files.

====================================================================================================
Preparing outcome set: Artesunate_EndometrialCancer_GRCh38_OutcomeCompare_04
Outcome file: /content/drive/MyDrive/UM_WQF7023/MRDRP-main/outcome/endometrial_cancer/GCST90083095_buildGRCh38.tsv.gz

Processing outcome: endometrial_cancer
Input: /content/drive/MyDrive/UM_WQF7023/MRDRP-main/outcome/endometrial_cancer/GCST90083095_buildGRCh38.tsv.gz
Detected columns:
  SNP: None
  CHR: chromosome
  POS: base_pair_location
  EA: effect_allele
  OA: other_allele
  BETA: None
  OR: odds_ratio
  SE: standard_error
  EAF: effect_allele_frequency
  P: p_value
  N: None
WARNING: No rsID/SNP column detected. Creating pseudo SNP ID using CHR:POS:EA:OA.
Output: /content/drive/MyDrive/UM_WQF7023/MRDRP-main/backend_work/mr_outputs/outcome_comparison/prepared_outcomes/Artesunate_EndometrialCancer_GRCh38_OutcomeCompare_04/endometrial_cancer_standardised.csv
Rows saved: 0
Effect size type: odds_ratio_converted_to_beta
SNP source type: pseudo_chr_pos_allele_id
Build inferred: GRCh38
NOTE: This file does not have real rsID. The pseudo SNP ID can help preprocessing continue, but formal LD clumping/MR may require rsID-based files.

====================================================================================================
Preparing outcome set: Artesunate_EndometrialCancer_GRCh38_OutcomeCompare_05
Outcome file: /content/drive/MyDrive/UM_WQF7023/MRDRP-main/outcome/endometrial_cancer/GCST90083593_buildGRCh38.tsv.gz

Processing outcome: endometrial_cancer
Input: /content/drive/MyDrive/UM_WQF7023/MRDRP-main/outcome/endometrial_cancer/GCST90083593_buildGRCh38.tsv.gz
Detected columns:
  SNP: None
  CHR: chromosome
  POS: base_pair_location
  EA: effect_allele
  OA: other_allele
  BETA: None
  OR: odds_ratio
  SE: standard_error
  EAF: effect_allele_frequency
  P: p_value
  N: None
WARNING: No rsID/SNP column detected. Creating pseudo SNP ID using CHR:POS:EA:OA.
Output: /content/drive/MyDrive/UM_WQF7023/MRDRP-main/backend_work/mr_outputs/outcome_comparison/prepared_outcomes/Artesunate_EndometrialCancer_GRCh38_OutcomeCompare_05/endometrial_cancer_standardised.csv
Rows saved: 0
Effect size type: odds_ratio_converted_to_beta
SNP source type: pseudo_chr_pos_allele_id
Build inferred: GRCh38
NOTE: This file does not have real rsID. The pseudo SNP ID can help preprocessing continue, but formal LD clumping/MR may require rsID-based files.

Multi-outcome preparation summary:

,set_name,outcome_file,prepared_outcome_file,mr_ready_outcome_file,rows_saved,effect_size_type,snp_source_type,build,mr_ready_rows,status,error
0,Artesunate_EndometrialCancer_GRCh38_OutcomeCom...,/content/drive/MyDrive/UM_WQF7023/MRDRP-main/o...,/content/drive/MyDrive/UM_WQF7023/MRDRP-main/b...,/content/drive/MyDrive/UM_WQF7023/MRDRP-main/b...,70746,odds_ratio_converted_to_beta,pseudo_chr_pos_allele_id,GRCh38,70746,prepared,None
1,Artesunate_EndometrialCancer_GRCh38_OutcomeCom...,/content/drive/MyDrive/UM_WQF7023/MRDRP-main/o...,/content/drive/MyDrive/UM_WQF7023/MRDRP-main/b...,/content/drive/MyDrive/UM_WQF7023/MRDRP-main/b...,73088,odds_ratio_converted_to_beta,pseudo_chr_pos_allele_id,GRCh38,73088,prepared,None
2,Artesunate_EndometrialCancer_GRCh38_OutcomeCom...,/content/drive/MyDrive/UM_WQF7023/MRDRP-main/o...,/content/drive/MyDrive/UM_WQF7023/MRDRP-main/b...,/content/drive/MyDrive/UM_WQF7023/MRDRP-main/b...,308476,odds_ratio_converted_to_beta,pseudo_chr_pos_allele_id,GRCh38,308476,prepared,None
3,Artesunate_EndometrialCancer_GRCh38_OutcomeCom...,/content/drive/MyDrive/UM_WQF7023/MRDRP-main/o...,/content/drive/MyDrive/UM_WQF7023/MRDRP-main/b...,/content/drive/MyDrive/UM_WQF7023/MRDRP-main/b...,0,odds_ratio_converted_to_beta,pseudo_chr_pos_allele_id,GRCh38,0,prepared,None
4,Artesunate_EndometrialCancer_GRCh38_OutcomeCom...,/content/drive/MyDrive/UM_WQF7023/MRDRP-main/o...,/content/drive/MyDrive/UM_WQF7023/MRDRP-main/b...,/content/drive/MyDrive/UM_WQF7023/MRDRP-main/b...,0,odds_ratio_converted_to_beta,pseudo_chr_pos_allele_id,GRCh38,0,prepared,None

Saved to: /content/drive/MyDrive/UM_WQF7023/MRDRP-main/backend_work/mr_outputs/summary/multi_outcome_prepare_summary.csv

In [ ]:
# ============================================================
# Cell 19: Check SNP overlap for each outcome candidate
# ============================================================

def load_snp_set_from_csv(path: Path, snp_col="SNP", chunksize=500000):
    snps = set()
    for chunk in pd.read_csv(path, usecols=[snp_col], chunksize=chunksize):
        snps.update(chunk[snp_col].dropna().astype(str).tolist())
    return snps

multi_outcome_overlap_records = []

# Reuse MR-ready exposure significant variant files from previous cells
mr_ready_sig_files = sorted(MR_READY_SIG_ROOT.glob("*_mr_ready_sig_variants.csv"))

for _, outcome_row in multi_outcome_prepare_df.iterrows():
    if outcome_row["status"] != "prepared":
        continue

    set_name = outcome_row["set_name"]
    outcome_file = Path(outcome_row["mr_ready_outcome_file"])

    print("\n" + "=" * 100)
    print("Checking overlap for:", set_name)

    outcome_snps = load_snp_set_from_csv(outcome_file)

    for exp_file in mr_ready_sig_files:
        trait = exp_file.name.replace("_mr_ready_sig_variants.csv", "")
        exp_df = pd.read_csv(exp_file)
        exp_snps = set(exp_df["SNP"].dropna().astype(str).tolist())

        overlap = sorted(list(exp_snps.intersection(outcome_snps)))

        multi_outcome_overlap_records.append({
            "set_name": set_name,
            "trait": trait,
            "exposure_snps": len(exp_snps),
            "outcome_snps": len(outcome_snps),
            "overlap_snps": len(overlap),
            "example_overlap": overlap[0] if len(overlap) > 0 else None,
            "outcome_file": str(outcome_file),
            "exposure_file": str(exp_file),
        })

multi_outcome_overlap_df = pd.DataFrame(multi_outcome_overlap_records)

multi_outcome_overlap_path = SUMMARY_DIR / "multi_outcome_snp_overlap.csv"
multi_outcome_overlap_df.to_csv(multi_outcome_overlap_path, index=False)

print("Multi-outcome SNP overlap:")
display(multi_outcome_overlap_df)
print("Saved to:", multi_outcome_overlap_path)

====================================================================================================
Checking overlap for: Artesunate_EndometrialCancer_GRCh38_OutcomeCompare_01

====================================================================================================
Checking overlap for: Artesunate_EndometrialCancer_GRCh38_OutcomeCompare_02

====================================================================================================
Checking overlap for: Artesunate_EndometrialCancer_GRCh38_OutcomeCompare_03

====================================================================================================
Checking overlap for: Artesunate_EndometrialCancer_GRCh38_OutcomeCompare_04

====================================================================================================
Checking overlap for: Artesunate_EndometrialCancer_GRCh38_OutcomeCompare_05
Multi-outcome SNP overlap:

,set_name,trait,exposure_snps,outcome_snps,overlap_snps,example_overlap,outcome_file,exposure_file
0,Artesunate_EndometrialCancer_GRCh38_OutcomeCom...,GDF15,81,70453,2,19:18264536,/content/drive/MyDrive/UM_WQF7023/MRDRP-main/b...,/content/drive/MyDrive/UM_WQF7023/MRDRP-main/b...
1,Artesunate_EndometrialCancer_GRCh38_OutcomeCom...,SHBG,8,70453,5,17:7387376,/content/drive/MyDrive/UM_WQF7023/MRDRP-main/b...,/content/drive/MyDrive/UM_WQF7023/MRDRP-main/b...
2,Artesunate_EndometrialCancer_GRCh38_OutcomeCom...,GDF15,81,72811,2,19:18264536,/content/drive/MyDrive/UM_WQF7023/MRDRP-main/b...,/content/drive/MyDrive/UM_WQF7023/MRDRP-main/b...
3,Artesunate_EndometrialCancer_GRCh38_OutcomeCom...,SHBG,8,72811,6,17:7387376,/content/drive/MyDrive/UM_WQF7023/MRDRP-main/b...,/content/drive/MyDrive/UM_WQF7023/MRDRP-main/b...
4,Artesunate_EndometrialCancer_GRCh38_OutcomeCom...,GDF15,81,304277,2,19:18264536,/content/drive/MyDrive/UM_WQF7023/MRDRP-main/b...,/content/drive/MyDrive/UM_WQF7023/MRDRP-main/b...
5,Artesunate_EndometrialCancer_GRCh38_OutcomeCom...,SHBG,8,304277,7,17:7387376,/content/drive/MyDrive/UM_WQF7023/MRDRP-main/b...,/content/drive/MyDrive/UM_WQF7023/MRDRP-main/b...
6,Artesunate_EndometrialCancer_GRCh38_OutcomeCom...,GDF15,81,0,0,None,/content/drive/MyDrive/UM_WQF7023/MRDRP-main/b...,/content/drive/MyDrive/UM_WQF7023/MRDRP-main/b...
7,Artesunate_EndometrialCancer_GRCh38_OutcomeCom...,SHBG,8,0,0,None,/content/drive/MyDrive/UM_WQF7023/MRDRP-main/b...,/content/drive/MyDrive/UM_WQF7023/MRDRP-main/b...
8,Artesunate_EndometrialCancer_GRCh38_OutcomeCom...,GDF15,81,0,0,None,/content/drive/MyDrive/UM_WQF7023/MRDRP-main/b...,/content/drive/MyDrive/UM_WQF7023/MRDRP-main/b...
9,Artesunate_EndometrialCancer_GRCh38_OutcomeCom...,SHBG,8,0,0,None,/content/drive/MyDrive/UM_WQF7023/MRDRP-main/b...,/content/drive/MyDrive/UM_WQF7023/MRDRP-main/b...

Saved to: /content/drive/MyDrive/UM_WQF7023/MRDRP-main/backend_work/mr_outputs/summary/multi_outcome_snp_overlap.csv

In [ ]:
# ============================================================
# Cell 20: Run MR for each outcome candidate
# ============================================================

MULTI_OUTCOME_MR_ROOT = OUTCOME_COMPARE_ROOT / "mr_results"

MULTI_OUTCOME_RESULTS_DIR = MULTI_OUTCOME_MR_ROOT / "results"
MULTI_OUTCOME_HARMONISED_DIR = MULTI_OUTCOME_MR_ROOT / "harmonised_data"
MULTI_OUTCOME_PLEIOTROPY_DIR = MULTI_OUTCOME_MR_ROOT / "pleiotropy"
MULTI_OUTCOME_HETEROGENEITY_DIR = MULTI_OUTCOME_MR_ROOT / "heterogeneity"

for folder in [
    MULTI_OUTCOME_RESULTS_DIR,
    MULTI_OUTCOME_HARMONISED_DIR,
    MULTI_OUTCOME_PLEIOTROPY_DIR,
    MULTI_OUTCOME_HETEROGENEITY_DIR,
]:
    folder.mkdir(parents=True, exist_ok=True)

multi_outcome_mr_run_records = []
multi_outcome_result_tables = []

for _, outcome_row in multi_outcome_prepare_df.iterrows():
    if outcome_row["status"] != "prepared":
        continue

    set_name = outcome_row["set_name"]
    outcome_file = Path(outcome_row["mr_ready_outcome_file"])

    print("\n" + "#" * 120)
    print("Running MR for outcome set:", set_name)
    print("Outcome file:", outcome_file)

    for exp_file in mr_ready_sig_files:
        trait = exp_file.name.replace("_mr_ready_sig_variants.csv", "")

        print("\n" + "=" * 100)
        print("Exposure:", trait)
        print("Exposure file:", exp_file)

        try:
            exp_dat = TwoSampleMR.read_exposure_data(
                filename=str(exp_file),
                sep=",",
                snp_col="SNP",
                beta_col="BETA",
                se_col="SE",
                effect_allele_col="EA",
                other_allele_col="OA",
                eaf_col="EAF",
                pval_col="P",
                samplesize_col="N",
                chr_col="CHR",
                pos_col="POS",
                clump=False
            )

            exp_df = pd.read_csv(exp_file)
            snp_list = robjects.StrVector(exp_df["SNP"].dropna().astype(str).tolist())

            outcome_dat = TwoSampleMR.read_outcome_data(
                snps=snp_list,
                filename=str(outcome_file),
                sep=",",
                snp_col="SNP",
                beta_col="BETA",
                se_col="SE",
                effect_allele_col="EA",
                other_allele_col="OA",
                eaf_col="EAF",
                pval_col="P"
            )

            harmonised = TwoSampleMR.harmonise_data(exp_dat, outcome_dat)
            harmonised_py = r_to_pandas(harmonised)

            harmonised_snps = len(harmonised_py)
            print("Harmonised SNP count:", harmonised_snps)

            if harmonised_snps == 0:
                raise ValueError("No SNPs retained after harmonisation.")

            res = TwoSampleMR.mr(harmonised)
            res_py = r_to_pandas(res)

            try:
                pleiotropy = TwoSampleMR.mr_pleiotropy_test(harmonised)
                pleiotropy_py = r_to_pandas(pleiotropy)
            except Exception as e:
                pleiotropy_py = pd.DataFrame({"warning": [str(e)]})

            try:
                heterogeneity = TwoSampleMR.mr_heterogeneity(harmonised)
                heterogeneity_py = r_to_pandas(heterogeneity)
            except Exception as e:
                heterogeneity_py = pd.DataFrame({"warning": [str(e)]})

            # Add metadata
            res_py["set_name"] = set_name
            res_py["trait"] = trait
            res_py["outcome_file"] = str(outcome_file)
            res_py["harmonised_snps"] = harmonised_snps

            # Save outputs
            safe_name = f"{set_name}_{trait}"
            res_py.to_csv(MULTI_OUTCOME_RESULTS_DIR / f"{safe_name}.csv", index=False)
            harmonised_py.to_csv(MULTI_OUTCOME_HARMONISED_DIR / f"{safe_name}.csv", index=False)
            pleiotropy_py.to_csv(MULTI_OUTCOME_PLEIOTROPY_DIR / f"{safe_name}.csv", index=False)
            heterogeneity_py.to_csv(MULTI_OUTCOME_HETEROGENEITY_DIR / f"{safe_name}.csv", index=False)

            multi_outcome_result_tables.append(res_py)

            multi_outcome_mr_run_records.append({
                "set_name": set_name,
                "trait": trait,
                "status": "success",
                "harmonised_snps": harmonised_snps,
                "result_rows": len(res_py),
                "error": None,
            })

            display(res_py)

        except Exception as e:
            print("ERROR:", e)

            multi_outcome_mr_run_records.append({
                "set_name": set_name,
                "trait": trait,
                "status": "failed",
                "harmonised_snps": 0,
                "result_rows": 0,
                "error": str(e),
            })

multi_outcome_mr_run_df = pd.DataFrame(multi_outcome_mr_run_records)

multi_outcome_mr_run_path = SUMMARY_DIR / "multi_outcome_mr_run_summary.csv"
multi_outcome_mr_run_df.to_csv(multi_outcome_mr_run_path, index=False)

print("\nMulti-outcome MR run summary:")
display(multi_outcome_mr_run_df)
print("Saved to:", multi_outcome_mr_run_path)

WARNING:rpy2.rinterface_lib.callbacks:R[write to console]: No phenotype name specified, defaulting to 'exposure'.

########################################################################################################################
Running MR for outcome set: Artesunate_EndometrialCancer_GRCh38_OutcomeCompare_01
Outcome file: /content/drive/MyDrive/UM_WQF7023/MRDRP-main/backend_work/mr_outputs/outcome_comparison/mr_ready_outcomes/Artesunate_EndometrialCancer_GRCh38_OutcomeCompare_01/endometrial_cancer_mr_ready.csv

====================================================================================================
Exposure: GDF15
Exposure file: /content/drive/MyDrive/UM_WQF7023/MRDRP-main/backend_work/mr_ready_significant_variants/GDF15_mr_ready_sig_variants.csv

WARNING:rpy2.rinterface_lib.callbacks:R[write to console]: No phenotype name specified, defaulting to 'outcome'.

WARNING:rpy2.rinterface_lib.callbacks:R[write to console]: Harmonising exposure (Lrdl8M) and outcome (b2G4UN)

WARNING:rpy2.rinterface_lib.callbacks:R[write to console]: Analysing 'Lrdl8M' on 'b2G4UN'

Harmonised SNP count: 2

,id.exposure,id.outcome,outcome,exposure,method,nsnp,b,se,pval,set_name,trait,outcome_file,harmonised_snps
1,Lrdl8M,b2G4UN,outcome,exposure,Inverse variance weighted,2.0,-0.704855,0.40822,0.084229,Artesunate_EndometrialCancer_GRCh38_OutcomeCom...,GDF15,/content/drive/MyDrive/UM_WQF7023/MRDRP-main/b...,2

WARNING:rpy2.rinterface_lib.callbacks:R[write to console]: No phenotype name specified, defaulting to 'exposure'.

====================================================================================================
Exposure: SHBG
Exposure file: /content/drive/MyDrive/UM_WQF7023/MRDRP-main/backend_work/mr_ready_significant_variants/SHBG_mr_ready_sig_variants.csv

WARNING:rpy2.rinterface_lib.callbacks:R[write to console]: No phenotype name specified, defaulting to 'outcome'.

WARNING:rpy2.rinterface_lib.callbacks:R[write to console]: Harmonising exposure (aR1Pus) and outcome (nG1udT)

WARNING:rpy2.rinterface_lib.callbacks:R[write to console]: Analysing 'aR1Pus' on 'nG1udT'

Harmonised SNP count: 5

,id.exposure,id.outcome,outcome,exposure,method,nsnp,b,se,pval,set_name,trait,outcome_file,harmonised_snps
1,aR1Pus,nG1udT,outcome,exposure,MR Egger,5.0,0.149544,0.220549,0.546353,Artesunate_EndometrialCancer_GRCh38_OutcomeCom...,SHBG,/content/drive/MyDrive/UM_WQF7023/MRDRP-main/b...,5
2,aR1Pus,nG1udT,outcome,exposure,Weighted median,5.0,0.198280,0.203747,0.330468,Artesunate_EndometrialCancer_GRCh38_OutcomeCom...,SHBG,/content/drive/MyDrive/UM_WQF7023/MRDRP-main/b...,5
3,aR1Pus,nG1udT,outcome,exposure,Inverse variance weighted,5.0,0.216414,0.203990,0.288733,Artesunate_EndometrialCancer_GRCh38_OutcomeCom...,SHBG,/content/drive/MyDrive/UM_WQF7023/MRDRP-main/b...,5
4,aR1Pus,nG1udT,outcome,exposure,Simple mode,5.0,0.926519,1.602192,0.594070,Artesunate_EndometrialCancer_GRCh38_OutcomeCom...,SHBG,/content/drive/MyDrive/UM_WQF7023/MRDRP-main/b...,5
5,aR1Pus,nG1udT,outcome,exposure,Weighted mode,5.0,0.199689,2.192781,0.931818,Artesunate_EndometrialCancer_GRCh38_OutcomeCom...,SHBG,/content/drive/MyDrive/UM_WQF7023/MRDRP-main/b...,5

WARNING:rpy2.rinterface_lib.callbacks:R[write to console]: No phenotype name specified, defaulting to 'exposure'.

WARNING:rpy2.rinterface_lib.callbacks:R[write to console]: No phenotype name specified, defaulting to 'outcome'.

########################################################################################################################
Running MR for outcome set: Artesunate_EndometrialCancer_GRCh38_OutcomeCompare_02
Outcome file: /content/drive/MyDrive/UM_WQF7023/MRDRP-main/backend_work/mr_outputs/outcome_comparison/mr_ready_outcomes/Artesunate_EndometrialCancer_GRCh38_OutcomeCompare_02/endometrial_cancer_mr_ready.csv

====================================================================================================
Exposure: GDF15
Exposure file: /content/drive/MyDrive/UM_WQF7023/MRDRP-main/backend_work/mr_ready_significant_variants/GDF15_mr_ready_sig_variants.csv

WARNING:rpy2.rinterface_lib.callbacks:R[write to console]: Harmonising exposure (oRIf1M) and outcome (vluVZs)

WARNING:rpy2.rinterface_lib.callbacks:R[write to console]: Analysing 'oRIf1M' on 'vluVZs'

Harmonised SNP count: 2

,id.exposure,id.outcome,outcome,exposure,method,nsnp,b,se,pval,set_name,trait,outcome_file,harmonised_snps
1,oRIf1M,vluVZs,outcome,exposure,Inverse variance weighted,2.0,-0.470632,0.334359,0.159261,Artesunate_EndometrialCancer_GRCh38_OutcomeCom...,GDF15,/content/drive/MyDrive/UM_WQF7023/MRDRP-main/b...,2

WARNING:rpy2.rinterface_lib.callbacks:R[write to console]: No phenotype name specified, defaulting to 'exposure'.

====================================================================================================
Exposure: SHBG
Exposure file: /content/drive/MyDrive/UM_WQF7023/MRDRP-main/backend_work/mr_ready_significant_variants/SHBG_mr_ready_sig_variants.csv

WARNING:rpy2.rinterface_lib.callbacks:R[write to console]: No phenotype name specified, defaulting to 'outcome'.

WARNING:rpy2.rinterface_lib.callbacks:R[write to console]: Harmonising exposure (Ifc84U) and outcome (dLaw7r)

Harmonised SNP count: 6

WARNING:rpy2.rinterface_lib.callbacks:R[write to console]: Analysing 'Ifc84U' on 'dLaw7r'

,id.exposure,id.outcome,outcome,exposure,method,nsnp,b,se,pval,set_name,trait,outcome_file,harmonised_snps
1,Ifc84U,dLaw7r,outcome,exposure,MR Egger,6.0,-0.017569,0.187600,0.929890,Artesunate_EndometrialCancer_GRCh38_OutcomeCom...,SHBG,/content/drive/MyDrive/UM_WQF7023/MRDRP-main/b...,6
2,Ifc84U,dLaw7r,outcome,exposure,Weighted median,6.0,-0.023262,0.178114,0.896089,Artesunate_EndometrialCancer_GRCh38_OutcomeCom...,SHBG,/content/drive/MyDrive/UM_WQF7023/MRDRP-main/b...,6
3,Ifc84U,dLaw7r,outcome,exposure,Inverse variance weighted,6.0,-0.041874,0.173211,0.808973,Artesunate_EndometrialCancer_GRCh38_OutcomeCom...,SHBG,/content/drive/MyDrive/UM_WQF7023/MRDRP-main/b...,6
4,Ifc84U,dLaw7r,outcome,exposure,Simple mode,6.0,0.154745,0.642633,0.819273,Artesunate_EndometrialCancer_GRCh38_OutcomeCom...,SHBG,/content/drive/MyDrive/UM_WQF7023/MRDRP-main/b...,6
5,Ifc84U,dLaw7r,outcome,exposure,Weighted mode,6.0,-0.012013,2.173636,0.995804,Artesunate_EndometrialCancer_GRCh38_OutcomeCom...,SHBG,/content/drive/MyDrive/UM_WQF7023/MRDRP-main/b...,6

WARNING:rpy2.rinterface_lib.callbacks:R[write to console]: No phenotype name specified, defaulting to 'exposure'.

########################################################################################################################
Running MR for outcome set: Artesunate_EndometrialCancer_GRCh38_OutcomeCompare_03
Outcome file: /content/drive/MyDrive/UM_WQF7023/MRDRP-main/backend_work/mr_outputs/outcome_comparison/mr_ready_outcomes/Artesunate_EndometrialCancer_GRCh38_OutcomeCompare_03/endometrial_cancer_mr_ready.csv

====================================================================================================
Exposure: GDF15
Exposure file: /content/drive/MyDrive/UM_WQF7023/MRDRP-main/backend_work/mr_ready_significant_variants/GDF15_mr_ready_sig_variants.csv

WARNING:rpy2.rinterface_lib.callbacks:R[write to console]: No phenotype name specified, defaulting to 'outcome'.

WARNING:rpy2.rinterface_lib.callbacks:R[write to console]: Harmonising exposure (TZURKg) and outcome (BAVGJq)

WARNING:rpy2.rinterface_lib.callbacks:R[write to console]: Analysing 'TZURKg' on 'BAVGJq'

Harmonised SNP count: 2

,id.exposure,id.outcome,outcome,exposure,method,nsnp,b,se,pval,set_name,trait,outcome_file,harmonised_snps
1,TZURKg,BAVGJq,outcome,exposure,Inverse variance weighted,2.0,-0.372194,0.242606,0.124993,Artesunate_EndometrialCancer_GRCh38_OutcomeCom...,GDF15,/content/drive/MyDrive/UM_WQF7023/MRDRP-main/b...,2

WARNING:rpy2.rinterface_lib.callbacks:R[write to console]: No phenotype name specified, defaulting to 'exposure'.

====================================================================================================
Exposure: SHBG
Exposure file: /content/drive/MyDrive/UM_WQF7023/MRDRP-main/backend_work/mr_ready_significant_variants/SHBG_mr_ready_sig_variants.csv

WARNING:rpy2.rinterface_lib.callbacks:R[write to console]: No phenotype name specified, defaulting to 'outcome'.

WARNING:rpy2.rinterface_lib.callbacks:R[write to console]: Harmonising exposure (RqAzOd) and outcome (2e36lX)

WARNING:rpy2.rinterface_lib.callbacks:R[write to console]: Analysing 'RqAzOd' on '2e36lX'

Harmonised SNP count: 7

,id.exposure,id.outcome,outcome,exposure,method,nsnp,b,se,pval,set_name,trait,outcome_file,harmonised_snps
1,RqAzOd,2e36lX,outcome,exposure,MR Egger,7.0,-0.073763,0.183881,0.704881,Artesunate_EndometrialCancer_GRCh38_OutcomeCom...,SHBG,/content/drive/MyDrive/UM_WQF7023/MRDRP-main/b...,7
2,RqAzOd,2e36lX,outcome,exposure,Weighted median,7.0,-0.070791,0.175366,0.686453,Artesunate_EndometrialCancer_GRCh38_OutcomeCom...,SHBG,/content/drive/MyDrive/UM_WQF7023/MRDRP-main/b...,7
3,RqAzOd,2e36lX,outcome,exposure,Inverse variance weighted,7.0,-0.076438,0.169484,0.651988,Artesunate_EndometrialCancer_GRCh38_OutcomeCom...,SHBG,/content/drive/MyDrive/UM_WQF7023/MRDRP-main/b...,7
4,RqAzOd,2e36lX,outcome,exposure,Simple mode,7.0,0.452069,0.875802,0.624194,Artesunate_EndometrialCancer_GRCh38_OutcomeCom...,SHBG,/content/drive/MyDrive/UM_WQF7023/MRDRP-main/b...,7
5,RqAzOd,2e36lX,outcome,exposure,Weighted mode,7.0,-0.060553,2.345330,0.980239,Artesunate_EndometrialCancer_GRCh38_OutcomeCom...,SHBG,/content/drive/MyDrive/UM_WQF7023/MRDRP-main/b...,7

WARNING:rpy2.rinterface_lib.callbacks:R[write to console]: No phenotype name specified, defaulting to 'exposure'.

WARNING:rpy2.rinterface_lib.callbacks:R[write to console]: Error in format_data(as.data.frame(outcome_dat), type = "outcome", snps = snps,  :
  No SNPs specified for the exposure are present in the outcome dataset.

WARNING:rpy2.rinterface_lib.callbacks:R[write to console]: In addition:
WARNING:rpy2.rinterface_lib.callbacks:R[write to console]: Warning messages:

WARNING:rpy2.rinterface_lib.callbacks:R[write to console]: 1:
WARNING:rpy2.rinterface_lib.callbacks:R[write to console]: In format_data(as.data.frame(exposure_dat), type = "exposure", snps = NULL,  :
WARNING:rpy2.rinterface_lib.callbacks:R[write to console]:

WARNING:rpy2.rinterface_lib.callbacks:R[write to console]:  N column is not numeric

WARNING:rpy2.rinterface_lib.callbacks:R[write to console]: 2:
WARNING:rpy2.rinterface_lib.callbacks:R[write to console]: In format_data(as.data.frame(exposure_dat), type = "exposure", snps = NULL,  :
WARNING:rpy2.rinterface_lib.callbacks:R[write to console]:

WARNING:rpy2.rinterface_lib.callbacks:R[write to console]:  N column is not numeric

WARNING:rpy2.rinterface_lib.callbacks:R[write to console]: 3:
WARNING:rpy2.rinterface_lib.callbacks:R[write to console]: In format_data(as.data.frame(exposure_dat), type = "exposure", snps = NULL,  :
WARNING:rpy2.rinterface_lib.callbacks:R[write to console]:

WARNING:rpy2.rinterface_lib.callbacks:R[write to console]:  N column is not numeric

WARNING:rpy2.rinterface_lib.callbacks:R[write to console]: 4:
WARNING:rpy2.rinterface_lib.callbacks:R[write to console]: In format_data(as.data.frame(exposure_dat), type = "exposure", snps = NULL,  :
WARNING:rpy2.rinterface_lib.callbacks:R[write to console]:

WARNING:rpy2.rinterface_lib.callbacks:R[write to console]:  N column is not numeric

WARNING:rpy2.rinterface_lib.callbacks:R[write to console]: 5:
WARNING:rpy2.rinterface_lib.callbacks:R[write to console]: In format_data(as.data.frame(exposure_dat), type = "exposure", snps = NULL,  :
WARNING:rpy2.rinterface_lib.callbacks:R[write to console]:

WARNING:rpy2.rinterface_lib.callbacks:R[write to console]:  N column is not numeric

WARNING:rpy2.rinterface_lib.callbacks:R[write to console]: 6:
WARNING:rpy2.rinterface_lib.callbacks:R[write to console]: In format_data(as.data.frame(exposure_dat), type = "exposure", snps = NULL,  :
WARNING:rpy2.rinterface_lib.callbacks:R[write to console]:

WARNING:rpy2.rinterface_lib.callbacks:R[write to console]:  N column is not numeric

WARNING:rpy2.rinterface_lib.callbacks:R[write to console]: 7:
WARNING:rpy2.rinterface_lib.callbacks:R[write to console]: In format_data(as.data.frame(exposure_dat), type = "exposure", snps = NULL,  :
WARNING:rpy2.rinterface_lib.callbacks:R[write to console]:

WARNING:rpy2.rinterface_lib.callbacks:R[write to console]:  N column is not numeric

WARNING:rpy2.rinterface_lib.callbacks:R[write to console]: No phenotype name specified, defaulting to 'exposure'.

WARNING:rpy2.rinterface_lib.callbacks:R[write to console]: Error in format_data(as.data.frame(outcome_dat), type = "outcome", snps = snps,  :
  No SNPs specified for the exposure are present in the outcome dataset.

WARNING:rpy2.rinterface_lib.callbacks:R[write to console]: In addition:
WARNING:rpy2.rinterface_lib.callbacks:R[write to console]: Warning message:

WARNING:rpy2.rinterface_lib.callbacks:R[write to console]: In format_data(as.data.frame(exposure_dat), type = "exposure", snps = NULL,  :
WARNING:rpy2.rinterface_lib.callbacks:R[write to console]:

WARNING:rpy2.rinterface_lib.callbacks:R[write to console]:  N column is not numeric

WARNING:rpy2.rinterface_lib.callbacks:R[write to console]: No phenotype name specified, defaulting to 'exposure'.

WARNING:rpy2.rinterface_lib.callbacks:R[write to console]: Error in format_data(as.data.frame(outcome_dat), type = "outcome", snps = snps,  :
  No SNPs specified for the exposure are present in the outcome dataset.

WARNING:rpy2.rinterface_lib.callbacks:R[write to console]: In addition:
WARNING:rpy2.rinterface_lib.callbacks:R[write to console]: Warning message:

WARNING:rpy2.rinterface_lib.callbacks:R[write to console]: In format_data(as.data.frame(exposure_dat), type = "exposure", snps = NULL,  :
WARNING:rpy2.rinterface_lib.callbacks:R[write to console]:

WARNING:rpy2.rinterface_lib.callbacks:R[write to console]:  N column is not numeric

WARNING:rpy2.rinterface_lib.callbacks:R[write to console]: No phenotype name specified, defaulting to 'exposure'.

WARNING:rpy2.rinterface_lib.callbacks:R[write to console]: Error in format_data(as.data.frame(outcome_dat), type = "outcome", snps = snps,  :
  No SNPs specified for the exposure are present in the outcome dataset.

WARNING:rpy2.rinterface_lib.callbacks:R[write to console]: In addition:
WARNING:rpy2.rinterface_lib.callbacks:R[write to console]: Warning message:

WARNING:rpy2.rinterface_lib.callbacks:R[write to console]: In format_data(as.data.frame(exposure_dat), type = "exposure", snps = NULL,  :
WARNING:rpy2.rinterface_lib.callbacks:R[write to console]:

WARNING:rpy2.rinterface_lib.callbacks:R[write to console]:  N column is not numeric

########################################################################################################################
Running MR for outcome set: Artesunate_EndometrialCancer_GRCh38_OutcomeCompare_04
Outcome file: /content/drive/MyDrive/UM_WQF7023/MRDRP-main/backend_work/mr_outputs/outcome_comparison/mr_ready_outcomes/Artesunate_EndometrialCancer_GRCh38_OutcomeCompare_04/endometrial_cancer_mr_ready.csv

====================================================================================================
Exposure: GDF15
Exposure file: /content/drive/MyDrive/UM_WQF7023/MRDRP-main/backend_work/mr_ready_significant_variants/GDF15_mr_ready_sig_variants.csv
ERROR: Error in format_data(as.data.frame(outcome_dat), type = "outcome", snps = snps,  :
  No SNPs specified for the exposure are present in the outcome dataset.


====================================================================================================
Exposure: SHBG
Exposure file: /content/drive/MyDrive/UM_WQF7023/MRDRP-main/backend_work/mr_ready_significant_variants/SHBG_mr_ready_sig_variants.csv
ERROR: Error in format_data(as.data.frame(outcome_dat), type = "outcome", snps = snps,  :
  No SNPs specified for the exposure are present in the outcome dataset.


########################################################################################################################
Running MR for outcome set: Artesunate_EndometrialCancer_GRCh38_OutcomeCompare_05
Outcome file: /content/drive/MyDrive/UM_WQF7023/MRDRP-main/backend_work/mr_outputs/outcome_comparison/mr_ready_outcomes/Artesunate_EndometrialCancer_GRCh38_OutcomeCompare_05/endometrial_cancer_mr_ready.csv

====================================================================================================
Exposure: GDF15
Exposure file: /content/drive/MyDrive/UM_WQF7023/MRDRP-main/backend_work/mr_ready_significant_variants/GDF15_mr_ready_sig_variants.csv
ERROR: Error in format_data(as.data.frame(outcome_dat), type = "outcome", snps = snps,  :
  No SNPs specified for the exposure are present in the outcome dataset.


====================================================================================================
Exposure: SHBG
Exposure file: /content/drive/MyDrive/UM_WQF7023/MRDRP-main/backend_work/mr_ready_significant_variants/SHBG_mr_ready_sig_variants.csv
ERROR: Error in format_data(as.data.frame(outcome_dat), type = "outcome", snps = snps,  :
  No SNPs specified for the exposure are present in the outcome dataset.


Multi-outcome MR run summary:

,set_name,trait,status,harmonised_snps,result_rows,error
0,Artesunate_EndometrialCancer_GRCh38_OutcomeCom...,GDF15,success,2,1,None
1,Artesunate_EndometrialCancer_GRCh38_OutcomeCom...,SHBG,success,5,5,None
2,Artesunate_EndometrialCancer_GRCh38_OutcomeCom...,GDF15,success,2,1,None
3,Artesunate_EndometrialCancer_GRCh38_OutcomeCom...,SHBG,success,6,5,None
4,Artesunate_EndometrialCancer_GRCh38_OutcomeCom...,GDF15,success,2,1,None
5,Artesunate_EndometrialCancer_GRCh38_OutcomeCom...,SHBG,success,7,5,None
6,Artesunate_EndometrialCancer_GRCh38_OutcomeCom...,GDF15,failed,0,0,Error in format_data(as.data.frame(outcome_dat...
7,Artesunate_EndometrialCancer_GRCh38_OutcomeCom...,SHBG,failed,0,0,Error in format_data(as.data.frame(outcome_dat...
8,Artesunate_EndometrialCancer_GRCh38_OutcomeCom...,GDF15,failed,0,0,Error in format_data(as.data.frame(outcome_dat...
9,Artesunate_EndometrialCancer_GRCh38_OutcomeCom...,SHBG,failed,0,0,Error in format_data(as.data.frame(outcome_dat...

Saved to: /content/drive/MyDrive/UM_WQF7023/MRDRP-main/backend_work/mr_outputs/summary/multi_outcome_mr_run_summary.csv

In [ ]:
# ============================================================
# Cell 21: Combine and rank multi-outcome MR results
# ============================================================

if len(multi_outcome_result_tables) > 0:
    multi_outcome_combined_results = pd.concat(multi_outcome_result_tables, ignore_index=True)

    if "b" in multi_outcome_combined_results.columns:
        multi_outcome_combined_results["MR_OR"] = np.exp(multi_outcome_combined_results["b"])

    if "b" in multi_outcome_combined_results.columns and "se" in multi_outcome_combined_results.columns:
        multi_outcome_combined_results["MR_OR_lower_95CI"] = np.exp(
            multi_outcome_combined_results["b"] - 1.96 * multi_outcome_combined_results["se"]
        )
        multi_outcome_combined_results["MR_OR_upper_95CI"] = np.exp(
            multi_outcome_combined_results["b"] + 1.96 * multi_outcome_combined_results["se"]
        )

    if "pval" in multi_outcome_combined_results.columns:
        multi_outcome_combined_results["nominal_significant"] = multi_outcome_combined_results["pval"] < 0.05

    # Merge overlap info
    overlap_for_merge = multi_outcome_overlap_df[[
        "set_name", "trait", "overlap_snps"
    ]].drop_duplicates()

    multi_outcome_combined_results = multi_outcome_combined_results.merge(
        overlap_for_merge,
        on=["set_name", "trait"],
        how="left"
    )

    # Sort by trait, p-value, and overlap
    if "pval" in multi_outcome_combined_results.columns:
        multi_outcome_combined_results = multi_outcome_combined_results.sort_values(
            by=["trait", "pval", "overlap_snps"],
            ascending=[True, True, False]
        )

    multi_outcome_combined_path = SUMMARY_DIR / "multi_outcome_combined_mr_results.csv"
    multi_outcome_combined_results.to_csv(multi_outcome_combined_path, index=False)

    print("Multi-outcome combined MR results:")
    display(multi_outcome_combined_results)
    print("Saved to:", multi_outcome_combined_path)

else:
    multi_outcome_combined_results = pd.DataFrame()
    print("No multi-outcome MR result tables were generated.")

Multi-outcome combined MR results:

,id.exposure,id.outcome,outcome,exposure,method,nsnp,b,se,pval,set_name,trait,outcome_file,harmonised_snps,MR_OR,MR_OR_lower_95CI,MR_OR_upper_95CI,nominal_significant,overlap_snps
0,Lrdl8M,b2G4UN,outcome,exposure,Inverse variance weighted,2.0,-0.704855,0.408220,0.084229,Artesunate_EndometrialCancer_GRCh38_OutcomeCom...,GDF15,/content/drive/MyDrive/UM_WQF7023/MRDRP-main/b...,2,0.494180,0.222025,1.099940,False,2
12,TZURKg,BAVGJq,outcome,exposure,Inverse variance weighted,2.0,-0.372194,0.242606,0.124993,Artesunate_EndometrialCancer_GRCh38_OutcomeCom...,GDF15,/content/drive/MyDrive/UM_WQF7023/MRDRP-main/b...,2,0.689221,0.428399,1.108839,False,2
6,oRIf1M,vluVZs,outcome,exposure,Inverse variance weighted,2.0,-0.470632,0.334359,0.159261,Artesunate_EndometrialCancer_GRCh38_OutcomeCom...,GDF15,/content/drive/MyDrive/UM_WQF7023/MRDRP-main/b...,2,0.624608,0.324336,1.202873,False,2
3,aR1Pus,nG1udT,outcome,exposure,Inverse variance weighted,5.0,0.216414,0.203990,0.288733,Artesunate_EndometrialCancer_GRCh38_OutcomeCom...,SHBG,/content/drive/MyDrive/UM_WQF7023/MRDRP-main/b...,5,1.241617,0.832430,1.851942,False,5
2,aR1Pus,nG1udT,outcome,exposure,Weighted median,5.0,0.198280,0.203747,0.330468,Artesunate_EndometrialCancer_GRCh38_OutcomeCom...,SHBG,/content/drive/MyDrive/UM_WQF7023/MRDRP-main/b...,5,1.219304,0.817861,1.817794,False,5
1,aR1Pus,nG1udT,outcome,exposure,MR Egger,5.0,0.149544,0.220549,0.546353,Artesunate_EndometrialCancer_GRCh38_OutcomeCom...,SHBG,/content/drive/MyDrive/UM_WQF7023/MRDRP-main/b...,5,1.161305,0.753721,1.789293,False,5
4,aR1Pus,nG1udT,outcome,exposure,Simple mode,5.0,0.926519,1.602192,0.594070,Artesunate_EndometrialCancer_GRCh38_OutcomeCom...,SHBG,/content/drive/MyDrive/UM_WQF7023/MRDRP-main/b...,5,2.525703,0.109287,58.370770,False,5
16,RqAzOd,2e36lX,outcome,exposure,Simple mode,7.0,0.452069,0.875802,0.624194,Artesunate_EndometrialCancer_GRCh38_OutcomeCom...,SHBG,/content/drive/MyDrive/UM_WQF7023/MRDRP-main/b...,7,1.571561,0.282380,8.746401,False,7
15,RqAzOd,2e36lX,outcome,exposure,Inverse variance weighted,7.0,-0.076438,0.169484,0.651988,Artesunate_EndometrialCancer_GRCh38_OutcomeCom...,SHBG,/content/drive/MyDrive/UM_WQF7023/MRDRP-main/b...,7,0.926411,0.664563,1.291431,False,7
14,RqAzOd,2e36lX,outcome,exposure,Weighted median,7.0,-0.070791,0.175366,0.686453,Artesunate_EndometrialCancer_GRCh38_OutcomeCom...,SHBG,/content/drive/MyDrive/UM_WQF7023/MRDRP-main/b...,7,0.931657,0.660665,1.313805,False,7
13,RqAzOd,2e36lX,outcome,exposure,MR Egger,7.0,-0.073763,0.183881,0.704881,Artesunate_EndometrialCancer_GRCh38_OutcomeCom...,SHBG,/content/drive/MyDrive/UM_WQF7023/MRDRP-main/b...,7,0.928892,0.647802,1.331949,False,7
9,Ifc84U,dLaw7r,outcome,exposure,Inverse variance weighted,6.0,-0.041874,0.173211,0.808973,Artesunate_EndometrialCancer_GRCh38_OutcomeCom...,SHBG,/content/drive/MyDrive/UM_WQF7023/MRDRP-main/b...,6,0.958991,0.682927,1.346649,False,6
10,Ifc84U,dLaw7r,outcome,exposure,Simple mode,6.0,0.154745,0.642633,0.819273,Artesunate_EndometrialCancer_GRCh38_OutcomeCom...,SHBG,/content/drive/MyDrive/UM_WQF7023/MRDRP-main/b...,6,1.167361,0.331272,4.113633,False,6
8,Ifc84U,dLaw7r,outcome,exposure,Weighted median,6.0,-0.023262,0.178114,0.896089,Artesunate_EndometrialCancer_GRCh38_OutcomeCom...,SHBG,/content/drive/MyDrive/UM_WQF7023/MRDRP-main/b...,6,0.977006,0.689103,1.385194,False,6
7,Ifc84U,dLaw7r,outcome,exposure,MR Egger,6.0,-0.017569,0.187600,0.929890,Artesunate_EndometrialCancer_GRCh38_OutcomeCom...,SHBG,/content/drive/MyDrive/UM_WQF7023/MRDRP-main/b...,6,0.982584,0.680271,1.419248,False,6
5,aR1Pus,nG1udT,outcome,exposure,Weighted mode,5.0,0.199689,2.192781,0.931818,Artesunate_EndometrialCancer_GRCh38_OutcomeCom...,SHBG,/content/drive/MyDrive/UM_WQF7023/MRDRP-main/b...,5,1.221023,0.016603,89.795878,False,5
17,RqAzOd,2e36lX,outcome,exposure,Weighted mode,7.0,-0.060553,2.345330,0.980239,Artesunate_EndometrialCancer_GRCh38_OutcomeCom...,SHBG,/content/drive/MyDrive/UM_WQF7023/MRDRP-main/b...,7,0.941244,0.009491,93.344188,False,7
11,Ifc84U,dLaw7r,outcome,exposure,Weighted mode,6.0,-0.012013,2.173636,0.995804,Artesunate_EndometrialCancer_GRCh38_OutcomeCom...,SHBG,/content/drive/MyDrive/UM_WQF7023/MRDRP-main/b...,6,0.988059,0.013949,69.987216,False,6

Saved to: /content/drive/MyDrive/UM_WQF7023/MRDRP-main/backend_work/mr_outputs/summary/multi_outcome_combined_mr_results.csv

In [ ]:
# ============================================================
# Cell 22: Generate outcome comparison report
# ============================================================

from datetime import datetime

report_lines = []

report_lines.append("# Multi-outcome Backend MR Comparison Report")
report_lines.append("")
report_lines.append(f"Run time: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
report_lines.append("")

report_lines.append("## Purpose")
report_lines.append("")
report_lines.append(
    "This analysis compares multiple endometrial cancer outcome GWAS files while keeping the selected exposure files fixed. "
    "The purpose is to evaluate whether outcome file choice affects SNP overlap, harmonisation success, and prototype MR results."
)
report_lines.append("")

report_lines.append("## Outcome candidates")
report_lines.append("")
if "multi_outcome_sets_df" in globals():
    report_lines.append(multi_outcome_sets_df.to_markdown(index=False))
else:
    report_lines.append("Outcome candidate table not available.")
report_lines.append("")

report_lines.append("## Outcome preparation summary")
report_lines.append("")
if "multi_outcome_prepare_df" in globals():
    report_lines.append(multi_outcome_prepare_df.to_markdown(index=False))
else:
    report_lines.append("Outcome preparation summary not available.")
report_lines.append("")

report_lines.append("## SNP overlap summary")
report_lines.append("")
if "multi_outcome_overlap_df" in globals():
    report_lines.append(multi_outcome_overlap_df.to_markdown(index=False))
else:
    report_lines.append("SNP overlap summary not available.")
report_lines.append("")

report_lines.append("## MR run summary")
report_lines.append("")
if "multi_outcome_mr_run_df" in globals():
    report_lines.append(multi_outcome_mr_run_df.to_markdown(index=False))
else:
    report_lines.append("MR run summary not available.")
report_lines.append("")

report_lines.append("## Combined MR results")
report_lines.append("")
if "multi_outcome_combined_results" in globals() and len(multi_outcome_combined_results) > 0:
    report_lines.append(multi_outcome_combined_results.to_markdown(index=False))
else:
    report_lines.append("No combined MR results available.")
report_lines.append("")

report_lines.append("## Interpretation note")
report_lines.append("")
report_lines.append(
    "This is an outcome-comparison backend prototype. Since several selected files use coordinate-based variant identifiers rather than standard rsID, "
    "formal LD clumping was not applied in this run. The results should therefore be interpreted as backend robustness and feasibility outputs, "
    "not as final formal MR evidence."
)

multi_outcome_report_text = "\n".join(report_lines)

multi_outcome_report_path = SUMMARY_DIR / "multi_outcome_backend_mr_comparison_report.md"

with open(multi_outcome_report_path, "w", encoding="utf-8") as f:
    f.write(multi_outcome_report_text)

print("Multi-outcome comparison report saved to:", multi_outcome_report_path)
print("\nPreview:")
print(multi_outcome_report_text[:3000])

Multi-outcome comparison report saved to: /content/drive/MyDrive/UM_WQF7023/MRDRP-main/backend_work/mr_outputs/summary/multi_outcome_backend_mr_comparison_report.md

Preview:
# Multi-outcome Backend MR Comparison Report

Run time: 2026-05-13 13:49:23

## Purpose

This analysis compares multiple endometrial cancer outcome GWAS files while keeping the selected exposure files fixed. The purpose is to evaluate whether outcome file choice affects SNP overlap, harmonisation success, and prototype MR results.

## Outcome candidates

| set_name                                              | outcome_file_name               | outcome_build   | outcome_status   | outcome_effect_size_type   | outcome_file                                                                                            |
|:------------------------------------------------------|:--------------------------------|:----------------|:-----------------|:---------------------------|:--------------------------------------------------------------------------------------------------------|
| Artesunate_EndometrialCancer_GRCh38_OutcomeCompare_01 | GCST90077633_buildGRCh38.tsv.gz | GRCh38          | Needs adaptation | odds_ratio                 | /content/drive/MyDrive/UM_WQF7023/MRDRP-main/outcome/endometrial_cancer/GCST90077633_buildGRCh38.tsv.gz |
| Artesunate_EndometrialCancer_GRCh38_OutcomeCompare_02 | GCST90079109_buildGRCh38.tsv.gz | GRCh38          | Needs adaptation | odds_ratio                 | /content/drive/MyDrive/UM_WQF7023/MRDRP-main/outcome/endometrial_cancer/GCST90079109_buildGRCh38.tsv.gz |
| Artesunate_EndometrialCancer_GRCh38_OutcomeCompare_03 | GCST90079607_buildGRCh38.tsv.gz | GRCh38          | Needs adaptation | odds_ratio                 | /content/drive/MyDrive/UM_WQF7023/MRDRP-main/outcome/endometrial_cancer/GCST90079607_buildGRCh38.tsv.gz |
| Artesunate_EndometrialCancer_GRCh38_OutcomeCompare_04 | GCST90083095_buildGRCh38.tsv.gz | GRCh38          | Needs adaptation | odds_ratio                 | /content/drive/MyDrive/UM_WQF7023/MRDRP-main/outcome/endometrial_cancer/GCST90083095_buildGRCh38.tsv.gz |
| Artesunate_EndometrialCancer_GRCh38_OutcomeCompare_05 | GCST90083593_buildGRCh38.tsv.gz | GRCh38          | Needs adaptation | odds_ratio                 | /content/drive/MyDrive/UM_WQF7023/MRDRP-main/outcome/endometrial_cancer/GCST90083593_buildGRCh38.tsv.gz |

## Outcome preparation summary

| set_name                                              | outcome_file                                                                                            | prepared_outcome_file                                                                                                                                                                               | mr_ready_outcome_file                                                                                                                                                                           |   rows_saved | effect_size_type             | snp_source_type          | build   |   mr_ready_rows | status   | error   |
|:------------------------------------------------------|:--------------------------

In [ ]:
# ============================================================
# Cell 23.0: Define LD clumping output folders
# ============================================================

from pathlib import Path
import pandas as pd
import numpy as np
import shutil
import os
import time
import json
import re

LD_ROOT = BACKEND_ROOT / "ld_clumping"
LD_MAPPING_ROOT = LD_ROOT / "rsid_mapping"
LD_INPUT_ROOT = LD_ROOT / "ld_input_significant_variants"
LD_CLUMPED_ROOT = LD_ROOT / "ld_clumped_significant_variants"
MR_READY_CLUMPED_SIG_ROOT = BACKEND_ROOT / "mr_ready_clumped_significant_variants"

CLUMPED_MR_OUTPUT_ROOT = MR_OUTPUT_ROOT / "clumped_mr"
CLUMPED_MR_RESULTS_DIR = CLUMPED_MR_OUTPUT_ROOT / "results"
CLUMPED_MR_HARMONISED_DIR = CLUMPED_MR_OUTPUT_ROOT / "harmonised_data"
CLUMPED_MR_PLEIOTROPY_DIR = CLUMPED_MR_OUTPUT_ROOT / "pleiotropy"
CLUMPED_MR_HETEROGENEITY_DIR = CLUMPED_MR_OUTPUT_ROOT / "heterogeneity"

for folder in [
    LD_ROOT,
    LD_MAPPING_ROOT,
    LD_INPUT_ROOT,
    LD_CLUMPED_ROOT,
    MR_READY_CLUMPED_SIG_ROOT,
    CLUMPED_MR_OUTPUT_ROOT,
    CLUMPED_MR_RESULTS_DIR,
    CLUMPED_MR_HARMONISED_DIR,
    CLUMPED_MR_PLEIOTROPY_DIR,
    CLUMPED_MR_HETEROGENEITY_DIR,
]:
    folder.mkdir(parents=True, exist_ok=True)

print("LD clumping folders are ready.")
print("LD_ROOT:", LD_ROOT)
print("LD_CLUMPED_ROOT:", LD_CLUMPED_ROOT)
print("MR_READY_CLUMPED_SIG_ROOT:", MR_READY_CLUMPED_SIG_ROOT)

LD clumping folders are ready.
LD_ROOT: /content/drive/MyDrive/UM_WQF7023/MRDRP-main/backend_work/ld_clumping
LD_CLUMPED_ROOT: /content/drive/MyDrive/UM_WQF7023/MRDRP-main/backend_work/ld_clumping/ld_clumped_significant_variants
MR_READY_CLUMPED_SIG_ROOT: /content/drive/MyDrive/UM_WQF7023/MRDRP-main/backend_work/mr_ready_clumped_significant_variants

In [ ]:
# ============================================================
# Cell 23.1: Inspect significant variants before LD clumping
# ============================================================

sig_files = sorted(SIG_VARIANT_ROOT.glob("*_full_sig_variants.csv"))

if len(sig_files) == 0:
    raise FileNotFoundError(
        f"No significant variant files found in {SIG_VARIANT_ROOT}. "
        "Please make sure Cell 9 and Cell 10 were already completed."
    )

inspect_records = []

for f in sig_files:
    trait = f.name.replace("_full_sig_variants.csv", "")
    df = pd.read_csv(f)

    snp_examples = df["SNP"].dropna().astype(str).head(5).tolist() if "SNP" in df.columns else []

    looks_like_rsid = 0
    if "SNP" in df.columns:
        looks_like_rsid = int(df["SNP"].astype(str).str.startswith("rs").sum())

    inspect_records.append({
        "trait": trait,
        "file": str(f),
        "rows": len(df),
        "columns": ", ".join(df.columns.tolist()),
        "rsid_like_count": looks_like_rsid,
        "non_rsid_count": len(df) - looks_like_rsid,
        "has_chr": "CHR" in df.columns,
        "has_pos": "POS" in df.columns,
        "has_ea": "EA" in df.columns,
        "has_oa": "OA" in df.columns,
        "min_p": pd.to_numeric(df["P"], errors="coerce").min() if "P" in df.columns else np.nan,
        "example_snp": "; ".join(snp_examples)
    })

sig_pre_clump_qc = pd.DataFrame(inspect_records)

sig_pre_clump_qc_path = SUMMARY_DIR / "pre_ld_clumping_significant_variant_qc.csv"
sig_pre_clump_qc.to_csv(sig_pre_clump_qc_path, index=False)

display(sig_pre_clump_qc)
print("Saved to:", sig_pre_clump_qc_path)

,trait,file,rows,columns,rsid_like_count,non_rsid_count,has_chr,has_pos,has_ea,has_oa,min_p,example_snp
0,GDF15,/content/drive/MyDrive/UM_WQF7023/MRDRP-main/b...,81,"SNP, CHR, POS, EA, OA, BETA, SE, EAF, P, N",0,81,True,True,True,True,1.670000e-105,19:18388639:T:G; 19:18290081:A:C; 19:18202348:...
1,SHBG,/content/drive/MyDrive/UM_WQF7023/MRDRP-main/b...,8,"SNP, CHR, POS, EA, OA, BETA, SE, EAF, P, N",0,8,True,True,True,True,2.225070e-307,17:7631360:T:C; 17:7633269:A:G; 17:7631691:T:G...

Saved to: /content/drive/MyDrive/UM_WQF7023/MRDRP-main/backend_work/mr_outputs/summary/pre_ld_clumping_significant_variant_qc.csv

In [ ]:
# ============================================================
# Cell 23.2: rsID mapping helper using Ensembl REST
# ============================================================

import requests
import time

ENSEMBL_REST_SERVER = "https://rest.ensembl.org"

def query_ensembl_variants_by_position(chrom, pos, max_retries=3, sleep_seconds=0.15):
    """
    Query Ensembl REST API for variants overlapping one GRCh38 position.
    Returns a list of variant records.
    """
    chrom = str(chrom).replace("chr", "").strip()
    pos = int(pos)

    url = f"{ENSEMBL_REST_SERVER}/overlap/region/human/{chrom}:{pos}-{pos}"
    params = {"feature": "variation"}

    headers = {
        "Content-Type": "application/json",
        "Accept": "application/json"
    }

    for attempt in range(max_retries):
        try:
            r = requests.get(url, headers=headers, params=params, timeout=20)

            if r.status_code == 200:
                data = r.json()
                if isinstance(data, list):
                    return data
                return []

            if r.status_code in [429, 500, 502, 503, 504]:
                time.sleep(1 + attempt)
                continue

            return []

        except Exception:
            time.sleep(1 + attempt)

    return []


def pick_best_rsid_from_ensembl_records(records):
    """
    Pick the first rsID-like variant ID from Ensembl overlap records.
    """
    if records is None or len(records) == 0:
        return None

    rsids = []

    for rec in records:
        vid = str(rec.get("id", ""))
        if vid.startswith("rs"):
            rsids.append(vid)

    if len(rsids) > 0:
        return rsids[0]

    return None


def map_single_variant_to_rsid(row):
    """
    Map one row with CHR and POS to rsID.
    If the original SNP is already rsID, keep it.
    """
    original_snp = str(row.get("SNP", ""))

    if original_snp.startswith("rs"):
        return {
            "mapped_rsid": original_snp,
            "mapping_status": "already_rsid",
            "ensembl_record_count": np.nan
        }

    chrom = row.get("CHR", None)
    pos = row.get("POS", None)

    if pd.isna(chrom) or pd.isna(pos):
        return {
            "mapped_rsid": None,
            "mapping_status": "missing_chr_pos",
            "ensembl_record_count": 0
        }

    records = query_ensembl_variants_by_position(chrom, pos)
    mapped_rsid = pick_best_rsid_from_ensembl_records(records)

    if mapped_rsid is not None:
        return {
            "mapped_rsid": mapped_rsid,
            "mapping_status": "mapped_by_chr_pos",
            "ensembl_record_count": len(records)
        }

    return {
        "mapped_rsid": None,
        "mapping_status": "not_mapped",
        "ensembl_record_count": len(records)
    }

print("rsID mapping helper is ready.")

rsID mapping helper is ready.

In [ ]:
# ============================================================
# Cell 23.3: Map significant variants to rsID
# ============================================================

mapped_variant_records = []
mapped_file_records = []

for sig_file in sig_files:
    trait = sig_file.name.replace("_full_sig_variants.csv", "")
    df = pd.read_csv(sig_file)

    required_cols = ["SNP", "CHR", "POS", "EA", "OA", "BETA", "SE", "EAF", "P", "N"]
    for col in required_cols:
        if col not in df.columns:
            df[col] = pd.NA

    print("\n" + "=" * 100)
    print("Mapping rsID for:", trait)
    print("Input:", sig_file)
    print("Rows:", len(df))

    mapped_rows = []

    for idx, row in df.iterrows():
        mapping = map_single_variant_to_rsid(row)

        new_row = row.to_dict()
        new_row["trait"] = trait
        new_row["original_SNP"] = str(row.get("SNP", ""))
        new_row["mapped_rsid"] = mapping["mapped_rsid"]
        new_row["mapping_status"] = mapping["mapping_status"]
        new_row["ensembl_record_count"] = mapping["ensembl_record_count"]

        mapped_rows.append(new_row)

        if (idx + 1) % 20 == 0:
            print(f"Mapped {idx + 1}/{len(df)} variants...")

    mapped_df = pd.DataFrame(mapped_rows)

    mapped_output_file = LD_MAPPING_ROOT / f"{trait}_significant_variants_rsid_mapping.csv"
    mapped_df.to_csv(mapped_output_file, index=False)

    mapped_count = int(mapped_df["mapped_rsid"].notna().sum())
    already_rsid_count = int((mapped_df["mapping_status"] == "already_rsid").sum())
    mapped_by_pos_count = int((mapped_df["mapping_status"] == "mapped_by_chr_pos").sum())
    not_mapped_count = int((mapped_df["mapping_status"] == "not_mapped").sum())

    mapped_file_records.append({
        "trait": trait,
        "input_file": str(sig_file),
        "mapped_output_file": str(mapped_output_file),
        "total_variants": len(mapped_df),
        "mapped_rsid_count": mapped_count,
        "already_rsid_count": already_rsid_count,
        "mapped_by_chr_pos_count": mapped_by_pos_count,
        "not_mapped_count": not_mapped_count,
        "mapping_rate": mapped_count / len(mapped_df) if len(mapped_df) > 0 else 0
    })

    print("Saved:", mapped_output_file)
    print("Mapped rsID:", mapped_count, "/", len(mapped_df))

rsid_mapping_summary = pd.DataFrame(mapped_file_records)

rsid_mapping_summary_path = SUMMARY_DIR / "rsid_mapping_summary.csv"
rsid_mapping_summary.to_csv(rsid_mapping_summary_path, index=False)

print("\nrsID mapping summary:")
display(rsid_mapping_summary)
print("Saved to:", rsid_mapping_summary_path)

====================================================================================================
Mapping rsID for: GDF15
Input: /content/drive/MyDrive/UM_WQF7023/MRDRP-main/backend_work/significant_variants/GDF15_full_sig_variants.csv
Rows: 81
Mapped 20/81 variants...
Mapped 40/81 variants...
Mapped 60/81 variants...
Mapped 80/81 variants...
Saved: /content/drive/MyDrive/UM_WQF7023/MRDRP-main/backend_work/ld_clumping/rsid_mapping/GDF15_significant_variants_rsid_mapping.csv
Mapped rsID: 79 / 81

====================================================================================================
Mapping rsID for: SHBG
Input: /content/drive/MyDrive/UM_WQF7023/MRDRP-main/backend_work/significant_variants/SHBG_full_sig_variants.csv
Rows: 8
Saved: /content/drive/MyDrive/UM_WQF7023/MRDRP-main/backend_work/ld_clumping/rsid_mapping/SHBG_significant_variants_rsid_mapping.csv
Mapped rsID: 8 / 8

rsID mapping summary:

,trait,input_file,mapped_output_file,total_variants,mapped_rsid_count,already_rsid_count,mapped_by_chr_pos_count,not_mapped_count,mapping_rate
0,GDF15,/content/drive/MyDrive/UM_WQF7023/MRDRP-main/b...,/content/drive/MyDrive/UM_WQF7023/MRDRP-main/b...,81,79,0,79,2,0.975309
1,SHBG,/content/drive/MyDrive/UM_WQF7023/MRDRP-main/b...,/content/drive/MyDrive/UM_WQF7023/MRDRP-main/b...,8,8,0,8,0,1.000000

Saved to: /content/drive/MyDrive/UM_WQF7023/MRDRP-main/backend_work/mr_outputs/summary/rsid_mapping_summary.csv

In [ ]:
# ============================================================
# Cell 23.4: Prepare rsID-based input for LD clumping
# Corrected version: use pval.exposure for TwoSampleMR
# ============================================================

ld_input_records = []

for _, row in rsid_mapping_summary.iterrows():
    trait = row["trait"]
    mapped_file = Path(row["mapped_output_file"])

    mapped_df = pd.read_csv(mapped_file)

    clump_input = mapped_df[mapped_df["mapped_rsid"].notna()].copy()

    if len(clump_input) == 0:
        print(f"WARNING: No mapped rsID available for {trait}. Cannot prepare rsID-based clumping input.")
        ld_input_records.append({
            "trait": trait,
            "ld_input_file": None,
            "variants_for_clumping": 0,
            "status": "no_mapped_rsid"
        })
        continue

    clump_input["SNP"] = clump_input["mapped_rsid"].astype(str)
    clump_input["pval.exposure"] = pd.to_numeric(clump_input["P"], errors="coerce")
    clump_input["id.exposure"] = trait
    clump_input["exposure"] = trait

    clump_input = clump_input.dropna(subset=["SNP", "pval.exposure"])
    clump_input = clump_input.drop_duplicates(subset=["SNP"], keep="first")

    # Keep the full mapped table with the corrected clumping columns
    ld_input_file = LD_INPUT_ROOT / f"{trait}_ld_clump_input.csv"
    clump_input.to_csv(ld_input_file, index=False)

    ld_input_records.append({
        "trait": trait,
        "ld_input_file": str(ld_input_file),
        "variants_for_clumping": len(clump_input),
        "min_pval_exposure": clump_input["pval.exposure"].min(),
        "status": "ready_for_clumping"
    })

    print(f"{trait}: LD clumping input saved:", ld_input_file)
    print("Variants for clumping:", len(clump_input))
    print("Min pval.exposure:", clump_input["pval.exposure"].min())

ld_input_summary = pd.DataFrame(ld_input_records)

ld_input_summary_path = SUMMARY_DIR / "ld_clumping_input_summary.csv"
ld_input_summary.to_csv(ld_input_summary_path, index=False)

display(ld_input_summary)
print("Saved to:", ld_input_summary_path)

GDF15: LD clumping input saved: /content/drive/MyDrive/UM_WQF7023/MRDRP-main/backend_work/ld_clumping/ld_input_significant_variants/GDF15_ld_clump_input.csv
Variants for clumping: 79
Min pval.exposure: 1.67e-105
SHBG: LD clumping input saved: /content/drive/MyDrive/UM_WQF7023/MRDRP-main/backend_work/ld_clumping/ld_input_significant_variants/SHBG_ld_clump_input.csv
Variants for clumping: 8
Min pval.exposure: 2.22507e-307

,trait,ld_input_file,variants_for_clumping,min_pval_exposure,status
0,GDF15,/content/drive/MyDrive/UM_WQF7023/MRDRP-main/b...,79,1.670000e-105,ready_for_clumping
1,SHBG,/content/drive/MyDrive/UM_WQF7023/MRDRP-main/b...,8,2.225070e-307,ready_for_clumping

Saved to: /content/drive/MyDrive/UM_WQF7023/MRDRP-main/backend_work/mr_outputs/summary/ld_clumping_input_summary.csv

In [ ]:
# ============================================================
# Cell 23.5A: Set OpenGWAS JWT token safely
# ============================================================

import os
import getpass
import rpy2.robjects as robjects

OPENGWAS_JWT = getpass.getpass("Paste your OpenGWAS JWT token here: ").strip()

if OPENGWAS_JWT.startswith("Bearer "):
    OPENGWAS_JWT = OPENGWAS_JWT.replace("Bearer ", "").strip()

if len(OPENGWAS_JWT) == 0:
    raise ValueError("OpenGWAS JWT token is empty.")

if not OPENGWAS_JWT.startswith("eyJ"):
    print("WARNING: This token does not start with 'eyJ'. Please check whether you copied the correct JWT token.")

os.environ["OPENGWAS_JWT"] = OPENGWAS_JWT

# Pass token into R session used by rpy2
robjects.r.assign("opengwas_jwt_py", OPENGWAS_JWT)
robjects.r("Sys.setenv(OPENGWAS_JWT = opengwas_jwt_py)")

print("OpenGWAS JWT has been set in Python and R session.")
print("Token length:", len(OPENGWAS_JWT))
print("Token preview:", OPENGWAS_JWT[:10] + "..." + OPENGWAS_JWT[-10:])

Paste your OpenGWAS JWT token here: ··········
OpenGWAS JWT has been set in Python and R session.
Token length: 556
Token preview: eyJhbGciOi...gov6UrPIzg

In [ ]:
# ============================================================
# Check whether R can read OPENGWAS_JWT
# ============================================================

import os
import rpy2.robjects as robjects

print("Python token length:", len(os.environ.get("OPENGWAS_JWT", "")))

robjects.r("""
cat("R token length:", nchar(Sys.getenv("OPENGWAS_JWT")), "\\n")
cat("R token preview:", substr(Sys.getenv("OPENGWAS_JWT"), 1, 10), "...", "\\n")
""")

Python token length: 556
R token length: 556
R token preview: eyJhbGciOi ...

In [ ]:
# ============================================================
# Cell 23.5: Try TwoSampleMR LD clumping using mapped rsID
# Corrected version: uses pval.exposure and requires OpenGWAS JWT
# ============================================================

import os

# Make sure Cell 14 and Cell 23.5A have been run before this cell.
jwt_value = os.environ.get("OPENGWAS_JWT", "")

if len(jwt_value.strip()) == 0:
    raise ValueError(
        "OPENGWAS_JWT is not set. Please run Cell 23.5A with your OpenGWAS JWT token first."
    )

clump_records = []
clumped_variant_tables = []

CLUMP_KB = 10000
CLUMP_R2 = 0.001
CLUMP_POP = "EUR"

for _, row in ld_input_summary.iterrows():
    trait = row["trait"]

    if row["status"] != "ready_for_clumping":
        clump_records.append({
            "trait": trait,
            "status": "skipped",
            "input_variants": 0,
            "clumped_variants": 0,
            "method": "TwoSampleMR.clump_data",
            "error": "No mapped rsID available"
        })
        continue

    ld_input_file = Path(row["ld_input_file"])
    clump_input_df = pd.read_csv(ld_input_file)

    print("\n" + "=" * 100)
    print("Trying TwoSampleMR LD clumping for:", trait)
    print("Input variants:", len(clump_input_df))

    required_cols = ["SNP", "pval.exposure", "id.exposure", "exposure"]
    missing_cols = [c for c in required_cols if c not in clump_input_df.columns]

    if missing_cols:
        raise ValueError(f"Missing required clumping columns for {trait}: {missing_cols}")

    clump_input_for_r = clump_input_df[required_cols].copy()
    clump_input_for_r["SNP"] = clump_input_for_r["SNP"].astype(str)
    clump_input_for_r["pval.exposure"] = pd.to_numeric(
        clump_input_for_r["pval.exposure"],
        errors="coerce"
    )

    clump_input_for_r = clump_input_for_r.dropna(subset=["SNP", "pval.exposure"])

    try:
        with (robjects.default_converter + pandas2ri.converter).context():
            r_clump_input = robjects.conversion.get_conversion().py2rpy(clump_input_for_r)

        clumped_r = TwoSampleMR.clump_data(
            r_clump_input,
            clump_kb=CLUMP_KB,
            clump_r2=CLUMP_R2,
            pop=CLUMP_POP
        )

        clumped_df = r_to_pandas(clumped_r)

        if len(clumped_df) == 0:
            raise ValueError("TwoSampleMR clump_data returned zero variants.")

        clumped_rsids = set(clumped_df["SNP"].astype(str).tolist())

        original_mapped_file = LD_MAPPING_ROOT / f"{trait}_significant_variants_rsid_mapping.csv"
        original_mapped_df = pd.read_csv(original_mapped_file)

        clumped_full_df = original_mapped_df[
            original_mapped_df["mapped_rsid"].astype(str).isin(clumped_rsids)
        ].copy()

        clumped_output_file = LD_CLUMPED_ROOT / f"{trait}_ld_clumped_variants.csv"
        clumped_full_df.to_csv(clumped_output_file, index=False)

        clump_records.append({
            "trait": trait,
            "status": "success",
            "input_variants": len(clump_input_for_r),
            "clumped_variants": len(clumped_full_df),
            "method": f"TwoSampleMR.clump_data kb={CLUMP_KB}, r2={CLUMP_R2}, pop={CLUMP_POP}",
            "output_file": str(clumped_output_file),
            "error": None
        })

        clumped_variant_tables.append(clumped_full_df)

        print("Clumped variants:", len(clumped_full_df))
        print("Saved:", clumped_output_file)

    except Exception as e:
        print("TwoSampleMR clumping failed for", trait)
        print("Error:", e)

        clump_records.append({
            "trait": trait,
            "status": "failed",
            "input_variants": len(clump_input_for_r),
            "clumped_variants": 0,
            "method": f"TwoSampleMR.clump_data kb={CLUMP_KB}, r2={CLUMP_R2}, pop={CLUMP_POP}",
            "output_file": None,
            "error": str(e)
        })

ld_clumping_summary = pd.DataFrame(clump_records)

ld_clumping_summary_path = SUMMARY_DIR / "ld_clumping_summary.csv"
ld_clumping_summary.to_csv(ld_clumping_summary_path, index=False)

print("\nLD clumping summary:")
display(ld_clumping_summary)
print("Saved to:", ld_clumping_summary_path)

WARNING:rpy2.rinterface_lib.callbacks:R[write to console]: Please look at vignettes for options on running this locally if you need to run many instances of this command.

WARNING:rpy2.rinterface_lib.callbacks:R[write to console]: Clumping GDF15, 79 variants, using EUR population reference

====================================================================================================
Trying TwoSampleMR LD clumping for: GDF15
Input variants: 79

WARNING:rpy2.rinterface_lib.callbacks:R[write to console]: Removing 77 of 79 variants due to LD with other variants or absence from LD reference panel

WARNING:rpy2.rinterface_lib.callbacks:R[write to console]: Please look at vignettes for options on running this locally if you need to run many instances of this command.

WARNING:rpy2.rinterface_lib.callbacks:R[write to console]: Clumping SHBG, 8 variants, using EUR population reference

Clumped variants: 2
Saved: /content/drive/MyDrive/UM_WQF7023/MRDRP-main/backend_work/ld_clumping/ld_clumped_significant_variants/GDF15_ld_clumped_variants.csv

====================================================================================================
Trying TwoSampleMR LD clumping for: SHBG
Input variants: 8

WARNING:rpy2.rinterface_lib.callbacks:R[write to console]: Removing 7 of 8 variants due to LD with other variants or absence from LD reference panel

Clumped variants: 1
Saved: /content/drive/MyDrive/UM_WQF7023/MRDRP-main/backend_work/ld_clumping/ld_clumped_significant_variants/SHBG_ld_clumped_variants.csv

LD clumping summary:

,trait,status,input_variants,clumped_variants,method,output_file,error
0,GDF15,success,79,2,"TwoSampleMR.clump_data kb=10000, r2=0.001, pop...",/content/drive/MyDrive/UM_WQF7023/MRDRP-main/b...,None
1,SHBG,success,8,1,"TwoSampleMR.clump_data kb=10000, r2=0.001, pop...",/content/drive/MyDrive/UM_WQF7023/MRDRP-main/b...,None

Saved to: /content/drive/MyDrive/UM_WQF7023/MRDRP-main/backend_work/mr_outputs/summary/ld_clumping_summary.csv

In [ ]:
# ============================================================
# Cell 23.6: Prepare MR-ready clumped exposure files
# ============================================================

def make_coord_snp_id_from_df(df):
    chr_clean = pd.to_numeric(df["CHR"], errors="coerce").astype("Int64").astype(str)
    pos_clean = pd.to_numeric(df["POS"], errors="coerce").astype("Int64").astype(str)
    return chr_clean + ":" + pos_clean

mr_ready_clumped_records = []

clumped_files = sorted(LD_CLUMPED_ROOT.glob("*_ld_clumped_variants.csv"))

if len(clumped_files) == 0:
    print("WARNING: No LD-clumped variant files found.")
    print("Please check ld_clumping_summary. If TwoSampleMR clumping failed, try PLINK/reference-panel-based clumping next.")

for clumped_file in clumped_files:
    trait = clumped_file.name.replace("_ld_clumped_variants.csv", "")
    df = pd.read_csv(clumped_file)

    if len(df) == 0:
        print(f"WARNING: Empty clumped file for {trait}")
        continue

    for col in ["CHR", "POS", "EA", "OA", "BETA", "SE", "EAF", "P", "N"]:
        if col not in df.columns:
            df[col] = pd.NA

    df["original_SNP_before_mapping"] = df.get("original_SNP", df.get("SNP", ""))
    df["mapped_rsid_for_clumping"] = df["mapped_rsid"]
    df["SNP"] = make_coord_snp_id_from_df(df)

    keep_cols = [
        "SNP", "CHR", "POS", "EA", "OA", "BETA", "SE", "EAF", "P", "N",
        "original_SNP_before_mapping", "mapped_rsid_for_clumping",
        "mapping_status"
    ]

    available_cols = [c for c in keep_cols if c in df.columns]
    out = df[available_cols].copy()

    out = out.replace([np.inf, -np.inf], np.nan)
    out = out.dropna(subset=["SNP", "EA", "OA", "BETA", "SE", "P"])
    out = out.drop_duplicates(subset=["SNP"], keep="first")

    output_file = MR_READY_CLUMPED_SIG_ROOT / f"{trait}_mr_ready_clumped_sig_variants.csv"
    out.to_csv(output_file, index=False)

    mr_ready_clumped_records.append({
        "trait": trait,
        "input_file": str(clumped_file),
        "output_file": str(output_file),
        "rows": len(out),
        "min_p": pd.to_numeric(out["P"], errors="coerce").min() if len(out) > 0 else np.nan
    })

    print(f"{trait}: MR-ready clumped file saved:", output_file)
    print("Rows:", len(out))

mr_ready_clumped_summary = pd.DataFrame(mr_ready_clumped_records)

mr_ready_clumped_summary_path = SUMMARY_DIR / "mr_ready_clumped_exposure_summary.csv"
mr_ready_clumped_summary.to_csv(mr_ready_clumped_summary_path, index=False)

display(mr_ready_clumped_summary)
print("Saved to:", mr_ready_clumped_summary_path)

GDF15: MR-ready clumped file saved: /content/drive/MyDrive/UM_WQF7023/MRDRP-main/backend_work/mr_ready_clumped_significant_variants/GDF15_mr_ready_clumped_sig_variants.csv
Rows: 2
SHBG: MR-ready clumped file saved: /content/drive/MyDrive/UM_WQF7023/MRDRP-main/backend_work/mr_ready_clumped_significant_variants/SHBG_mr_ready_clumped_sig_variants.csv
Rows: 1

,trait,input_file,output_file,rows,min_p
0,GDF15,/content/drive/MyDrive/UM_WQF7023/MRDRP-main/b...,/content/drive/MyDrive/UM_WQF7023/MRDRP-main/b...,2,4.673000e-57
1,SHBG,/content/drive/MyDrive/UM_WQF7023/MRDRP-main/b...,/content/drive/MyDrive/UM_WQF7023/MRDRP-main/b...,1,3.544090e-11

Saved to: /content/drive/MyDrive/UM_WQF7023/MRDRP-main/backend_work/mr_outputs/summary/mr_ready_clumped_exposure_summary.csv

In [ ]:
# ============================================================
# Cell 23.7.0
# Recovery cell before Cell 23.7:
# Define helper function for loading SNP sets from CSV
# ============================================================

import pandas as pd
from pathlib import Path

def load_snp_set_from_csv(file_path, snp_col="SNP", chunksize=500000):
    """
    Load SNP identifiers from a large CSV file safely using chunks.
    This is used to check overlap between exposure SNPs and outcome SNPs.
    """
    file_path = Path(file_path)

    if not file_path.exists():
        raise FileNotFoundError(f"File not found: {file_path}")

    snp_set = set()

    for chunk in pd.read_csv(file_path, usecols=[snp_col], chunksize=chunksize):
        snps = chunk[snp_col].dropna().astype(str).tolist()
        snp_set.update(snps)

    return snp_set

print("load_snp_set_from_csv helper is ready.")

load_snp_set_from_csv helper is ready.

In [ ]:
# ============================================================
# Cell 23.7: Check clumped exposure-outcome overlap for multiple outcomes
# ============================================================

multi_outcome_prepare_path = SUMMARY_DIR / "multi_outcome_prepare_summary.csv"

if "multi_outcome_prepare_df" not in globals():
    if multi_outcome_prepare_path.exists():
        multi_outcome_prepare_df = pd.read_csv(multi_outcome_prepare_path)
        print("Loaded multi_outcome_prepare_df from:", multi_outcome_prepare_path)
    else:
        raise FileNotFoundError(
            "multi_outcome_prepare_df is not in memory and multi_outcome_prepare_summary.csv was not found. "
            "Please run Cell 18 first."
        )

clumped_sig_files = sorted(MR_READY_CLUMPED_SIG_ROOT.glob("*_mr_ready_clumped_sig_variants.csv"))

if len(clumped_sig_files) == 0:
    raise FileNotFoundError(
        f"No MR-ready clumped significant variant files found in {MR_READY_CLUMPED_SIG_ROOT}. "
        "Please complete Cell 23.5 and Cell 23.6 first."
    )

clumped_overlap_records = []

for _, outcome_row in multi_outcome_prepare_df.iterrows():
    if str(outcome_row["status"]).lower() != "prepared":
        continue

    set_name = outcome_row["set_name"]
    outcome_file = Path(outcome_row["mr_ready_outcome_file"])

    print("\n" + "=" * 100)
    print("Checking clumped overlap for:", set_name)

    outcome_snps = load_snp_set_from_csv(outcome_file)

    for exp_file in clumped_sig_files:
        trait = exp_file.name.replace("_mr_ready_clumped_sig_variants.csv", "")
        exp_df = pd.read_csv(exp_file)
        exp_snps = set(exp_df["SNP"].dropna().astype(str).tolist())

        overlap = sorted(list(exp_snps.intersection(outcome_snps)))

        clumped_overlap_records.append({
            "set_name": set_name,
            "trait": trait,
            "clumped_exposure_snps": len(exp_snps),
            "outcome_snps": len(outcome_snps),
            "overlap_snps": len(overlap),
            "example_overlap": overlap[0] if len(overlap) > 0 else None,
            "outcome_file": str(outcome_file),
            "clumped_exposure_file": str(exp_file),
        })

clumped_multi_outcome_overlap_df = pd.DataFrame(clumped_overlap_records)

clumped_overlap_path = SUMMARY_DIR / "clumped_multi_outcome_snp_overlap.csv"
clumped_multi_outcome_overlap_df.to_csv(clumped_overlap_path, index=False)

display(clumped_multi_outcome_overlap_df)
print("Saved to:", clumped_overlap_path)

====================================================================================================
Checking clumped overlap for: Artesunate_EndometrialCancer_GRCh38_OutcomeCompare_01

====================================================================================================
Checking clumped overlap for: Artesunate_EndometrialCancer_GRCh38_OutcomeCompare_02

====================================================================================================
Checking clumped overlap for: Artesunate_EndometrialCancer_GRCh38_OutcomeCompare_03

====================================================================================================
Checking clumped overlap for: Artesunate_EndometrialCancer_GRCh38_OutcomeCompare_04

====================================================================================================
Checking clumped overlap for: Artesunate_EndometrialCancer_GRCh38_OutcomeCompare_05

,set_name,trait,clumped_exposure_snps,outcome_snps,overlap_snps,example_overlap,outcome_file,clumped_exposure_file
0,Artesunate_EndometrialCancer_GRCh38_OutcomeCom...,GDF15,2,70453,0,None,/content/drive/MyDrive/UM_WQF7023/MRDRP-main/b...,/content/drive/MyDrive/UM_WQF7023/MRDRP-main/b...
1,Artesunate_EndometrialCancer_GRCh38_OutcomeCom...,SHBG,1,70453,1,17:7387376,/content/drive/MyDrive/UM_WQF7023/MRDRP-main/b...,/content/drive/MyDrive/UM_WQF7023/MRDRP-main/b...
2,Artesunate_EndometrialCancer_GRCh38_OutcomeCom...,GDF15,2,72811,0,None,/content/drive/MyDrive/UM_WQF7023/MRDRP-main/b...,/content/drive/MyDrive/UM_WQF7023/MRDRP-main/b...
3,Artesunate_EndometrialCancer_GRCh38_OutcomeCom...,SHBG,1,72811,1,17:7387376,/content/drive/MyDrive/UM_WQF7023/MRDRP-main/b...,/content/drive/MyDrive/UM_WQF7023/MRDRP-main/b...
4,Artesunate_EndometrialCancer_GRCh38_OutcomeCom...,GDF15,2,304277,0,None,/content/drive/MyDrive/UM_WQF7023/MRDRP-main/b...,/content/drive/MyDrive/UM_WQF7023/MRDRP-main/b...
5,Artesunate_EndometrialCancer_GRCh38_OutcomeCom...,SHBG,1,304277,1,17:7387376,/content/drive/MyDrive/UM_WQF7023/MRDRP-main/b...,/content/drive/MyDrive/UM_WQF7023/MRDRP-main/b...
6,Artesunate_EndometrialCancer_GRCh38_OutcomeCom...,GDF15,2,0,0,None,/content/drive/MyDrive/UM_WQF7023/MRDRP-main/b...,/content/drive/MyDrive/UM_WQF7023/MRDRP-main/b...
7,Artesunate_EndometrialCancer_GRCh38_OutcomeCom...,SHBG,1,0,0,None,/content/drive/MyDrive/UM_WQF7023/MRDRP-main/b...,/content/drive/MyDrive/UM_WQF7023/MRDRP-main/b...
8,Artesunate_EndometrialCancer_GRCh38_OutcomeCom...,GDF15,2,0,0,None,/content/drive/MyDrive/UM_WQF7023/MRDRP-main/b...,/content/drive/MyDrive/UM_WQF7023/MRDRP-main/b...
9,Artesunate_EndometrialCancer_GRCh38_OutcomeCom...,SHBG,1,0,0,None,/content/drive/MyDrive/UM_WQF7023/MRDRP-main/b...,/content/drive/MyDrive/UM_WQF7023/MRDRP-main/b...

Saved to: /content/drive/MyDrive/UM_WQF7023/MRDRP-main/backend_work/mr_outputs/summary/clumped_multi_outcome_snp_overlap.csv

In [ ]:
# ============================================================
# Cell 23.8: Run clumped MR for each outcome candidate
# ============================================================

clumped_mr_run_records = []
clumped_mr_result_tables = []

for _, outcome_row in multi_outcome_prepare_df.iterrows():
    if str(outcome_row["status"]).lower() != "prepared":
        continue

    set_name = outcome_row["set_name"]
    outcome_file = Path(outcome_row["mr_ready_outcome_file"])

    print("\n" + "#" * 120)
    print("Running clumped MR for outcome set:", set_name)
    print("Outcome file:", outcome_file)

    for exp_file in clumped_sig_files:
        trait = exp_file.name.replace("_mr_ready_clumped_sig_variants.csv", "")

        print("\n" + "=" * 100)
        print("Exposure:", trait)
        print("Clumped exposure file:", exp_file)

        try:
            exp_df = pd.read_csv(exp_file)

            if len(exp_df) == 0:
                raise ValueError("Clumped exposure file is empty.")

            exp_dat = TwoSampleMR.read_exposure_data(
                filename=str(exp_file),
                sep=",",
                snp_col="SNP",
                beta_col="BETA",
                se_col="SE",
                effect_allele_col="EA",
                other_allele_col="OA",
                eaf_col="EAF",
                pval_col="P",
                samplesize_col="N",
                chr_col="CHR",
                pos_col="POS",
                clump=False
            )

            snp_list = robjects.StrVector(exp_df["SNP"].dropna().astype(str).tolist())

            outcome_dat = TwoSampleMR.read_outcome_data(
                snps=snp_list,
                filename=str(outcome_file),
                sep=",",
                snp_col="SNP",
                beta_col="BETA",
                se_col="SE",
                effect_allele_col="EA",
                other_allele_col="OA",
                eaf_col="EAF",
                pval_col="P"
            )

            harmonised = TwoSampleMR.harmonise_data(exp_dat, outcome_dat)
            harmonised_py = r_to_pandas(harmonised)

            harmonised_snps = len(harmonised_py)
            print("Harmonised SNP count:", harmonised_snps)

            if harmonised_snps == 0:
                raise ValueError("No SNPs retained after harmonisation.")

            res = TwoSampleMR.mr(harmonised)
            res_py = r_to_pandas(res)

            try:
                pleiotropy = TwoSampleMR.mr_pleiotropy_test(harmonised)
                pleiotropy_py = r_to_pandas(pleiotropy)
            except Exception as e:
                pleiotropy_py = pd.DataFrame({"warning": [str(e)]})

            try:
                heterogeneity = TwoSampleMR.mr_heterogeneity(harmonised)
                heterogeneity_py = r_to_pandas(heterogeneity)
            except Exception as e:
                heterogeneity_py = pd.DataFrame({"warning": [str(e)]})

            res_py["set_name"] = set_name
            res_py["trait"] = trait
            res_py["outcome_file"] = str(outcome_file)
            res_py["harmonised_snps"] = harmonised_snps
            res_py["instrument_selection"] = "LD clumped"

            safe_name = f"{set_name}_{trait}_ld_clumped"

            res_py.to_csv(CLUMPED_MR_RESULTS_DIR / f"{safe_name}.csv", index=False)
            harmonised_py.to_csv(CLUMPED_MR_HARMONISED_DIR / f"{safe_name}.csv", index=False)
            pleiotropy_py.to_csv(CLUMPED_MR_PLEIOTROPY_DIR / f"{safe_name}.csv", index=False)
            heterogeneity_py.to_csv(CLUMPED_MR_HETEROGENEITY_DIR / f"{safe_name}.csv", index=False)

            clumped_mr_result_tables.append(res_py)

            clumped_mr_run_records.append({
                "set_name": set_name,
                "trait": trait,
                "status": "success",
                "harmonised_snps": harmonised_snps,
                "result_rows": len(res_py),
                "error": None,
            })

            display(res_py)

        except Exception as e:
            print("ERROR:", e)

            clumped_mr_run_records.append({
                "set_name": set_name,
                "trait": trait,
                "status": "failed",
                "harmonised_snps": 0,
                "result_rows": 0,
                "error": str(e),
            })

clumped_mr_run_df = pd.DataFrame(clumped_mr_run_records)

clumped_mr_run_path = SUMMARY_DIR / "clumped_multi_outcome_mr_run_summary.csv"
clumped_mr_run_df.to_csv(clumped_mr_run_path, index=False)

display(clumped_mr_run_df)
print("Saved to:", clumped_mr_run_path)

WARNING:rpy2.rinterface_lib.callbacks:R[write to console]: No phenotype name specified, defaulting to 'exposure'.

########################################################################################################################
Running clumped MR for outcome set: Artesunate_EndometrialCancer_GRCh38_OutcomeCompare_01
Outcome file: /content/drive/MyDrive/UM_WQF7023/MRDRP-main/backend_work/mr_outputs/outcome_comparison/mr_ready_outcomes/Artesunate_EndometrialCancer_GRCh38_OutcomeCompare_01/endometrial_cancer_mr_ready.csv

====================================================================================================
Exposure: GDF15
Clumped exposure file: /content/drive/MyDrive/UM_WQF7023/MRDRP-main/backend_work/mr_ready_clumped_significant_variants/GDF15_mr_ready_clumped_sig_variants.csv

WARNING:rpy2.rinterface_lib.callbacks:R[write to console]: Error in format_data(as.data.frame(outcome_dat), type = "outcome", snps = snps,  :
  No SNPs specified for the exposure are present in the outcome dataset.

WARNING:rpy2.rinterface_lib.callbacks:R[write to console]: In addition:
WARNING:rpy2.rinterface_lib.callbacks:R[write to console]: Warning message:

WARNING:rpy2.rinterface_lib.callbacks:R[write to console]: In format_data(as.data.frame(exposure_dat), type = "exposure", snps = NULL,  :
WARNING:rpy2.rinterface_lib.callbacks:R[write to console]:

WARNING:rpy2.rinterface_lib.callbacks:R[write to console]:  N column is not numeric

WARNING:rpy2.rinterface_lib.callbacks:R[write to console]: No phenotype name specified, defaulting to 'exposure'.

ERROR: Error in format_data(as.data.frame(outcome_dat), type = "outcome", snps = snps,  :
  No SNPs specified for the exposure are present in the outcome dataset.


====================================================================================================
Exposure: SHBG
Clumped exposure file: /content/drive/MyDrive/UM_WQF7023/MRDRP-main/backend_work/mr_ready_clumped_significant_variants/SHBG_mr_ready_clumped_sig_variants.csv

WARNING:rpy2.rinterface_lib.callbacks:R[write to console]: No phenotype name specified, defaulting to 'outcome'.

WARNING:rpy2.rinterface_lib.callbacks:R[write to console]: Harmonising exposure (a2epQ9) and outcome (5jcWBA)

WARNING:rpy2.rinterface_lib.callbacks:R[write to console]: Analysing 'a2epQ9' on '5jcWBA'

WARNING:rpy2.rinterface_lib.callbacks:R[write to console]: Not enough SNPs available for pleiotropy analysis of 'a2epQ9' on '5jcWBA'

WARNING:rpy2.rinterface_lib.callbacks:R[write to console]: Not enough SNPs available for Heterogeneity analysis of 'a2epQ9' on '5jcWBA'

Harmonised SNP count: 1

,id.exposure,id.outcome,outcome,exposure,method,nsnp,b,se,pval,set_name,trait,outcome_file,harmonised_snps,instrument_selection
1,a2epQ9,5jcWBA,outcome,exposure,Wald ratio,1.0,2.630739,3.335311,0.430256,Artesunate_EndometrialCancer_GRCh38_OutcomeCom...,SHBG,/content/drive/MyDrive/UM_WQF7023/MRDRP-main/b...,1,LD clumped

WARNING:rpy2.rinterface_lib.callbacks:R[write to console]: No phenotype name specified, defaulting to 'exposure'.

########################################################################################################################
Running clumped MR for outcome set: Artesunate_EndometrialCancer_GRCh38_OutcomeCompare_02
Outcome file: /content/drive/MyDrive/UM_WQF7023/MRDRP-main/backend_work/mr_outputs/outcome_comparison/mr_ready_outcomes/Artesunate_EndometrialCancer_GRCh38_OutcomeCompare_02/endometrial_cancer_mr_ready.csv

====================================================================================================
Exposure: GDF15
Clumped exposure file: /content/drive/MyDrive/UM_WQF7023/MRDRP-main/backend_work/mr_ready_clumped_significant_variants/GDF15_mr_ready_clumped_sig_variants.csv

WARNING:rpy2.rinterface_lib.callbacks:R[write to console]: Error in format_data(as.data.frame(outcome_dat), type = "outcome", snps = snps,  :
  No SNPs specified for the exposure are present in the outcome dataset.

WARNING:rpy2.rinterface_lib.callbacks:R[write to console]: In addition:
WARNING:rpy2.rinterface_lib.callbacks:R[write to console]: Warning messages:

WARNING:rpy2.rinterface_lib.callbacks:R[write to console]: 1:
WARNING:rpy2.rinterface_lib.callbacks:R[write to console]: In format_data(as.data.frame(exposure_dat), type = "exposure", snps = NULL,  :
WARNING:rpy2.rinterface_lib.callbacks:R[write to console]:

WARNING:rpy2.rinterface_lib.callbacks:R[write to console]:  N column is not numeric

WARNING:rpy2.rinterface_lib.callbacks:R[write to console]: 2:
WARNING:rpy2.rinterface_lib.callbacks:R[write to console]: In format_data(as.data.frame(exposure_dat), type = "exposure", snps = NULL,  :
WARNING:rpy2.rinterface_lib.callbacks:R[write to console]:

WARNING:rpy2.rinterface_lib.callbacks:R[write to console]:  N column is not numeric

WARNING:rpy2.rinterface_lib.callbacks:R[write to console]: No phenotype name specified, defaulting to 'exposure'.

ERROR: Error in format_data(as.data.frame(outcome_dat), type = "outcome", snps = snps,  :
  No SNPs specified for the exposure are present in the outcome dataset.


====================================================================================================
Exposure: SHBG
Clumped exposure file: /content/drive/MyDrive/UM_WQF7023/MRDRP-main/backend_work/mr_ready_clumped_significant_variants/SHBG_mr_ready_clumped_sig_variants.csv

WARNING:rpy2.rinterface_lib.callbacks:R[write to console]: No phenotype name specified, defaulting to 'outcome'.

WARNING:rpy2.rinterface_lib.callbacks:R[write to console]: Harmonising exposure (lZ6Pf6) and outcome (JtowDQ)

WARNING:rpy2.rinterface_lib.callbacks:R[write to console]: Analysing 'lZ6Pf6' on 'JtowDQ'

WARNING:rpy2.rinterface_lib.callbacks:R[write to console]: Not enough SNPs available for pleiotropy analysis of 'lZ6Pf6' on 'JtowDQ'

WARNING:rpy2.rinterface_lib.callbacks:R[write to console]: Not enough SNPs available for Heterogeneity analysis of 'lZ6Pf6' on 'JtowDQ'

Harmonised SNP count: 1

,id.exposure,id.outcome,outcome,exposure,method,nsnp,b,se,pval,set_name,trait,outcome_file,harmonised_snps,instrument_selection
1,lZ6Pf6,JtowDQ,outcome,exposure,Wald ratio,1.0,-0.822653,2.892323,0.776084,Artesunate_EndometrialCancer_GRCh38_OutcomeCom...,SHBG,/content/drive/MyDrive/UM_WQF7023/MRDRP-main/b...,1,LD clumped

WARNING:rpy2.rinterface_lib.callbacks:R[write to console]: No phenotype name specified, defaulting to 'exposure'.

########################################################################################################################
Running clumped MR for outcome set: Artesunate_EndometrialCancer_GRCh38_OutcomeCompare_03
Outcome file: /content/drive/MyDrive/UM_WQF7023/MRDRP-main/backend_work/mr_outputs/outcome_comparison/mr_ready_outcomes/Artesunate_EndometrialCancer_GRCh38_OutcomeCompare_03/endometrial_cancer_mr_ready.csv

====================================================================================================
Exposure: GDF15
Clumped exposure file: /content/drive/MyDrive/UM_WQF7023/MRDRP-main/backend_work/mr_ready_clumped_significant_variants/GDF15_mr_ready_clumped_sig_variants.csv

WARNING:rpy2.rinterface_lib.callbacks:R[write to console]: Error in format_data(as.data.frame(outcome_dat), type = "outcome", snps = snps,  :
  No SNPs specified for the exposure are present in the outcome dataset.

WARNING:rpy2.rinterface_lib.callbacks:R[write to console]: In addition:
WARNING:rpy2.rinterface_lib.callbacks:R[write to console]: Warning messages:

WARNING:rpy2.rinterface_lib.callbacks:R[write to console]: 1:
WARNING:rpy2.rinterface_lib.callbacks:R[write to console]: In format_data(as.data.frame(exposure_dat), type = "exposure", snps = NULL,  :
WARNING:rpy2.rinterface_lib.callbacks:R[write to console]:

WARNING:rpy2.rinterface_lib.callbacks:R[write to console]:  N column is not numeric

WARNING:rpy2.rinterface_lib.callbacks:R[write to console]: 2:
WARNING:rpy2.rinterface_lib.callbacks:R[write to console]: In format_data(as.data.frame(exposure_dat), type = "exposure", snps = NULL,  :
WARNING:rpy2.rinterface_lib.callbacks:R[write to console]:

WARNING:rpy2.rinterface_lib.callbacks:R[write to console]:  N column is not numeric

WARNING:rpy2.rinterface_lib.callbacks:R[write to console]: No phenotype name specified, defaulting to 'exposure'.

ERROR: Error in format_data(as.data.frame(outcome_dat), type = "outcome", snps = snps,  :
  No SNPs specified for the exposure are present in the outcome dataset.


====================================================================================================
Exposure: SHBG
Clumped exposure file: /content/drive/MyDrive/UM_WQF7023/MRDRP-main/backend_work/mr_ready_clumped_significant_variants/SHBG_mr_ready_clumped_sig_variants.csv

WARNING:rpy2.rinterface_lib.callbacks:R[write to console]: No phenotype name specified, defaulting to 'outcome'.

WARNING:rpy2.rinterface_lib.callbacks:R[write to console]: Harmonising exposure (ugNteI) and outcome (YYS6J5)

WARNING:rpy2.rinterface_lib.callbacks:R[write to console]: Analysing 'ugNteI' on 'YYS6J5'

WARNING:rpy2.rinterface_lib.callbacks:R[write to console]: Not enough SNPs available for pleiotropy analysis of 'ugNteI' on 'YYS6J5'

WARNING:rpy2.rinterface_lib.callbacks:R[write to console]: Not enough SNPs available for Heterogeneity analysis of 'ugNteI' on 'YYS6J5'

Harmonised SNP count: 1

,id.exposure,id.outcome,outcome,exposure,method,nsnp,b,se,pval,set_name,trait,outcome_file,harmonised_snps,instrument_selection
1,ugNteI,YYS6J5,outcome,exposure,Wald ratio,1.0,-0.024774,2.869653,0.993112,Artesunate_EndometrialCancer_GRCh38_OutcomeCom...,SHBG,/content/drive/MyDrive/UM_WQF7023/MRDRP-main/b...,1,LD clumped

WARNING:rpy2.rinterface_lib.callbacks:R[write to console]: No phenotype name specified, defaulting to 'exposure'.

########################################################################################################################
Running clumped MR for outcome set: Artesunate_EndometrialCancer_GRCh38_OutcomeCompare_04
Outcome file: /content/drive/MyDrive/UM_WQF7023/MRDRP-main/backend_work/mr_outputs/outcome_comparison/mr_ready_outcomes/Artesunate_EndometrialCancer_GRCh38_OutcomeCompare_04/endometrial_cancer_mr_ready.csv

====================================================================================================
Exposure: GDF15
Clumped exposure file: /content/drive/MyDrive/UM_WQF7023/MRDRP-main/backend_work/mr_ready_clumped_significant_variants/GDF15_mr_ready_clumped_sig_variants.csv

WARNING:rpy2.rinterface_lib.callbacks:R[write to console]: Error in format_data(as.data.frame(outcome_dat), type = "outcome", snps = snps,  :
  No SNPs specified for the exposure are present in the outcome dataset.

WARNING:rpy2.rinterface_lib.callbacks:R[write to console]: In addition:
WARNING:rpy2.rinterface_lib.callbacks:R[write to console]: Warning messages:

WARNING:rpy2.rinterface_lib.callbacks:R[write to console]: 1:
WARNING:rpy2.rinterface_lib.callbacks:R[write to console]: In format_data(as.data.frame(exposure_dat), type = "exposure", snps = NULL,  :
WARNING:rpy2.rinterface_lib.callbacks:R[write to console]:

WARNING:rpy2.rinterface_lib.callbacks:R[write to console]:  N column is not numeric

WARNING:rpy2.rinterface_lib.callbacks:R[write to console]: 2:
WARNING:rpy2.rinterface_lib.callbacks:R[write to console]: In format_data(as.data.frame(exposure_dat), type = "exposure", snps = NULL,  :
WARNING:rpy2.rinterface_lib.callbacks:R[write to console]:

WARNING:rpy2.rinterface_lib.callbacks:R[write to console]:  N column is not numeric

WARNING:rpy2.rinterface_lib.callbacks:R[write to console]: No phenotype name specified, defaulting to 'exposure'.

WARNING:rpy2.rinterface_lib.callbacks:R[write to console]: Error in format_data(as.data.frame(outcome_dat), type = "outcome", snps = snps,  :
  No SNPs specified for the exposure are present in the outcome dataset.

WARNING:rpy2.rinterface_lib.callbacks:R[write to console]: In addition:
WARNING:rpy2.rinterface_lib.callbacks:R[write to console]: Warning message:

WARNING:rpy2.rinterface_lib.callbacks:R[write to console]: In format_data(as.data.frame(exposure_dat), type = "exposure", snps = NULL,  :
WARNING:rpy2.rinterface_lib.callbacks:R[write to console]:

WARNING:rpy2.rinterface_lib.callbacks:R[write to console]:  N column is not numeric

WARNING:rpy2.rinterface_lib.callbacks:R[write to console]: No phenotype name specified, defaulting to 'exposure'.

WARNING:rpy2.rinterface_lib.callbacks:R[write to console]: Error in format_data(as.data.frame(outcome_dat), type = "outcome", snps = snps,  :
  No SNPs specified for the exposure are present in the outcome dataset.

WARNING:rpy2.rinterface_lib.callbacks:R[write to console]: In addition:
WARNING:rpy2.rinterface_lib.callbacks:R[write to console]: Warning message:

WARNING:rpy2.rinterface_lib.callbacks:R[write to console]: In format_data(as.data.frame(exposure_dat), type = "exposure", snps = NULL,  :
WARNING:rpy2.rinterface_lib.callbacks:R[write to console]:

WARNING:rpy2.rinterface_lib.callbacks:R[write to console]:  N column is not numeric

WARNING:rpy2.rinterface_lib.callbacks:R[write to console]: No phenotype name specified, defaulting to 'exposure'.

WARNING:rpy2.rinterface_lib.callbacks:R[write to console]: Error in format_data(as.data.frame(outcome_dat), type = "outcome", snps = snps,  :
  No SNPs specified for the exposure are present in the outcome dataset.

WARNING:rpy2.rinterface_lib.callbacks:R[write to console]: In addition:
WARNING:rpy2.rinterface_lib.callbacks:R[write to console]: Warning message:

WARNING:rpy2.rinterface_lib.callbacks:R[write to console]: In format_data(as.data.frame(exposure_dat), type = "exposure", snps = NULL,  :
WARNING:rpy2.rinterface_lib.callbacks:R[write to console]:

WARNING:rpy2.rinterface_lib.callbacks:R[write to console]:  N column is not numeric

ERROR: Error in format_data(as.data.frame(outcome_dat), type = "outcome", snps = snps,  :
  No SNPs specified for the exposure are present in the outcome dataset.


====================================================================================================
Exposure: SHBG
Clumped exposure file: /content/drive/MyDrive/UM_WQF7023/MRDRP-main/backend_work/mr_ready_clumped_significant_variants/SHBG_mr_ready_clumped_sig_variants.csv
ERROR: Error in format_data(as.data.frame(outcome_dat), type = "outcome", snps = snps,  :
  No SNPs specified for the exposure are present in the outcome dataset.


########################################################################################################################
Running clumped MR for outcome set: Artesunate_EndometrialCancer_GRCh38_OutcomeCompare_05
Outcome file: /content/drive/MyDrive/UM_WQF7023/MRDRP-main/backend_work/mr_outputs/outcome_comparison/mr_ready_outcomes/Artesunate_EndometrialCancer_GRCh38_OutcomeCompare_05/endometrial_cancer_mr_ready.csv

====================================================================================================
Exposure: GDF15
Clumped exposure file: /content/drive/MyDrive/UM_WQF7023/MRDRP-main/backend_work/mr_ready_clumped_significant_variants/GDF15_mr_ready_clumped_sig_variants.csv
ERROR: Error in format_data(as.data.frame(outcome_dat), type = "outcome", snps = snps,  :
  No SNPs specified for the exposure are present in the outcome dataset.


====================================================================================================
Exposure: SHBG
Clumped exposure file: /content/drive/MyDrive/UM_WQF7023/MRDRP-main/backend_work/mr_ready_clumped_significant_variants/SHBG_mr_ready_clumped_sig_variants.csv
ERROR: Error in format_data(as.data.frame(outcome_dat), type = "outcome", snps = snps,  :
  No SNPs specified for the exposure are present in the outcome dataset.

,set_name,trait,status,harmonised_snps,result_rows,error
0,Artesunate_EndometrialCancer_GRCh38_OutcomeCom...,GDF15,failed,0,0,Error in format_data(as.data.frame(outcome_dat...
1,Artesunate_EndometrialCancer_GRCh38_OutcomeCom...,SHBG,success,1,1,None
2,Artesunate_EndometrialCancer_GRCh38_OutcomeCom...,GDF15,failed,0,0,Error in format_data(as.data.frame(outcome_dat...
3,Artesunate_EndometrialCancer_GRCh38_OutcomeCom...,SHBG,success,1,1,None
4,Artesunate_EndometrialCancer_GRCh38_OutcomeCom...,GDF15,failed,0,0,Error in format_data(as.data.frame(outcome_dat...
5,Artesunate_EndometrialCancer_GRCh38_OutcomeCom...,SHBG,success,1,1,None
6,Artesunate_EndometrialCancer_GRCh38_OutcomeCom...,GDF15,failed,0,0,Error in format_data(as.data.frame(outcome_dat...
7,Artesunate_EndometrialCancer_GRCh38_OutcomeCom...,SHBG,failed,0,0,Error in format_data(as.data.frame(outcome_dat...
8,Artesunate_EndometrialCancer_GRCh38_OutcomeCom...,GDF15,failed,0,0,Error in format_data(as.data.frame(outcome_dat...
9,Artesunate_EndometrialCancer_GRCh38_OutcomeCom...,SHBG,failed,0,0,Error in format_data(as.data.frame(outcome_dat...

Saved to: /content/drive/MyDrive/UM_WQF7023/MRDRP-main/backend_work/mr_outputs/summary/clumped_multi_outcome_mr_run_summary.csv

In [ ]:
# ============================================================
# Cell 23.9: Combine clumped MR results
# ============================================================

if len(clumped_mr_result_tables) > 0:
    clumped_combined_mr_results = pd.concat(clumped_mr_result_tables, ignore_index=True)

    if "b" in clumped_combined_mr_results.columns:
        clumped_combined_mr_results["MR_OR"] = np.exp(clumped_combined_mr_results["b"])

    if "b" in clumped_combined_mr_results.columns and "se" in clumped_combined_mr_results.columns:
        clumped_combined_mr_results["MR_OR_lower_95CI"] = np.exp(
            clumped_combined_mr_results["b"] - 1.96 * clumped_combined_mr_results["se"]
        )
        clumped_combined_mr_results["MR_OR_upper_95CI"] = np.exp(
            clumped_combined_mr_results["b"] + 1.96 * clumped_combined_mr_results["se"]
        )

    if "pval" in clumped_combined_mr_results.columns:
        clumped_combined_mr_results["nominal_significant"] = clumped_combined_mr_results["pval"] < 0.05

    if "clumped_multi_outcome_overlap_df" in globals() and len(clumped_multi_outcome_overlap_df) > 0:
        overlap_for_merge = clumped_multi_outcome_overlap_df[[
            "set_name", "trait", "overlap_snps"
        ]].drop_duplicates()

        clumped_combined_mr_results = clumped_combined_mr_results.merge(
            overlap_for_merge,
            on=["set_name", "trait"],
            how="left"
        )

    if "pval" in clumped_combined_mr_results.columns:
        clumped_combined_mr_results = clumped_combined_mr_results.sort_values(
            by=["trait", "pval"],
            ascending=[True, True]
        )

    clumped_combined_path = SUMMARY_DIR / "clumped_multi_outcome_combined_mr_results.csv"
    clumped_combined_mr_results.to_csv(clumped_combined_path, index=False)

    display(clumped_combined_mr_results)
    print("Saved to:", clumped_combined_path)

else:
    clumped_combined_mr_results = pd.DataFrame()
    print("No clumped MR result tables were generated.")

,id.exposure,id.outcome,outcome,exposure,method,nsnp,b,se,pval,set_name,trait,outcome_file,harmonised_snps,instrument_selection,MR_OR,MR_OR_lower_95CI,MR_OR_upper_95CI,nominal_significant,overlap_snps
0,a2epQ9,5jcWBA,outcome,exposure,Wald ratio,1.0,2.630739,3.335311,0.430256,Artesunate_EndometrialCancer_GRCh38_OutcomeCom...,SHBG,/content/drive/MyDrive/UM_WQF7023/MRDRP-main/b...,1,LD clumped,13.884031,0.020111,9584.944534,False,1
1,lZ6Pf6,JtowDQ,outcome,exposure,Wald ratio,1.0,-0.822653,2.892323,0.776084,Artesunate_EndometrialCancer_GRCh38_OutcomeCom...,SHBG,/content/drive/MyDrive/UM_WQF7023/MRDRP-main/b...,1,LD clumped,0.439265,0.001516,127.268677,False,1
2,ugNteI,YYS6J5,outcome,exposure,Wald ratio,1.0,-0.024774,2.869653,0.993112,Artesunate_EndometrialCancer_GRCh38_OutcomeCom...,SHBG,/content/drive/MyDrive/UM_WQF7023/MRDRP-main/b...,1,LD clumped,0.975530,0.003520,270.357642,False,1

Saved to: /content/drive/MyDrive/UM_WQF7023/MRDRP-main/backend_work/mr_outputs/summary/clumped_multi_outcome_combined_mr_results.csv

In [ ]:
# ============================================================
# Cell 23.10: Generate LD clumping report
# ============================================================

from datetime import datetime

report_lines = []

report_lines.append("# LD Clumping Improvement Report")
report_lines.append("")
report_lines.append(f"Run time: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
report_lines.append("")

report_lines.append("## Purpose")
report_lines.append("")
report_lines.append(
    "This section improves the previous backend MR prototype by adding an LD clumping step. "
    "The purpose is to select more independent genetic instruments before MR analysis."
)
report_lines.append("")

report_lines.append("## Pre-clumping significant variant summary")
report_lines.append("")
if "sig_pre_clump_qc" in globals() and len(sig_pre_clump_qc) > 0:
    report_lines.append(sig_pre_clump_qc.to_markdown(index=False))
else:
    report_lines.append("Pre-clumping QC table is not available.")
report_lines.append("")

report_lines.append("## rsID mapping summary")
report_lines.append("")
if "rsid_mapping_summary" in globals() and len(rsid_mapping_summary) > 0:
    report_lines.append(rsid_mapping_summary.to_markdown(index=False))
else:
    report_lines.append("rsID mapping summary is not available.")
report_lines.append("")

report_lines.append("## LD clumping summary")
report_lines.append("")
if "ld_clumping_summary" in globals() and len(ld_clumping_summary) > 0:
    report_lines.append(ld_clumping_summary.to_markdown(index=False))
else:
    report_lines.append("LD clumping summary is not available.")
report_lines.append("")

report_lines.append("## MR-ready clumped exposure summary")
report_lines.append("")
if "mr_ready_clumped_summary" in globals() and len(mr_ready_clumped_summary) > 0:
    report_lines.append(mr_ready_clumped_summary.to_markdown(index=False))
else:
    report_lines.append("MR-ready clumped exposure summary is not available.")
report_lines.append("")

report_lines.append("## Clumped SNP overlap summary")
report_lines.append("")
if "clumped_multi_outcome_overlap_df" in globals() and len(clumped_multi_outcome_overlap_df) > 0:
    report_lines.append(clumped_multi_outcome_overlap_df.to_markdown(index=False))
else:
    report_lines.append("Clumped SNP overlap summary is not available.")
report_lines.append("")

report_lines.append("## Clumped MR run summary")
report_lines.append("")
if "clumped_mr_run_df" in globals() and len(clumped_mr_run_df) > 0:
    report_lines.append(clumped_mr_run_df.to_markdown(index=False))
else:
    report_lines.append("Clumped MR run summary is not available.")
report_lines.append("")

report_lines.append("## Clumped combined MR results")
report_lines.append("")
if "clumped_combined_mr_results" in globals() and len(clumped_combined_mr_results) > 0:
    report_lines.append(clumped_combined_mr_results.to_markdown(index=False))
else:
    report_lines.append("No clumped combined MR results are available.")
report_lines.append("")

report_lines.append("## Interpretation note")
report_lines.append("")
report_lines.append(
    "The clumping step uses mapped rsID where available. If rsID mapping or TwoSampleMR clumping fails, "
    "a reference-panel-based PLINK approach should be used as the next method. "
    "The clumped MR outputs should be compared with the previous coordinate-based prototype results."
)

ld_report_text = "\n".join(report_lines)

ld_report_path = SUMMARY_DIR / "ld_clumping_improvement_report.md"

with open(ld_report_path, "w", encoding="utf-8") as f:
    f.write(ld_report_text)

print("LD clumping improvement report saved to:", ld_report_path)
print("\nPreview:")
print(ld_report_text[:3000])

LD clumping improvement report saved to: /content/drive/MyDrive/UM_WQF7023/MRDRP-main/backend_work/mr_outputs/summary/ld_clumping_improvement_report.md

Preview:
# LD Clumping Improvement Report

Run time: 2026-06-01 04:59:04

## Purpose

This section improves the previous backend MR prototype by adding an LD clumping step. The purpose is to select more independent genetic instruments before MR analysis.

## Pre-clumping significant variant summary

| trait   | file                                                                                                       |   rows | columns                                    |   rsid_like_count |   non_rsid_count | has_chr   | has_pos   | has_ea   | has_oa   |        min_p | example_snp                                                                         |
|:--------|:-----------------------------------------------------------------------------------------------------------|-------:|:-------------------------------------------|------------------:|-----------------:|:----------|:----------|:---------|:---------|-------------:|:------------------------------------------------------------------------------------|
| GDF15   | /content/drive/MyDrive/UM_WQF7023/MRDRP-main/backend_work/significant_variants/GDF15_full_sig_variants.csv |     81 | SNP, CHR, POS, EA, OA, BETA, SE, EAF, P, N |                 0 |               81 | True      | True      | True     | True     | 1.67e-105    | 19:18388639:T:G; 19:18290081:A:C; 19:18202348:T:C; 19:18249079:A:G; 19:18135235:T:C |
| SHBG    | /content/drive/MyDrive/UM_WQF7023/MRDRP-main/backend_work/significant_variants/SHBG_full_sig_variants.csv  |      8 | SNP, CHR, POS, EA, OA, BETA, SE, EAF, P, N |                 0 |                8 | True      | True      | True     | True     | 2.22507e-307 | 17:7631360:T:C; 17:7633269:A:G; 17:7631691:T:G; 17:7770907:T:G; 17:7818933:T:C      |

## rsID mapping summary

| trait   | input_file                                                                                                 | mapped_output_file                                                                                                             |   total_variants |   mapped_rsid_count |   already_rsid_count |   mapped_by_chr_pos_count |   not_mapped_count |   mapping_rate |
|:--------|:-----------------------------------------------------------------------------------------------------------|:-------------------------------------------------------------------------------------------------------------------------------|-----------------:|--------------------:|---------------------:|--------------------------:|-------------------:|---------------:|
| GDF15   | /content/drive/MyDrive/UM_WQF7023/MRDRP-main/backend_work/significant_variants/GDF15_full_sig_variants.csv | /content/drive/MyDrive/UM_WQF7023/MRDRP-main/backend_work/ld_clumping/rsid_mapping/GDF15_significant_variants_rsid_mapping.csv |               81 |                  79 |                    0 |                        79 |                  2 |       0.975309 |
| SHBG    | /content/drive/MyDrive/UM_WQF7023/MRDRP-main/backend_work/significant_variants/SHBG_fu

In [ ]:
import pandas as pd
from pathlib import Path

PROJECT_ROOT = Path("/content/drive/MyDrive/UM_WQF7023/MRDRP-main")
SUMMARY_DIR = PROJECT_ROOT / "backend_work" / "mr_outputs" / "summary"

clumped_result_file = SUMMARY_DIR / "clumped_multi_outcome_combined_mr_results.csv"

df = pd.read_csv(clumped_result_file)

print("Shape:", df.shape)
display(df)

Shape: (3, 19)

,id.exposure,id.outcome,outcome,exposure,method,nsnp,b,se,pval,set_name,trait,outcome_file,harmonised_snps,instrument_selection,MR_OR,MR_OR_lower_95CI,MR_OR_upper_95CI,nominal_significant,overlap_snps
0,a2epQ9,5jcWBA,outcome,exposure,Wald ratio,1.0,2.630739,3.335311,0.430256,Artesunate_EndometrialCancer_GRCh38_OutcomeCom...,SHBG,/content/drive/MyDrive/UM_WQF7023/MRDRP-main/b...,1,LD clumped,13.884031,0.020111,9584.944534,False,1
1,lZ6Pf6,JtowDQ,outcome,exposure,Wald ratio,1.0,-0.822653,2.892323,0.776084,Artesunate_EndometrialCancer_GRCh38_OutcomeCom...,SHBG,/content/drive/MyDrive/UM_WQF7023/MRDRP-main/b...,1,LD clumped,0.439265,0.001516,127.268677,False,1
2,ugNteI,YYS6J5,outcome,exposure,Wald ratio,1.0,-0.024774,2.869653,0.993112,Artesunate_EndometrialCancer_GRCh38_OutcomeCom...,SHBG,/content/drive/MyDrive/UM_WQF7023/MRDRP-main/b...,1,LD clumped,0.975530,0.003520,270.357642,False,1